### ISSUE TITLE
add new tokenizer merge recipe

### ISSUE THREAD

**Issue by enpassanty** [ymcui/Chinese-LLaMA-Alpaca-2#101]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] I have read the [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki) and [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), we recommend checking the corresponding project for solutions

### Type of Issue

Other issues

### Base Model

LLaMA-2-7B

### Operating System

Linux

### Describe your issue in detail

you mentioned in the docs that this project both extended and redesigned the tokenizer vocabulary you used.  Did you merge tokenizers in a different way than you did in the[ first generation project](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_tokenizer/merge_tokenizers.py)?  I want to use your approach to pre-train llama-2 on my own custom data.  Would you recommend I use first gen tokenizer merge approach, or are you planning to post a new recipe for a different tokenizer merge strategy you used in generation 2?  thank you!

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

```
# Please copy-and-paste your logs here.
```

**Comment by airaria** [comment]
The merge strategy is the same as the one in the Chinese-LLaMA-Alpaca project.
The difference is that we retrain the Chinese tokenizer with a large vocabulary size to enlarge the vocabulary of the merged tokenizer to 55296.
