### ISSUE TITLE
Chinese-Alpaca-2-LoRA-7B是怎么训练得到的？

### ISSUE THREAD

**Issue by weilx2267** [ymcui/Chinese-LLaMA-Alpaca-2#102]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

你好，我想问一下Chinese-Alpaca-2-LoRA-7B权重是基于[Llama-2-7B-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf)直接指令微调得到的，还是在Chinese-LLaMA-2-LoRA-7B基础上继续指令微调得到的？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
```
[2023/07/31] 正式发布Chinese-LLaMA-2-7B（基座模型），使用120G中文语料增量训练（与一代Plus系列相同）；进一步通过5M条指令数据精调（相比一代略微增加），得到Chinese-Alpaca-2-7B（指令/chat模型）。
```

即：Llama-2 -> Chinese-LLaMA-2 -> Chinese-Alpaca-2

**Comment by weilx2267** [comment]
感谢！！！
