### ISSUE TITLE
是否可以自己训练llama2_70b？

### ISSUE THREAD

**Issue by Lyn4ever29** [ymcui/Chinese-LLaMA-Alpaca-2#106]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

请问我是否可以按照wiki所写的那样，使用训练脚本对llama2_13b和lama2_70b进行词表扩充和训练呢？
或者说，chinese_llama2_70b什么时候开源呢

**Comment by ymcui** [comment]
中文70B尚未启动。
另外，Llama-2 70B模型是有GQA的，我们现有的脚本没有添加这部分，所以不能直接拿去用。

**Comment by Double-bear** [comment]
> 中文70B尚未启动。 另外，Llama-2 70B模型是有GQA的，我们现有的脚本没有添加这部分，所以不能直接拿去用。

请问GQA会如何影响训练？我用预训练的脚本尝试了Llama2-70B的预训练，似乎没有报错，loss也是正常下降的，想请问一下问题出在哪里？

**Comment by yqli2420** [comment]
> 

因为你没有使用flash attn加速直接使用transformer中的attention

**Comment by yqli2420** [comment]
> 

@Double-bear 因为你没有使用flash attn加速直接使用transformer中的attention

**Comment by Double-bear** [comment]
> > 
> 
> @Double-bear 因为你没有使用flash attn加速直接使用transformer中的attention

我用了flash_attn，只是改了flashattn的那个脚本让它可以在70B上跑了。如果只是flashattn的问题那应该就没事了，我以为是除了flashattn还有别的问题我没有注意到的。

**Comment by yqli2420** [comment]
> > > 
> > 
> > 
> > @Double-bear 因为你没有使用flash attn加速直接使用transformer中的attention
> 
> 我用了flash_attn，只是改了flashattn的那个脚本让它可以在70B上跑了。如果只是flashattn的问题那应该就没事了，我以为是除了flashattn还有别的问题我没有注意到的。
改了patch支持gqa能训起来就没啥问题

**Comment by yoosan** [comment]
> 

你用预训练70b用的lora还是全参数呢，用的啥卡
我这边跑的时候一直oom

**Comment by yoosan** [comment]
> > 中文70B尚未启动。 另外，Llama-2 70B模型是有GQA的，我们现有的脚本没有添加这部分，所以不能直接拿去用。
> 
> 请问GQA会如何影响训练？我用预训练的脚本尝试了Llama2-70B的预训练，似乎没有报错，loss也是正常下降的，想请问一下问题出在哪里？

你用预训练70b用的lora还是全参数呢，用的啥卡
我这边跑的时候，用deepspeed + lora都会oom
