### ISSUE TITLE
请教一下申请Lliama2模型下载Meta审批流程需要多久？

### ISSUE THREAD

**Issue by young-yang03** [ymcui/Chinese-LLaMA-Alpaca-2#11]
一周前就申请了Meat Llama2 模型下载，但是Meta侧一直没有完成审批。

请问，你们申请了多久，Meta侧就完成了审批？填写 https://ai.meta.com/resources/models-and-libraries/llama-downloads/ 中的申请信息时，有什么需要注意的吗？比如，国家不能填写中国？

**Comment by ymcui** [comment]
当时是1天内获得了资格，现在不太清楚。
你可以考虑换一个邮箱申请，其他信息如实填写。

**Comment by iswsc** [comment]
几分钟就获得了

**Comment by jediyoda36** [comment]
半天时间就拿到了

**Comment by moye12325** [comment]
三分钟

**Comment by young-yang03** [comment]
谢谢大家
