### ISSUE TITLE
Langchain的最后一项环境准备下载不了pip install faiss-gpu==1.7.2

### ISSUE THREAD

**Issue by YLlllllllllll** [ymcui/Chinese-LLaMA-Alpaca-2#112]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型量化和部署

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
pip install faiss-gpu==1.7.2

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
ctransformers                  0.2.5
sentence-transformers          2.2.2
torch                          2.0.1
torchvision                    0.15.2
transformers                   4.31.0

### 运行日志或截图

```
# 请在此处粘贴运行日志
```ERROR: Could not find a version that satisfies the requirement faiss-gpu==1.7.2 (from versions: 1.5.3, 1.6.0, 1.6.1, 1.6.3, 1.6.4, 1.6.4.post2, 1.6.5, 1.7.0, 1.7.1, 1.7.1.post1, 1.7.1.post2)
ERROR: No matching distribution found for faiss-gpu==1.7.2

**Comment by YLlllllllllll** [comment]
另外可以问一下下载好的模型应该放在哪里吗，还是直接运行langchain的那个代码。

现在有三个文件，github项目，langchain，Chinese-Alpaca-2-7B模型
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/32410985-ef57-4411-a5d1-ecf08360bce8)

**Comment by YLlllllllllll** [comment]
我试了让他安装后续低级版本，发现全都不允许，找时间试试官方版本

**Comment by iMountTai** [comment]
`pip install faiss-gpu==1.7.1`也是可以的,亲测可运行。

**Comment by YLlllllllllll** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/207b0937-38c8-4144-be28-dc1ffc454a68)
我后续的版本都试了，github的原版也试了，可能是电脑显卡问题，这个电脑是集显，没有Nvidia和CUDA

**Comment by YLlllllllllll** [comment]
langchain环境部署gpu是必须的吗
