### ISSUE TITLE
指令精调数据格式问题

### ISSUE THREAD

**Issue by icoderzqliu** [ymcui/Chinese-LLaMA-Alpaca-2#115]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

请问您所说的“本项目中的Alpaca-2系列模型简化了系统提示语，同时遵循Llama-2-Chat指令模板，以便更好地适配相关生态”中，Llama-2-chat指令模板是在哪看到的呢？我在Llama-2论文中没找到相关的描述。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by icoderzqliu** [comment]
不是应该在做指令微调的时候，用多样化的指令效果更好吗？我在代码中只找到了这一份模板，请问Llama-2-chat在做sft的时候也是只用了这一个模板吗？
```
PROMPT_TEMPLATE = (
        "[INST] <<SYS>>\n"
        "You are a helpful assistant. 你是一个乐于助人的助手。\n"
        "<</SYS>>\n\n{instruction} [/INST]"
    )
```

**Comment by ymcui** [comment]
> 不是应该在做指令微调的时候，用多样化的指令效果更好吗？我在代码中只找到了这一份模板，请问Llama-2-chat在做sft的时候也是只用了这一个模板吗？
> 
> ```
> PROMPT_TEMPLATE = (
>         "[INST] <<SYS>>\n"
>         "You are a helpful assistant. 你是一个乐于助人的助手。\n"
>         "<</SYS>>\n\n{instruction} [/INST]"
>     )
> ```

论文里没有，你要去llama开源的目录里找。
这个你列的这个不是指令，是指令模板。指令是要填到{instruction}字段里。
如果你说的是system prompt，这个看你自己，想多样化也无所谓，只不过我们训练的时候没有更改system prompt。

**Comment by icoderzqliu** [comment]
> > 不是应该在做指令微调的时候，用多样化的指令效果更好吗？我在代码中只找到了这一份模板，请问Llama-2-chat在做sft的时候也是只用了这一个模板吗？
> > ```
> > PROMPT_TEMPLATE = (
> >         "[INST] <<SYS>>\n"
> >         "You are a helpful assistant. 你是一个乐于助人的助手。\n"
> >         "<</SYS>>\n\n{instruction} [/INST]"
> >     )
> > ```
> 
> 论文里没有，你要去llama开源的目录里找。 这个你列的这个不是指令，是指令模板。指令是要填到{instruction}字段里。 如果你说的是system prompt，这个看你自己，想多样化也无所谓，只不过我们训练的时候没有更改system prompt。

好的理解了。请问一下llama-2在做sft的时候也是只遵循了这一个指令模板吗？
```
<s>[INST] <<SYS>>
{{ system_prompt }}
<</SYS>>

{{ user_message }} [/INST]
```

**Comment by ymcui** [comment]
这个是原版的，你可以看一下原代码：https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L44

**Comment by laserwave** [comment]
@ymcui 请问alpaca2在训练的过程中构造instruction的时候有role的设置吗，llama2使用了user和assistant的设置，在如下的预测示例里没有看到设置role：
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/inference/inference_hf.py
