### ISSUE TITLE
训练一半退出继续训练

### ISSUE THREAD

**Issue by altria-zewei-wang** [ymcui/Chinese-LLaMA-Alpaca-2#117]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

训练到一半WSL自己退出了，想问一下继续训练的话需要修改config和路径吗，有没有相关教程可以参考一下谢谢

**Comment by YinSonglin1997** [comment]
1. 修改脚本文件：删除--overwrite_output_dir，增加--resume_from_checkpoint
2. 修改/anaconda3/envs/环境/lib/pythonx.x/site-packages/deepspeed/runtime/engine.py，将函数load_checkpoint定义中的参数load_module_strict默认值改为False
