### ISSUE TITLE
System prompt的相关结论

### ISSUE THREAD

**Issue by laserwave** [ymcui/Chinese-LLaMA-Alpaca-2#119]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

其他问题

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/prompts/README.md
中提到有alpaca-2.txt以及alpaca-2-long.txt，并且对前者的描述是 “这个文件是训练时采用的默认系统指令，内容极简，因此回复长度上略短于一代Pro系列模型。”

请问此结论是否是指，使用alpaca-2.txt对比使用alpaca-2-long.txt作为system prompt，模型有生成更短内容的倾向。即使指令中包含“简述”、“详述”这样的字样也有这个问题吗？发布的最新模型是基于哪一个system prompt进行训练的？

### 依赖情况（代码类问题务必提供）

无

### 运行日志或截图

无

**Comment by ymcui** [comment]
alpaca-2.txt是训练时使用的。
