### ISSUE TITLE
Gradio运行报错 Help!!!

### ISSUE THREAD

**Issue by YLlllllllllll** [ymcui/Chinese-LLaMA-Alpaca-2#120]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型量化和部署

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
python Chinese-LLaMA-Alpaca-2/scripts/inference/gradio_demo.py --base_model chinese-alpaca-2-7b --load_in_4bit
我把环境部署好了，测了一下python -m bitsandbytes也没问题，但是我不太确定启动命令是不是正确的，如果是正确的那这个报错是因为啥呢，截图可以看到我的文件位置。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
peft                      0.3.0.dev0
torch                     2.0.1
torchvision               0.15.2
transformers              4.31.0

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/8e0cb67c-c912-41d4-aa14-d620e277353f)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/894f2770-41a2-4090-9e86-5480a512bf0a)

**Comment by YLlllllllllll** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/3f8041bb-6901-4ddd-a87c-8784cca19a80)
我又试了一下版本1的项目，也是跟着colab弄的，最后出现的error都是一样的

**Comment by ymcui** [comment]
你可以查看下载的模型是否是完整的。`chinese-alpaca-2-7b`这个目录内的文件是从哪里下载的？
如果是从huggingface上git clone下来的，是否开启git lfs了？不开启的话下载的模型文件只是一个空壳子。

**Comment by YLlllllllllll** [comment]
好，我重新下一个试试，之前本地有一份我给删了

**Comment by YLlllllllllll** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/c2dfe4ad-ddcf-4f0a-9090-a37add45684c)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/0c53dad2-afa3-447e-80bd-b59397fe6d9e)
我重新下了一下这两个模型，然后从本地upload到的jupyter文件夹里面，但是还是报错了，可以看看是为啥吗

**Comment by ymcui** [comment]
1. `ls`一下`chinese-alppaca-2-7b`这个目录看一下里面都有什么文件
2. 不需要指定`--tokenizer_path`。
3. 是否检查了这两个bin文件的SHA256？分别是：
```
182d552f893db16f7196afdf6ec13f05b43650985c9ce71f41f6d576e978c53f
1f22e3d669ea912c4b0428fb4095f2068eb6192c89406ddd441de87ccec0c1b5
```

**Comment by YLlllllllllll** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/69372e9f-305f-4bec-8c54-9d72c3d6a810)
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/a14bc033-c68e-44e1-89f0-f334acca768d)
这样吗？
这两个bin文件我点开是空的不知道为啥，明明是上传的

**Comment by ymcui** [comment]
不是。SHA256.md是给你用来校验用的。如果你是linux，执行`sha256sum 文件名`来获取对应的SHA256校验值。你要比对和SHA256.md中所列值是否一致。
如果你打开bin文件是空的，多半是你的模型文件还是下载的不对。不太清楚你从哪儿下载的。之前也说了，如果是huggingface上git clone下来的，必须先开启LFS。
```
# Make sure you have git-lfs installed (https://git-lfs.com)
git lfs install
git clone https://huggingface.co/ziqingyang/chinese-alpaca-2-7b
```

**Comment by YLlllllllllll** [comment]
因为我这个用的是远程服务器，远程的jupyter我没权限下载git lfs，用不了所以我直接点的那个下载按钮，下到了本地，然后上传的

**Comment by ymcui** [comment]
两个bin文件差不多有14G，你看看这两个文件大小吧，也可以本地校验一下上面说的SHA256校验值。
如果你本地的文件没问题那就是你上传过程出问题了。

**Comment by YLlllllllllll** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/114622851/541722e9-2697-4794-b50b-d222c523a33f)
这是本地的，咋打开bin文件查看校验值阿

**Comment by ymcui** [comment]
命令行：
```
certutil -hashfile your-model-file sha256
```

其他方法自己google找一下吧。
