### ISSUE TITLE
请问如何通过API方式访问7B

### ISSUE THREAD

**Issue by heiheiheibj** [ymcui/Chinese-LLaMA-Alpaca-2#124]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

效果问题

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
请问如何通过API方式访问7B，是调用地址http://localhost:19324/v1/completions吗 
怎么试都是返回"detail": "Not Found"
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/6910198/09047844-832f-4a05-836a-8bfbc2f4d243)

还有就是在WEB方式下，多几轮对话，有时会报显存不够

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by iMountTai** [comment]
我们没有提供相应API供调用，可参考[推理与部署](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#推理与部署)自行搭建API

**Comment by heiheiheibj** [comment]
好的。谢谢

**Comment by airaria** [comment]
API服务的搭建：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/api_calls_zh

> 多几轮对话，有时会报显存不够

减少gradio_demo.py 启动参数 max_memory 的值试试。

**Comment by heiheiheibj** [comment]
好的。谢谢。。
