### ISSUE TITLE
能否给出privategpt的完整用法

### ISSUE THREAD

**Issue by weipeng3020** [ymcui/Chinese-LLaMA-Alpaca-2#126]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

其他问题

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

请大佬给出关于privategpt的完整设置及代码更换方案，自己实际调试实在是报错的搞不定，万分感谢

 raise Exception(f"Model type {model_type} is not supported. Please choose one of the following: LlamaCpp, GPT4All")
Exception: Model type chinese-alpaca-2-7b is not supported. Please choose one of the following: LlamaCpp, GPT4All

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/privategpt_zh 这里不就是教程么

**Comment by weipeng3020** [comment]
> https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/privategpt_zh 这里不就是教程么

感谢大佬抽出时间回复小白问题！！！！
我按照里面的提示修改了代码，运行的时候提示：找不到模型 还有 AttributeError: 'Llama' object has no attribute 'ctx'
是不是我env里面设置的不对，您能给一个 修改好能运行的env吗？
个人电脑：13600kf+3070

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/privategpt_zh#step-2-修改配置文件
step 2这里提供的`.env`就是实际可用的示例。
```
MODEL_TYPE=LlamaCpp
PERSIST_DIRECTORY=db
MODEL_PATH=your-path-to-ggml-model.bin
MODEL_N_CTX=4096
MODEL_N_BATCH=512
EMBEDDINGS_MODEL_NAME=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
TARGET_SOURCE_CHUNKS=4
```

其中`MODEL_PATH`需要指定实际的GGML模型位置，`EMBEDDINGS_MODEL_NAME`可改可不改。

**Comment by Danielyy** [comment]
根据Privategpt中的env设置，使用了
```
MODEL_PATH=models/ggml-gpt4all-j-v1.3-groovy.bin
EMBEDDINGS_MODEL_NAME=all-MiniLM-L6-v2
```
那么如果要换成Chinese-Alpaca-2-13B 模型该如何设置。从Chinese-LLaMA-Alpaca-2模型下载中下载的模型是个目录，其中bin文件有3个，那么该如何设置env中的参数，可以正确使用？

**Comment by ymcui** [comment]
@Danielyy 我建议你还是仔细阅读一下wiki，里面都有写。
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/privategpt_zh#step-2-修改配置文件
里面的`MODEL_PATH`指向的是llama.cpp格式的模型文件，不是原版HF格式（就是你说的3个bin文件）。HF转成llama.cpp格式之后只有一个输出文件。
