### ISSUE TITLE
执行openai_api_server.py时报错ModuleNotFoundError: No module named 'attn_and_long_ctx_patches'

### ISSUE THREAD

**Issue by Shimooth** [ymcui/Chinese-LLaMA-Alpaca-2#135]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

其他问题

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

执行命令python openai_api_server.py --base_model zh-models/7B/ggml-model-q4_0.bin 时报错ModuleNotFoundError: No module named 'attn_and_long_ctx_patches'
更新了pip也没能安装attn_and_long_ctx_patches，也没找到手动下载的链接
有同志遇到这个错误吗，或者有没有什么解决的思路？

### 依赖情况（代码类问题务必提供）

peft                                   0.2.0
sentence-transformers     2.2.2
torch                                 2.0.1
torchvision                        0.15.2
transformers                     4.30.2

### 运行日志或截图

╭──────────────────────── Traceback (most recent call last) ────────────────────────╮
│ /mnt/TOSHIBA_MQ4/shiyq/Alpaca2/cuBLAS.llama.cpp/openai_api_server.py:43 in        │
│ <module>                                                                          │
│                                                                                   │
│    40                                                                             │
│    41 parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))    │
│    42 sys.path.append(parent_dir)                                                 │
│ ❱  43 from attn_and_long_ctx_patches import apply_attention_patch, apply_ntk_scal │
│    44                                                                             │
│    45 apply_attention_patch(use_memory_efficient_attention=True)                  │
│    46 apply_ntk_scaling_patch(args.alpha)                                         │
╰───────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'attn_and_long_ctx_patches'

**Comment by ymcui** [comment]
文件在这里：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/attn_and_long_ctx_patches.py
你可以手动放在同一目录下。

**Comment by Shimooth** [comment]
> 文件在这里：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/attn_and_long_ctx_patches.py 你可以手动放在同一目录下。

感谢感谢！！
该报错已经解决了，但是在执行python openai_api_server.py --base_model ../cuBLAS.llama.cpp/zh-models/7B/ggml-model-q4_0.bin命令之后还是没能启动服务，以下是输出的日志，是我还需要配置什么东西吗？
USE_MEM_EFF_ATTENTION:  True
STORE_KV_BEFORE_ROPE: False
Apply NTK scaling with ALPHA=1.0
/root/miniconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1727: FutureWarning: Calling LlamaTokenizer.from_pretrained() with the path to a single file or url is deprecated and won't be possible anymore in v5. Use a model identifier or the path to a directory instead.
  warnings.warn(
python: src/../third_party/protobuf-lite/google/protobuf/stubs/stringpiece.h:229: google::protobuf::StringPiece::StringPiece(const char*, google::protobuf::stringpiece_ssize_type): Assertion `len >= 0' failed.
已放弃(吐核)

**Comment by ymcui** [comment]
你仔细看一下文档：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/api_calls_zh
看你的文件名是GGML格式的，并不是HF格式。

**Comment by Shimooth** [comment]
> 你仔细看一下文档：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/api_calls_zh 看你的文件名是GGML格式的，并不是HF格式。

原来如此！！我错以为是.bin的就可以，我把路径改成HF的目录解决了芜湖！
大佬永远不死永远活着mua mua
