### ISSUE TITLE
cpu推理时报错：`.float()` is not supported for quantized model.

### ISSUE THREAD

**Issue by fanlisaddas** [ymcui/Chinese-LLaMA-Alpaca-2#136]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

LLaMA-2-7B

### 操作系统

Windows

### 详细描述问题

```
python Chinese-LLaMA-Alpaca-2/scripts/inference/inference_hf.py \
--base_model llama2/7B_full_model \
--with_prompt \
--interactive \
--only_cpu
```

### 依赖情况（代码类问题务必提供）

```
peft                         0.4.0
torch                        2.0.1
torchvision                  0.15.2
transformers                 4.32.0.dev0 D:\myworkplace\transformers
```

### 运行日志或截图

报错信息：
<img width="473" alt="企业微信截图_1692009512821" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/55045155/2a83027c-eba9-41a9-8ba5-9a87dc6abefd">
定位代码：
```
# Chinese-LLaMA-Alpaca-2/scripts/inference/inference_hf.py
base_model = LlamaForCausalLM.from_pretrained(
    args.base_model,
    torch_dtype=load_type,
    low_cpu_mem_usage=True,
    device_map='auto',
    quantization_config=BitsAndBytesConfig(
        load_in_4bit=args.load_in_4bit,
        load_in_8bit=args.load_in_8bit,
        bnb_4bit_compute_dtype=load_type
    )
)
```
推理脚本中使用`quantization`并配置参数。在`cpu`上推理时：
```
# Chinese-LLaMA-Alpaca-2/scripts/inference/inference_hf.py
if device==torch.device('cpu'):
    model.float()
```
而`transformers`中定义的`.float()`中：
```
# transformers\src\transformers\modeling_utils.py
def float(self, *args):
    # Checks if the model is quantized
    if getattr(self, "is_quantized", False):
        raise ValueError(
            "`.float()` is not supported for quantized model. Please use the model as it is, since the"
            " model has already been casted to the correct `dtype`."
        )
    else:
        return super().float(*args)
```
因此`cpu`使用`quantization`推理时调用`.float()`会报错：``.float()` is not supported for quantized model.`

**Comment by airaria** [comment]
load_in_4bit和load_in8bit都是False吗？

**Comment by fanlisaddas** [comment]
> load_in_4bit和load_in8bit都是False吗？
是的，如果不是前面这里就会报错：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/55045155/67d082ad-bbfc-4c4c-b6ea-b95ed7a1fbe9)

**Comment by airaria** [comment]
你把
```
quantization_config=BitsAndBytesConfig(
        load_in_4bit=args.load_in_4bit,
        load_in_8bit=args.load_in_8bit,
        bnb_4bit_compute_dtype=load_type
    )
```
整个删掉试试？
