### ISSUE TITLE
Cevals评测结果无法复现

### ISSUE THREAD

**Issue by wang99711123** [ymcui/Chinese-LLaMA-Alpaca-2#138]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

效果问题

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
CUDA_VISIBLE_DEVICES=7 python eval.py \
    --model_path ${model_path} \
    --cot False \
    --few_shot False \
    --with_prompt True \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir ${output_path} \
```

### 依赖情况（代码类问题务必提供）

```
peft                     0.3.0
torch                    2.0.0
transformers             4.31.0
```

### 运行日志或截图

您好，我使用repo提供的脚本在cevals的valset上进行评测，模型使用hf上的chinese-llama2（https://huggingface.co/ziqingyang/chinese-llama-2-7b/tree/main），但是zeroshot复现不出相应的结果。
得到的结果如下
```
  "All": {
    "score": 0.2310549777117385,
    "num": 1346,
    "correct": 311.0
  }
```
请问是由于超参数的原因吗，有没有可供参考的、能复现对应结果的超参数呢

**Comment by wang99711123** [comment]
我把prompt去掉了，得到了相对正常的结果。

**Comment by wang99711123** [comment]
但是在复现alpaca的性能时，我用上面的参数，zeroshot性能基本可以复现，但是5shot的性能较差，这个请问是为什么呢
```
"All": {
    "score": 0.2934621099554235,
    "num": 1346,
    "correct": 395.0
  }
```

**Comment by ymcui** [comment]
> 但是在复现alpaca的性能时，我用上面的参数，zeroshot性能基本可以复现，但是5shot的性能较差，这个请问是为什么呢
> 
> ```
> "All": {
>     "score": 0.2934621099554235,
>     "num": 1346,
>     "correct": 395.0
>   }
> ```

5-shot的命令？

**Comment by wang99711123** [comment]
> > 但是在复现alpaca的性能时，我用上面的参数，zeroshot性能基本可以复现，但是5shot的性能较差，这个请问是为什么呢
> > ```
> > "All": {
> >     "score": 0.2934621099554235,
> >     "num": 1346,
> >     "correct": 395.0
> >   }
> > ```
> 
> 5-shot的命令？
尝试过修改cot  和 constrained_decoding ，得到的性能差不多
```
CUDA_VISIBLE_DEVICES=7 python eval.py \
    --model_path ${model_path} \
    --cot False \
    --few_shot True \
    --with_prompt True \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir ${output_path} \
```

**Comment by ymcui** [comment]
你可以试试`--with_prompt False`

**Comment by wang99711123** [comment]
好的谢谢

**Comment by catqaq** [comment]
hi，我遇到了类似的问题：
'''
python eval.py \
    --model_path ${model_path} \
    --cot False \
    --few_shot False \
    --with_prompt True \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir ${output_path} \
'''
chinese-llama-2-7b和chinese-alpaca-2-7b的5-shot效果分别为0.23和0.41，比官方的要差一些
