### ISSUE TITLE
预训练代码中设置‘tokenizer.add_eos_token = True’有何影响？

### ISSUE THREAD

**Issue by TengLi931128** [ymcui/Chinese-LLaMA-Alpaca-2#140]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

None

### 操作系统

None

### 详细描述问题

我看到相比之前你们llama的预训练代码，这次llama2的预训练代码，设置了tokenizer.add_eos_token = True。
请问，为何会有这样的改变？这样改变效果如何？llama的预训练是否也需要这样调整？

**Comment by iMountTai** [comment]
一定程度上可以解决chinese-llama生成不能停止的问题。

**Comment by YinSonglin1997** [comment]
> 一定程度上可以解决chinese-llama生成不能停止的问题。

您好，我加入了这行代码，可我二次预训练之后的模型在回复时依旧不能停止，还会有重复的回答。请问这是什么原因呢？
