### ISSUE TITLE
lora指令微调后保存的adapter_model.bin只有127k，请问怎么回事呢，已经按照另一个issue的方案注释了代码

### ISSUE THREAD

**Issue by yingzhao27** [ymcui/Chinese-LLaMA-Alpaca-2#141]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
old_state_dict = model.state_dict

model.state_dict = (
    lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
).__get__(model, type(model))
```
lora指令微调后保存的adapter_model.bin只有127k，(用了zero2），请问是什么原因呢

### 依赖情况（代码类问题务必提供）

deepspeed               0.9.2
peft                    0.3.0.dev0
torch                   1.13.1
transformers            4.28.0.dev0                               /public/home/zhaoying1/install/transformers-main

### 运行日志或截图

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /public/home/zhaoying1/work/Chinese-LLaMA-Alpaca-2-main/Chinese-LLaMA-Alpaca-2-main/scripts/merg │
│ e_llama2_with_chinese_lora_low_mem.py:246 in <module>                                            │
│                                                                                                  │
│   243 │   │   print("!!!!!!!",lora_state_dict['base_model.model.model.embed_tokens.weight'].sh   │
│   244 │   │   lora_vocab_size = lora_state_dict['base_model.model.model.embed_tokens.weight'].   │
│   245 │   │   assert lora_vocab_size==len(tokenizer), \                                          │
│ ❱ 246 │   │   (f"The vocab size of the tokenizer {len(tokenizer)} does not match the vocab siz   │
│   247 │   tokenizers_and_loras.append(                                                           │
│   248 │   │   {                                                                                  │
│   249 │   │   │   "tokenizer"  :tokenizer,                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: The vocab size of the tokenizer 55296 does not match the vocab size of the LoRA weight 0!
```

**Comment by iMountTai** [comment]
zero2为什么要注释掉那几行代码？

**Comment by yingzhao27** [comment]
> 

不注释也是只有一百多k

**Comment by iMountTai** [comment]
先按照[requirements](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/requirements.txt)和[预训练脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/pt_scripts_zh)配置训练参数吧。torch版本理论上不影响训练，可能影响flash-attn 2等特性的应用。

**Comment by iMountTai** [comment]
您再调试一下吧，代码本身确定没问题的。

**Comment by yingzhao27** [comment]
> 您再调试一下吧，代码本身确定没问题的。

我从log看
```
Model vocab size: 0 
Resize model vocab size to 55296
```
请问这是否正常呢

**Comment by iMountTai** [comment]
不正常，你确定你用的是zero2?把你的训练脚本贴出来吧

**Comment by yingzhao27** [comment]
> 不正常，你确定你用的是zero2?把你的训练脚本贴出来吧

现在用的zero3；用slurm在集群上训练的，以下是mpirun的内容
```
lr=5e-5
lora_rank=16
lora_alpha=322
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/public/home/zhaoying1/work/model_scope/chinese-llama2-7b
chinese_tokenizer_path=/public/home/zhaoying1/work/model_scope/chinese-llama2-7b/
dataset_dir=/public/home/zhaoying1/work/Chinese-LLaMA-Alpaca-2-main/Chinese-LLaMA-Alpaca-2-main/data_alpaca
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
output_dir=/public/home/zhaoying1/work/Chinese-LLaMA-Alpaca-2-main/Chinese-LLaMA-Alpaca-2-main/scripts/training/output_dir_sft_nooffload_5e-5_10epoch-test
max_seq_length=1024

deepspeed_config_file=/public/home/zhaoying1/work/Chinese-LLaMA-Alpaca-2-main/Chinese-LLaMA-Alpaca-2-main/scripts/training/ds_zero2_no_offload.json


APP="python3 ../scripts/training/run_clm_sft_with_peft.py --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 5 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length 1024 \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False
"
```

**Comment by yingzhao27** [comment]
ds_zero2_no_offload.json内容：
```
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 100,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1e-10
    },

    "zero_optimization": {
        "stage": 3,
        "allgather_partitions": true,
        "allgather_bucket_size": 1e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 1e8,
        "contiguous_gradients": true
    },
    "stage3_gather_16bit_weights_on_model_save": true,
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 2000,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}

```

**Comment by iMountTai** [comment]
你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。

**Comment by yingzhao27** [comment]
> 你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。

好的，如果zero3的话，Model vocab size: 0是正常的吗

**Comment by Daniel-Xing** [comment]
> > 你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。
> 
> 好的，如果zero3的话，Model vocab size: 0是正常的吗

您好，我也遇到了一样的问题，当我设置stage=2时，Model vocab size是正常的，但是当stage=3时，就出现了问题。我怀疑是不是huggingface transformer库的问题

**Comment by xiaoqi25478** [comment]
> > > 你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。
> > 
> > 
> > 好的，如果zero3的话，Model vocab size: 0是正常的吗
> 
> 您好，我也遇到了一样的问题，当我设置stage=2时，Model vocab size是正常的，但是当stage=3时，就出现了问题。我怀疑是不是huggingface transformer库的问题

我也碰到这个问题

**Comment by airaria** [comment]
使用zero3会出现这种情况。可以用sft_lora_model上一级目录中的adapter_model.bin合并。

**Comment by xiaoqi25478** [comment]
> 使用zero3会出现这种情况。可以用sft_lora_model上一级目录中的adapter_model.bin合并。

没看到呀

**Comment by xiaoqi25478** [comment]
> > > 你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。
> > 
> > 
> > 好的，如果zero3的话，Model vocab size: 0是正常的吗
> 
> 您好，我也遇到了一样的问题，当我设置stage=2时，Model vocab size是正常的，但是当stage=3时，就出现了问题。我怀疑是不是huggingface transformer库的问题

请问解决了吗

**Comment by Double-bear** [comment]
> > 你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。
> 
> 好的，如果zero3的话，Model vocab size: 0是正常的吗

请问这个问题解决了吗？

**Comment by iMountTai** [comment]
有没有存储中间模型？`checkpoint-steps`下面应该也有`adapter_model.bin`

**Comment by panpanli521** [comment]
> > > > 你大部分依赖版本都与我们要求的不同，目前没有有效的建议可以提出。如果是transformers 4.31，可以尝试将`checkpoint-500`下面的`adapter_model.bin`复制到`sft_lora_model`下再进行合并。
> > > 
> > > 
> > > 好的，如果zero3的话，Model vocab size: 0是正常的吗
> > 
> > 
> > 您好，我也遇到了一样的问题，当我设置stage=2时，Model vocab size是正常的，但是当stage=3时，就出现了问题。我怀疑是不是huggingface transformer库的问题
> 
> 我也碰到这个问题

同遇到了这个问题，bash run_pt.sh里开了zero3
`Chinese-LLaMA-Alpaca-2-main/scripts/merge_llama2_with_chinese_lora_low_mem.py", line 244, in <module>
    assert lora_vocab_size==len(tokenizer), \
AssertionError: The vocab size of the tokenizer 55296 does not match the vocab size of the LoRA weight 0!`
请问有人解决了吗？

**Comment by panpanli521** [comment]
使用zero3做完lora训练后，执行scripts/merge_llama2_with_chinese_lora_low_mem.py，出现
`scripts/merge_llama2_with_chinese_lora_low_mem.py", line 245, in <module>
    assert lora_vocab_size==len(tokenizer), \
AssertionError: The vocab size of the tokenizer 55296 does not match the vocab size of the LoRA weight 0!`
请问是代码层面本身就不支持吗？
@iMountTai

**Comment by ymcui** [comment]
> 使用zero3做完lora训练后，执行scripts/merge_llama2_with_chinese_lora_low_mem.py，出现 `scripts/merge_llama2_with_chinese_lora_low_mem.py", line 245, in <module> assert lora_vocab_size==len(tokenizer), \ AssertionError: The vocab size of the tokenizer 55296 does not match the vocab size of the LoRA weight 0!` 请问是代码层面本身就不支持吗？ @iMountTai

@panpanli521 assert里提示很清楚了，说明你的LoRA权重的词向量大小并不是我们规定的55296。具体你怎么用ZeRO-3训的LoRA 麻烦你新开一个issue，写明具体流程。

**Comment by panpanli521** [comment]
好的 多谢
