### ISSUE TITLE
预训练的正确流程是怎样的？

### ISSUE THREAD

**Issue by Faysir** [ymcui/Chinese-LLaMA-Alpaca-2#143]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

目前看预训练的wiki，有些疑惑，我的最终目的是训练一个可以处理专业领域知识的对话模型，想请问正确的流程是怎样的？
目前准备了领域的预训练数据和sft数据，当前的做法是，1. 基于完整版Chinese-Alpaca-2-7B开始做预训练，得到pt_lora；2. 将pt_lora和完整版Chinese-Alpaca-2-7B合并，得到预训练之后的全量模型；3. 基于完整版Chinese-Alpaca-2-7B模型和1同时开始做的SFT训练，得到sft_lora；4. 将2得到的合并模型和3得到的sft_lora再次合并。

这种流程对么？有几个疑问，a. 2中合并得到的模型丧失了原版Chinese-Alpaca-2-7B的对话能力，开始有些自言自语；b. 3中的sft是应该基于原版Chinese-Alpaca-2-7B还是基于2中合并之后的预训练模型呢？c. 这种预训练的范式，怎么样的流程能保证你们提供的基础的5M alpaca对话能力不丢失？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
```
1. 基于完整版Chinese-Alpaca-2-7B开始做预训练，得到pt_lora；2. 将pt_lora和完整版Chinese-Alpaca-2-7B合并，得到预训练之后的全量模型；3. 基于完整版Chinese-Alpaca-2-7B模型和1同时开始做的SFT训练，得到sft_lora；4. 将2得到的合并模型和3得到的sft_lora再次合并。
```
这里描述的是一种方法的pipeline还是多个方法？指代关系有点乱，看不太明白。另外建议给你训练得出的模型起个临时的名字，方便指代。

----

作为一般的建议，
1. 你这么做不可能不丢失Alpaca-2-7B的通用能力，因为你在二次pretrain的时候必然会产生mismatch。
2. 关于怎么训练能不丢失，这个并没有一个成熟的pipeline供参考。
3. 你可以考虑将预训练数据以适当形式转为SFT数据进行训练。
