### ISSUE TITLE
用A40训练一个指令精调，大概要运行多长时间

### ISSUE THREAD

**Issue by czhcc** [ymcui/Chinese-LLaMA-Alpaca-2#147]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

我用A40运行example中的指令精调脚本，使用的数据是Chinese-LLaMA-Alpaca中data目录里的json文件，想做个测试。现在运行了两天还没结束，这是正常的吗？如何通过日志判断训练是正常运行的？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
那你贴一下日志。

**Comment by czhcc** [comment]
![无标题](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/4754730/23d74960-27c8-45ce-ad01-f6df0be918cc)
上传一个截图吧

**Comment by czhcc** [comment]
差不多快5天，结束了

**Comment by xxllp** [comment]
一个数据集五天还是有些慢啊
