### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by TJSL0715** [ymcui/Chinese-LLaMA-Alpaca-2#149]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

还有必要继续在Chinese-Alpaca-2-13B上进行sft吗？
还是说用Chinese-llama-2-13B进行sft比较好？
另外就是进行sft的时候是否支持8bit量化？
谢谢

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
根据你自己的sft数据情况，如果数据量比较充足，可以在Chinese-LLaMA-2-13B上进行sft。
但最后还是以实验效果为准， 你可以两种方式都尝试然后进行比较。

可以进行8bit量化训练，但训练代码还未更新，需要参照相关代码自行修改。

**Comment by TJSL0715** [comment]
谢谢解答
