### ISSUE TITLE
Can you first expose the training scripts, PT scripts and sft scripts, and synthesis scripts?

### ISSUE THREAD

**Issue by musellama** [ymcui/Chinese-LLaMA-Alpaca-2#15]
Can you first expose the training scripts, PT scripts and sft scripts, and synthesis scripts?

**Comment by ymcui** [comment]
You can refer to our first-gen script first, as Llama-2 7B/13B do not use GQA, which makes them compatible with their firsr-gen. We will indeed release our code in a future time, but we are now occupied.

**Comment by musellama** [comment]
@ymcui 
Thank you for your reply
I tried the first generation of scripts, it seems that it can be trained, but I don't know why the trained LoRa merges with the llama2-HF model and makes an error, but it can be merged with the ALPACA model, that is, the final reasoning will be garbled

**Comment by musellama** [comment]
@ymcui  你好在你所知道的范围内，有没有一款 微型模型的训练，并且可以进行组合的。多个模型组合成一个专家模型的
