### ISSUE TITLE
关于改词表后的embedding适配

### ISSUE THREAD

**Issue by nuoma** [ymcui/Chinese-LLaMA-Alpaca-2#153]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

其他问题

### 基础模型

None

### 操作系统

None

### 详细描述问题

您好，我已经阅读了您的wiki。

假设我根据自己的领域，继续扩充词表，Emedding该怎么适配我一直没搞懂（计算资源够）。直到最近我才意识到，在进行merge和resize了以后，是不是可以通过lora，把target modules设置为wte和lm_head去做。这么做是对的吗？谢谢！

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
没太看明白，wte是什么？

**Comment by nuoma** [comment]
> 没太看明白，wte是什么？

使用的是gpt-j的网络结构：
GPTJForCausalLM(
  (transformer): GPTJModel(
    (wte): Embedding(50400, 4096)
    (drop): Dropout(p=0.0, inplace=False)
    (h): ModuleList(
      (0-27): 28 x GPTJBlock(
        (ln_1): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attn): GPTJAttention(
          (attn_dropout): Dropout(p=0.0, inplace=False)
          (resid_dropout): Dropout(p=0.0, inplace=False)
          (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (out_proj): Linear(in_features=4096, out_features=4096, bias=False)
        )
        (mlp): GPTJMLP(
          (fc_in): Linear(in_features=4096, out_features=16384, bias=True)
          (fc_out): Linear(in_features=16384, out_features=4096, bias=True)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.0, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=4096, out_features=50400, bias=True)
)

**Comment by airaria** [comment]
> 把target modules设置为wte和lm_head去做。

那就是训练embedding和lm_head。如果你的模型的中文embedding部分是新初始化的，确实应该这样训练。

**Comment by YoLo-MUC** [comment]
> > 把target modules设置为wte和lm_head去做。
> 
> 那就是训练embedding和lm_head。如果你的模型的中文embedding部分是新初始化的，确实应该这样训练。

请问对扩充的token进行向量初始化的时候，选用什么方法呢？是随机扩充还是均值扩充还是其他？谢谢！
