### ISSUE TITLE
指令精调后的sft_lora_model目录，是要进行合并吗？

### ISSUE THREAD

**Issue by czhcc** [ymcui/Chinese-LLaMA-Alpaca-2#155]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

我已经通过指令精调脚本生成sft_lora_model目录，
指令精调使用的模型是chinese-alpaca-2-7b，精调完成后，还需要合并吗？
如果合并，是与chinese-alpaca-2-7b合并，还是与Llama-2-7b-chat-hf合并？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
1. Chinese-Alpaca-2模型与Llama-2-7b-chat-hf无关，没有依赖关系。
2. 建议你贴一下SFT的运行命令，主要是要看基模型和LoRA相关参数。

**Comment by czhcc** [comment]
用的是run_sft.sh脚本，pretrained_model和chinese_tokenizer_path指向的是chinese-alpaca-2-7b目录，按说明，没使用peft_path，dataset_dir指向一个json文件所在的目录，其它的参数没改

**Comment by czhcc** [comment]
或者能详细说一下，
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh
这个文档中，最后那句：
“训练后的LoRA权重和配置存放${output_dir}/sft_lora_model，可用于后续的合并流程。”
中“合并流程”是指与哪个模型合并？基于Chinese-Alpaca-2训练的话还要不要合并？

**Comment by czhcc** [comment]
把sft_lora_model目录与chinese-alpaca-2-7b合并后可以了

**Comment by dengxiang1995** [comment]
> 把sft_lora_model目录与chinese-alpaca-2-7b合并后可以了



> 把sft_lora_model目录与chinese-alpaca-2-7b合并后可以了
兄弟合并完后，回答的效果有试过吗，我合并完和合并前回答的一模一样的
