### ISSUE TITLE
合并模型疑惑

### ISSUE THREAD

**Issue by tangxuemei1995** [ymcui/Chinese-LLaMA-Alpaca-2#156]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型转换和合并

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

```
python merge_llama2_with_chinese_lora_low_mem.py \
    --base_model ziqingyang/chinese-alpaca-2-7b \
    --lora_model ziqingyang/chinese-alpaca-2-lora-7b \
    --output_type huggingface \
    --output_dir alpaca-combined
```
1. 请问这里合并模型
ziqingyang/chinese-alpaca-2-7b对应ziqingyang/chinese-alpaca-2-lora-7b
ziqingyang/chinese-llama-2-7b对应ziqingyang/chinese-llama-2-lora-7b
看readme是这样写的，是这样吗？

但是给的Google colab 中ziqingyang/chinese-llama-2-lora-7b和meta-llama/Llama-2-7b-hf合并

所以有点疑惑，base 模型应该怎么选？

2. 假设合并之后的模型为M，我在合并之后的模型M上精调之后的lora模型是N，最后是把M和N合并再测试对吗？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
1. `ziqingyang/chinese-llama-2-7b`已经是完整模型了，不需要合并。如果你要自己合并就要用对应的LoRA和原版Llama-2-hf合并。比如你提到的colab里，为了合成完整的Chinese-LLaMA-2-7B，就需要传入ziqingyang/chinese-llama-2-lora-7b（LoRA）和meta-llama/Llama-2-7b-hf（基模型）
2. 是

**Comment by hikrr** [comment]
@ymcui

您好，對於模型的運行有一些疑惑想要請教您。

在 readme 中有提到：

```
完整模型下载
以下是完整版模型，直接下载即可使用，无需其他合并步骤。推荐网络带宽充足的用户。
```

如果是用 huggingface 的方式下載權重 (clone repo) ，在本地會有兩個檔案：
`pytorch_model-00001-of-00002.bin` 和 `pytorch_model-00002-of-00002.bin`

如果要使用 llama.cpp 來進行 inference 的話，是否需要自行 merge 此兩檔案，再轉換成 ggml 的格式。
有這個困惑的原因是因為 script/ 中 merge 的腳本 `merge_llama2_with_chinese_lora_low_mem.py` 需要提供 `--lora_model`，但是我並暫時沒有想要加 lora_model ，所以這個 script 似乎並沒有辦法 merge 上述兩檔案

謝謝您為社群的貢獻~

**Comment by ymcui** [comment]
@hikrr 合并模型特指的是LoRA和基模型（原版Llama-2-hf）的合并。
```
完整模型  = 合并脚本(基模型 + LoRA模型)
```
你下载的`pytorch_model-00001-of-00002.bin`和`pytorch_model-00002-of-00002.bin`已经是合并完成的模型了。不需要再通过`merge_llama2_with_chinese_lora_low_mem.py`脚本合并了。
在llama.cpp里直接通过`python convert.py pytorch_model模型存放路径`就可以把`.bin`文件转换为GGML格式了。

**Comment by hikrr** [comment]
@ymcui 謝謝您的回答！

**Comment by ibmxiang** [comment]
想请问一下 用完整模型微调之后，合并模型是怎么处理喃。用sft_lora_model的模型与完整模型chinese-alpaca-2-7b进行合并？

**Comment by ymcui** [comment]
@ibmxiang 你精调时候用的基模型是什么就和什么合并。

**Comment by Intermatrix** [comment]
> @ibmxiang 你精调时候用的基模型是什么就和什么合并。

你好！我精调的时候使用的基模型是chinese-alpaca-2-7b，将之与微调后得到的sft_lora_model进行了合并。而后对合并得到的全量模型权重进行convert.py时显示如下报错：Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00001-of-00002.bin
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00001-of-00002.bin
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00002-of-00002.bin
params = Params(n_vocab=55296, n_embd=4096, n_mult=5504, n_layer=32, n_ctx=4096, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-05, f_rope_freq_base=None, f_rope_scale=None, ftype=None, path_model=PosixPath('/root/model/llama.cpp/zh-models/7B/sft_v0_combine'))
Loading vocab file '/root/model/llama.cpp/zh-models/7B/sft_v0_combine/tokenizer.model', type 'spm'
Permuting layer 0
Permuting layer 1
Permuting layer 2
Permuting layer 3
Permuting layer 4
Permuting layer 5
Permuting layer 6
Permuting layer 7
Permuting layer 8
Permuting layer 9
Permuting layer 10
Permuting layer 11
Permuting layer 12
Permuting layer 13
Permuting layer 14
Permuting layer 15
Permuting layer 16
Permuting layer 17
Permuting layer 18
Permuting layer 19
Permuting layer 20
Permuting layer 21
Permuting layer 22
Permuting layer 23
Permuting layer 24
Permuting layer 25
Permuting layer 26
Permuting layer 27
Permuting layer 28
Permuting layer 29
Permuting layer 30
Permuting layer 31
Traceback (most recent call last):
  File "/root/model/llama.cpp/convert.py", line 1173, in <module>
    main()
  File "/root/model/llama.cpp/convert.py", line 1160, in main
    model   = convert_model_names(model, params)
  File "/root/model/llama.cpp/convert.py", line 975, in convert_model_names
    if gguf.should_skip_tensor_TMP(ARCH, params.n_layer, name_new):
AttributeError: module 'gguf' has no attribute 'should_skip_tensor_TMP'请问是什么情况呀？

**Comment by Intermatrix** [comment]
> @ibmxiang 你精调时候用的基模型是什么就和什么合并。

@ymcui 您好！我精调的时候使用的基模型是chinese-alpaca-2-7b，将之与微调后得到的sft_lora_model进行了合并。而后对合并得到的全量模型权重进行convert.py时显示如下报错：Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00001-of-00002.bin
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00001-of-00002.bin
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00002-of-00002.bin
params = Params(n_vocab=55296, n_embd=4096, n_mult=5504, n_layer=32, n_ctx=4096, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-05, f_rope_freq_base=None, f_rope_scale=None, ftype=None, path_model=PosixPath('/root/model/llama.cpp/zh-models/7B/sft_v0_combine'))
Loading vocab file '/root/model/llama.cpp/zh-models/7B/sft_v0_combine/tokenizer.model', type 'spm'
Permuting layer 0
Permuting layer 1
Permuting layer 2
Permuting layer 3
Permuting layer 4
Permuting layer 5
Permuting layer 6
Permuting layer 7
Permuting layer 8
Permuting layer 9
Permuting layer 10
Permuting layer 11
Permuting layer 12
Permuting layer 13
Permuting layer 14
Permuting layer 15
Permuting layer 16
Permuting layer 17
Permuting layer 18
Permuting layer 19
Permuting layer 20
Permuting layer 21
Permuting layer 22
Permuting layer 23
Permuting layer 24
Permuting layer 25
Permuting layer 26
Permuting layer 27
Permuting layer 28
Permuting layer 29
Permuting layer 30
Permuting layer 31
Traceback (most recent call last):
File "/root/model/llama.cpp/convert.py", line 1173, in
main()
File "/root/model/llama.cpp/convert.py", line 1160, in main
model = convert_model_names(model, params)
File "/root/model/llama.cpp/convert.py", line 975, in convert_model_names
if gguf.should_skip_tensor_TMP(ARCH, params.n_layer, name_new):
AttributeError: module 'gguf' has no attribute 'should_skip_tensor_TMP'请问是什么情况呀？
