### ISSUE TITLE
预训练之后推理问题

### ISSUE THREAD

**Issue by icowan** [ymcui/Chinese-LLaMA-Alpaca-2#158]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

训练完，并且合并完之的使用 `scripts/inference/inference_hf.py` 进行推理，但输出的内容去各种乱。

**预训练脚本**:

```
wandb disabled
lr=1e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

dir_date=$(date +%m%d)
train_version=v0.1

NUM_NODES=1
SEQ_LEN=2048
GC_SCALE=4
SKYPILOT_NUM_GPUS_PER_NODE=4
PER_DEVICE_BATCH_SIZE=64
GRADIENT_ACCUMULATION_STEPS=64

pretrained_model=/data/alpaca/chinese-llama-2-13b
chinese_tokenizer_path=/data/alpaca/chinese-alpaca-2-lora-13b
dataset_dir=/data/train-data/
# data cache 需要每次清理一下，否则加上之前的数据
data_cache=/data/cache/${dir_date}-${train_version}
rm -rf ${data_cache}*
per_device_train_batch_size=${PER_DEVICE_BATCH_SIZE}
per_device_eval_batch_size=${PER_DEVICE_BATCH_SIZE}
training_steps=1500
gradient_accumulation_steps=${GRADIENT_ACCUMULATION_STEPS}
output_dir=/data/output/pt-chinese-alpaca-2-13b-lora-${dir_date}-${train_version}
block_size=1024
max_seq_length=1024
deepspeed_config_file=ds_zero2_no_offload.json
run_clm_sft_with_peft=run_clm_pt_with_peft.py

torchrun --nnodes 1 --nproc_per_node ${SKYPILOT_NUM_GPUS_PER_NODE} ${run_clm_sft_with_peft} \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --peft_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --do_train \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs 10 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 500 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size ${block_size} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False \
    --flash_attn \
    --data_cache_dir ${data_cache}
```

推理脚本:

```
$ python scripts/inference/inference_hf.py \
  --base_model /data/output/merged-chinese-alpaca-2-13b-lora-0820-v0.2 \
  --with_prompt \
  --interactive
```

### 依赖情况（代码类问题务必提供）

```
peft                     0.3.0.dev0
torch                    2.0.1
transformers             4.31.0
```

### 运行日志或截图

<img width="1099" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/6229526/fe748ae8-0201-4fdc-b2e0-8aa825061036">

**Comment by ymcui** [comment]
因为你的参数指定的比较奇怪，
- `model_name_or_path`你指定的是Chinese-LLaMA-2-13B
- `peft_path`你指定的是Chinese-Alpaca-2-LoRA-13B

但问题是这两个合并之后并不是一个正确的模型。如果是要接着Alpaca-2-LoRA继续训练（不改变rank之类的情况下），`model_name_or_path`指定的应该原版Llama-2-13B-hf，因为原版Llama-2-13B-hf + Chinese-Alpaca-2-LoRA-13B = Chinese-Alpaca-2-13B。

建议你再仔细看一下wiki，尤其是里面的那个表格。
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh

**Comment by icowan** [comment]
> 因为你的参数指定的比较奇怪，
> 
> * `model_name_or_path`你指定的是Chinese-LLaMA-2-13B
> * `peft_path`你指定的是Chinese-Alpaca-2-LoRA-13B
> 
> 但问题是这两个合并之后并不是一个正确的模型。如果是要接着Alpaca-2-LoRA继续训练（不改变rank之类的情况下），`model_name_or_path`指定的应该原版Llama-2-13B-hf，因为原版Llama-2-13B-hf + Chinese-Alpaca-2-LoRA-13B = Chinese-Alpaca-2-13B。
> 
> 建议你再仔细看一下wiki，尤其是里面的那个表格。 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh

预训练应该不用指定 peft_path，我再核对一下 。

**Comment by ymcui** [comment]
看到你实际指定的脚本是pt脚本了。这种情况下你还是要排查一下[pt_wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)。
如果你只是继承llama权重做预训练，而不是指令精调的话，效果不好也正常，因为gradio_demo和inference脚本都是针对Alpaca-2（指令精调模型）做的。LLaMA模型只适合做文本续写。

总而言之，只做预训练的模型是不适合直接拿来做对话的。

**Comment by icowan** [comment]
> 看到你实际指定的脚本是pt脚本了。这种情况下你还是要排查一下[pt_wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)。 如果你只是继承llama权重做预训练，而不是指令精调的话，效果不好也正常，因为gradio_demo和inference脚本都是针对Alpaca-2（指令精调模型）做的。LLaMA模型只适合做文本续写。
> 
> 总而言之，只做预训练的模型是不适合直接拿来做对话的。

确实是加入了 peft_path 的问题，去掉之后 ，正常了一些。
其他的正在逐步尝试，感谢！🙏
