### ISSUE TITLE
指令精调后，运行合并脚本，似乎并没有执行合并

### ISSUE THREAD

**Issue by czhcc** [ymcui/Chinese-LLaMA-Alpaca-2#163]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型转换和合并

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

指令精调后，生成了sft_lora_model目录，然后运行
merge_llama2_with_chinese_lora_low_mem.py
base_model指向chinese-alpace-2-7b
lore_model指向sft_lore_model
但最后的输出目录里，bin文件还是chinese-alpace-2-7b里的文件，合并时也没有更多的输出

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

[2023-08-22 01:22:36,487] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
================================================================================
Base model: /home/trs/models/chinese-alpaca-2-7b
LoRA model: /home/trs/keras_test/src/Chinese-LLaMA-Alpaca-2-main/scripts/training/output_dir/sft_lora_model
Loading /home/trs/keras_test/src/Chinese-LLaMA-Alpaca-2-main/scripts/training/output_dir/sft_lora_model
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Loading ckpt pytorch_model-00001-of-00002.bin
Merging...
Saving ckpt pytorch_model-00001-of-00002.bin to /home/trs/models/czhmodel in HF format...
Loading ckpt pytorch_model-00002-of-00002.bin
Merging...
Saving ckpt pytorch_model-00002-of-00002.bin to /home/trs/models/czhmodel in HF format...
Saving tokenizer
Saving config.json
Saving generation_config.json
Saving pytorch_model.bin.index.json
Done.

**Comment by airaria** [comment]
ls你的合并后的目录看一下

> bin文件还是chinese-alpace-2-7b里的文件

你确定合并前后是同一个文件吗？合并后的文件名不变的。

**Comment by airaria** [comment]
> 合并后的目录

合并后的目录内容没有问题。

**Comment by czhcc** [comment]
多谢
