### ISSUE TITLE
多轮对话微调数据如何构造

### ISSUE THREAD

**Issue by aaronliu7** [ymcui/Chinese-LLaMA-Alpaca-2#167]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
基于基座模型进行数据微调，多轮对话的数据怎么构造成Stanford Alpaca格式？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
如果你基于基座模型进行指令微调，那么多轮对话的格式你用任何一种都可以，当然推理时要适配。

在Chinese-alpaca-2中，我们不再使用Stanford Alpaca格式，而是使用llama-2官方给的格式，可以参考：
https://github.com/facebookresearch/llama/blob/main/llama/generation.py

**Comment by ymcui** [comment]
Stanford Alpaca格式指的是训练数据的文件格式（如wiki中提供的JSON示例），和模型的指令模板不是一个概念。
训练脚本读取这个JSON文件之后会提取对应的字段，然后套用对应的指令模板，这个才是最后要送到模型的输入。

**Comment by airaria** [comment]
> 但是在readme的[指令精调脚本Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)中，要求的数据格式还是Stanford Alpaca格式，是没有更新吗？利用这个脚本进行指令微调的话，多轮对话数据如何构造呢？

多谢指出，我们会进行更正。

多轮对话的数据需要自己拼接，拼接的方式可以参考：
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/fa58621fac9fff72870ef8ef93777fe1ae95e99a/scripts/inference/gradio_demo.py#L360-L376

history 是一个列表，每一个元素是一个(input, output)的tuple

**Comment by aaronliu7** [comment]
> Stanford Alpaca格式指的是训练数据的文件格式（如wiki中提供的JSON示例），和模型的指令模板不是一个概念。 训练脚本读取这个JSON文件之后会提取对应的字段，然后套用对应的指令模板，这个才是最后要送到模型的输入。

不好意思，我可能问题没有描述清楚，我没有提问指令模板的问题，就是指令精调的训练数据，wiki要求的是Stanford Alpaca格式，JSON示例中的都是单轮的，是否可以构造多轮对话的语料，如何构造？

**Comment by airaria** [comment]
> 不好意思，我可能问题没有描述清楚，我没有提问指令模板的问题，就是指令精调的训练数据，wiki要求的是Stanford Alpaca格式，JSON示例中的都是单轮的，是否可以构造多轮对话的语料，如何构造？

> 但是在readme的[指令精调脚本Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)中，要求的数据格式还是Stanford Alpaca格式，是没有更新吗？利用这个脚本进行指令微调的话，多轮对话数据如何构造呢？

多轮对话的数据需要自己将多轮对话拼接成完整的input和output，拼接的方式可以参考：
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/fa58621fac9fff72870ef8ef93777fe1ae95e99a/scripts/inference/gradio_demo.py#L360-L376

history 是一个列表，每一个元素是一个(input, response)的tuple

**Comment by aaronliu7** [comment]
> > 不好意思，我可能问题没有描述清楚，我没有提问指令模板的问题，就是指令精调的训练数据，wiki要求的是Stanford Alpaca格式，JSON示例中的都是单轮的，是否可以构造多轮对话的语料，如何构造？
> 
> > 但是在readme的[指令精调脚本Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)中，要求的数据格式还是Stanford Alpaca格式，是没有更新吗？利用这个脚本进行指令微调的话，多轮对话数据如何构造呢？
> 
> 多轮对话数据需要自己拼接成完整的input和output，拼接的方式可以参考：
> 
> https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/fa58621fac9fff72870ef8ef93777fe1ae95e99a/scripts/inference/gradio_demo.py#L360-L376
> 
> history 是一个列表，每一个元素是一个(input, response)的tuple

好的，谢谢

**Comment by minmie** [comment]
> > 不好意思，我可能问题没有描述清楚，我没有提问指令模板的问题，就是指令精调的训练数据，wiki要求的是Stanford Alpaca格式，JSON示例中的都是单轮的，是否可以构造多轮对话的语料，如何构造？
> 
> > 但是在readme的[指令精调脚本Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh)中，要求的数据格式还是Stanford Alpaca格式，是没有更新吗？利用这个脚本进行指令微调的话，多轮对话数据如何构造呢？
> 
> 多轮对话数据需要自己拼接成完整的input和output，拼接的方式可以参考：
> 
> https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/fa58621fac9fff72870ef8ef93777fe1ae95e99a/scripts/inference/gradio_demo.py#L360-L376
> 
> history 是一个列表，每一个元素是一个(input, response)的tuple

你好，本项目说“在Chinese-LLaMA-2的基础上，利用有标注指令数据进行进一步精调，得到Chinese-Alpaca-2系列模型”
于是我看了一下sft的源码，发现构造的数据都是单轮对话prompt，如下图：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/8a97acc8-f3cf-49e9-9b50-1f4922ceea66)

但是项目里说，这样训练好后的Chinese-Alpaca-2却支持多轮对话，并且推理的时候使用的是如下prompt:
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/ea7c1f71-32d0-4d0b-a96e-a571ffd24ee5)

我有几个问题：
1. 训练的时候使用的单轮对话数据，推理的时候也能支持多轮对话？
2. 训练的时候都是单轮对话的prompt，推理的时候直接使用多轮对话prompt，模型也能理解吗？（多轮对话的prompt模型从没见过）

**Comment by changyuying** [comment]
> 如果你基于基座模型进行指令微调，那么多轮对话的格式你用任何一种都可以，当然推理时要适配。
> 
> 在Chinese-alpaca-2中，我们不再使用Stanford Alpaca格式，而是使用llama-2官方给的格式，可以参考： https://github.com/facebookresearch/llama/blob/main/llama/generation.py

您好，如果是基于指令模型继续做全量微调的话（比如基于Chinese-alpaca-2），prompt的格式是要和alpaca的一致才能发挥出更好的性能嘛

**Comment by SHX9610** [comment]
@minmie 您好！ 您说得这两个问题我同样很疑惑，您那边有过实验或结论吗？ 

1）训练的时候使用的单轮对话数据，推理的时候也能支持多轮对话？
2）训练的时候都是单轮对话的prompt，推理的时候直接使用多轮对话prompt，模型也能理解吗？（多轮对话的prompt模型从没见过）

**Comment by minmie** [comment]
> @minmie 您好！ 您说得这两个问题我同样很疑惑，您那边有过实验或结论吗？
> 
> 1）训练的时候使用的单轮对话数据，推理的时候也能支持多轮对话？ 2）训练的时候都是单轮对话的prompt，推理的时候直接使用多轮对话prompt，模型也能理解吗？（多轮对话的prompt模型从没见过）

没有深入去探究了
