### ISSUE TITLE
请问是否支持流式回复？

### ISSUE THREAD

**Issue by jessicawu11** [ymcui/Chinese-LLaMA-Alpaca-2#168]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

请问是否支持流式回复？支持的话麻烦告知一下使用方法，谢谢！

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
大多数都支持，你自己看一下对应的文档（模型量化、推理、部署）吧：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki

**Comment by jessicawu11** [comment]
我现在用的是langchain的推理，答案都是完整直接出来的，不是流式

**Comment by ymcui** [comment]
这属于第三方库的问题，建议你去LangChain那边找一下文档，看看是否支持。
