### ISSUE TITLE
alpaca模型加载出错

### ISSUE THREAD

**Issue by long568** [ymcui/Chinese-LLaMA-Alpaca-2#169]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型量化和部署

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

更新llama.cpp到最新后，alpaca模型加载出错，llama模型正常。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
llama_model_load_internal: format       = GGUF V1 (latest)
llama_model_load_internal: arch         = llama
llama_model_load_internal: vocab type   = SPM
llama_model_load_internal: n_vocab      = 55296
llama_model_load_internal: n_ctx_train  = 4096
llama_model_load_internal: n_ctx        = 512
llama_model_load_internal: n_embd       = 4096
llama_model_load_internal: n_head       = 32
llama_model_load_internal: n_head_kv    = 32
llama_model_load_internal: n_layer      = 32
llama_model_load_internal: n_rot        = 128
llama_model_load_internal: n_gqa        = 1
llama_model_load_internal: f_norm_eps   = 1.0e-05
llama_model_load_internal: n_ff         = 11008
llama_model_load_internal: freq_base    = 10000.0
llama_model_load_internal: freq_scale   = 1
llama_model_load_internal: model type   = 7B
llama_model_load_internal: model ftype  = mostly Q4_0
llama_model_load_internal: model size   = 5.08 B
llama_model_load_internal: general.name = LLaMA
llama_model_load_internal: BOS token = 1 '<s>'
llama_model_load_internal: EOS token = 2 '</s>'
llama_model_load_internal: LF token  = 13 '<0x0A>'
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: using CUDA for GPU acceleration
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3090) as main device
error loading model: create_tensor: tensor 'output_norm.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'chinese-alpaca-2-7b-hf.gguf'
main: error: unable to load model
```

**Comment by ymcui** [comment]
贴一下转换模型的命令？

**Comment by long568** [comment]
参照的llama官方的
先安装依赖
python3 -m pip install -r requirements.txt
再做转换，在模型路径下
python convert.py .
quantize ggml-model-f16.gguf chinese-alpaca-2-7b-hf.gguf q4_0
加载模型:
main -m chinese-alpaca-2-7b-hf.gguf -n 128 -ngl 40

**Comment by ymcui** [comment]
1. 拉取最新llama.cpp之后是否执行了`make clean`？先clean之后再编译，生成新的二进制文件。然后再执行`convert.py`和`quantize`。
2. 你的llama.cpp的log里有异常：
```
llama_model_load_internal: model size   = 5.08 B
```
7B模型应该输出6.93B，所以怀疑你原始hf模型可能不完整。建议你再仔细排查一下源文件是否完整。

**Comment by long568** [comment]
好的，
1. 执行了make clean的
2. 模型一直放在移动硬盘里的，之前在另一台机器上用过。但是，我记得之前生成的模型是大于3G的，这次不到3G，比较奇怪。

**Comment by long568** [comment]
又试了下 
chinese-llama-2-7b-hf
llama_model_load_internal: model size   = 6.93 B
chinese-alpaca-2-7b-hf
llama_model_load_internal: model size   = 5.08 B
好像确实有问题～～

**Comment by lucifer222** [comment]
> 

@long568 
请教下 上面的问题解决了吗？ 我也遇到了相同的问题。 模型大小为5.08. 使用时报错
error loading model: create_tensor: tensor 'output_norm.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model 'chinese-alpaca-2-7b/ggml-model-q4_0.gguf'
main: error: unable to load model

**Comment by Tr-buaa** [comment]
@long568 hello，请问上面的问题解决了吗？我也遇到了相同的问题，
error loading model: create_tensor: tensor 'output_norm.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model './models/chinese-llama-2-7b-hf/ggml-model-q4_0.gguf'
main: error: unable to load model
是因为模型下载的时候就有问题吗？

**Comment by qingfengfenga** [comment]
最新的`llama.cpp`代码中遇到了相同的问题，执行`make clean`，重新编译后依然无法解决，参数略有不同

主要参数
```
llm_load_print_meta: model params   = 5.08 B
llm_load_print_meta: model size     = 2.66 GiB (4.50 BPW)
```


```
llama_model_loader: - kv   0:                       general.architecture str
llama_model_loader: - kv   1:                               general.name str
llama_model_loader: - kv   2:                       llama.context_length u32
llama_model_loader: - kv   3:                     llama.embedding_length u32
llama_model_loader: - kv   4:                          llama.block_count u32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32
llama_model_loader: - kv   7:                 llama.attention.head_count u32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32
llama_model_loader: - kv  10:                          general.file_type u32
llama_model_loader: - kv  11:                       tokenizer.ggml.model str
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32
llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32
llama_model_loader: - kv  18:               general.quantization_version u32
llama_model_loader: - type  f32:   48 tensors
llama_model_loader: - type q4_0:  169 tensors
llm_load_print_meta: format         = GGUF V2 (latest)
llm_load_print_meta: arch           = llama
llm_load_print_meta: vocab type     = SPM
llm_load_print_meta: n_vocab        = 55296
llm_load_print_meta: n_merges       = 0
llm_load_print_meta: n_ctx_train    = 4096
llm_load_print_meta: n_ctx          = 512
llm_load_print_meta: n_embd         = 4096
llm_load_print_meta: n_head         = 32
llm_load_print_meta: n_head_kv      = 32
llm_load_print_meta: n_layer        = 32
llm_load_print_meta: n_rot          = 128
llm_load_print_meta: n_gqa          = 1
llm_load_print_meta: f_norm_eps     = 0.0e+00
llm_load_print_meta: f_norm_rms_eps = 1.0e-05
llm_load_print_meta: n_ff           = 11008
llm_load_print_meta: freq_base      = 10000.0
llm_load_print_meta: freq_scale     = 1
llm_load_print_meta: model type     = 7B
llm_load_print_meta: model ftype    = mostly Q4_0
llm_load_print_meta: model params   = 5.08 B
llm_load_print_meta: model size     = 2.66 GiB (4.50 BPW)
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.07 MB
error loading model: create_tensor: tensor 'output_norm.weight' not found
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '/models/ggml-model-q4_0.gguf'
main: error: unable to load model
```

**Comment by Tr-buaa** [comment]
> 最新的`llama.cpp`代码中遇到了相同的问题，执行`make clean`，重新编译后依然无法解决，参数略有不同
> 
> 主要参数
> 
> ```
> llm_load_print_meta: model params   = 5.08 B
> llm_load_print_meta: model size     = 2.66 GiB (4.50 BPW)
> ```
> 
> ```
> llama_model_loader: - kv   0:                       general.architecture str
> llama_model_loader: - kv   1:                               general.name str
> llama_model_loader: - kv   2:                       llama.context_length u32
> llama_model_loader: - kv   3:                     llama.embedding_length u32
> llama_model_loader: - kv   4:                          llama.block_count u32
> llama_model_loader: - kv   5:                  llama.feed_forward_length u32
> llama_model_loader: - kv   6:                 llama.rope.dimension_count u32
> llama_model_loader: - kv   7:                 llama.attention.head_count u32
> llama_model_loader: - kv   8:              llama.attention.head_count_kv u32
> llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32
> llama_model_loader: - kv  10:                          general.file_type u32
> llama_model_loader: - kv  11:                       tokenizer.ggml.model str
> llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr
> llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr
> llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr
> llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32
> llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32
> llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32
> llama_model_loader: - kv  18:               general.quantization_version u32
> llama_model_loader: - type  f32:   48 tensors
> llama_model_loader: - type q4_0:  169 tensors
> llm_load_print_meta: format         = GGUF V2 (latest)
> llm_load_print_meta: arch           = llama
> llm_load_print_meta: vocab type     = SPM
> llm_load_print_meta: n_vocab        = 55296
> llm_load_print_meta: n_merges       = 0
> llm_load_print_meta: n_ctx_train    = 4096
> llm_load_print_meta: n_ctx          = 512
> llm_load_print_meta: n_embd         = 4096
> llm_load_print_meta: n_head         = 32
> llm_load_print_meta: n_head_kv      = 32
> llm_load_print_meta: n_layer        = 32
> llm_load_print_meta: n_rot          = 128
> llm_load_print_meta: n_gqa          = 1
> llm_load_print_meta: f_norm_eps     = 0.0e+00
> llm_load_print_meta: f_norm_rms_eps = 1.0e-05
> llm_load_print_meta: n_ff           = 11008
> llm_load_print_meta: freq_base      = 10000.0
> llm_load_print_meta: freq_scale     = 1
> llm_load_print_meta: model type     = 7B
> llm_load_print_meta: model ftype    = mostly Q4_0
> llm_load_print_meta: model params   = 5.08 B
> llm_load_print_meta: model size     = 2.66 GiB (4.50 BPW)
> llm_load_print_meta: general.name   = LLaMA v2
> llm_load_print_meta: BOS token = 1 '<s>'
> llm_load_print_meta: EOS token = 2 '</s>'
> llm_load_print_meta: UNK token = 0 '<unk>'
> llm_load_print_meta: PAD token = 0 '<unk>'
> llm_load_print_meta: LF token  = 13 '<0x0A>'
> llm_load_tensors: ggml ctx size =    0.07 MB
> error loading model: create_tensor: tensor 'output_norm.weight' not found
> llama_load_model_from_file: failed to load model
> llama_init_from_gpt_params: error: failed to load model '/models/ggml-model-q4_0.gguf'
> main: error: unable to load model
> ```

可以检查一下SHA256.md中的文件名字与原model中实际的文件名字是否相同，我之前也遇到了这个问题，最后发现是“pytorch_model-00002-of-00002.bin”的名字没有对应导致第二个模型文件没有load进去，导致总参数只有5.08B。修改名字统一后成功运行。

**Comment by qingfengfenga** [comment]
> > 最新的`llama.cpp`代码中遇到了相同的问题，执行`make clean`，重新编译后依然无法解决，参数略有不同
> > 主要参数
> > ```
> > llm_load_print_meta: model params   = 5.08 B
> > llm_load_print_meta: model size     = 2.66 GiB (4.50 BPW)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > llama_model_loader: - kv   0:                       general.architecture str
> > llama_model_loader: - kv   1:                               general.name str
> > llama_model_loader: - kv   2:                       llama.context_length u32
> > llama_model_loader: - kv   3:                     llama.embedding_length u32
> > llama_model_loader: - kv   4:                          llama.block_count u32
> > llama_model_loader: - kv   5:                  llama.feed_forward_length u32
> > llama_model_loader: - kv   6:                 llama.rope.dimension_count u32
> > llama_model_loader: - kv   7:                 llama.attention.head_count u32
> > llama_model_loader: - kv   8:              llama.attention.head_count_kv u32
> > llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32
> > llama_model_loader: - kv  10:                          general.file_type u32
> > llama_model_loader: - kv  11:                       tokenizer.ggml.model str
> > llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr
> > llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr
> > llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr
> > llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32
> > llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32
> > llama_model_loader: - kv  17:            tokenizer.ggml.padding_token_id u32
> > llama_model_loader: - kv  18:               general.quantization_version u32
> > llama_model_loader: - type  f32:   48 tensors
> > llama_model_loader: - type q4_0:  169 tensors
> > llm_load_print_meta: format         = GGUF V2 (latest)
> > llm_load_print_meta: arch           = llama
> > llm_load_print_meta: vocab type     = SPM
> > llm_load_print_meta: n_vocab        = 55296
> > llm_load_print_meta: n_merges       = 0
> > llm_load_print_meta: n_ctx_train    = 4096
> > llm_load_print_meta: n_ctx          = 512
> > llm_load_print_meta: n_embd         = 4096
> > llm_load_print_meta: n_head         = 32
> > llm_load_print_meta: n_head_kv      = 32
> > llm_load_print_meta: n_layer        = 32
> > llm_load_print_meta: n_rot          = 128
> > llm_load_print_meta: n_gqa          = 1
> > llm_load_print_meta: f_norm_eps     = 0.0e+00
> > llm_load_print_meta: f_norm_rms_eps = 1.0e-05
> > llm_load_print_meta: n_ff           = 11008
> > llm_load_print_meta: freq_base      = 10000.0
> > llm_load_print_meta: freq_scale     = 1
> > llm_load_print_meta: model type     = 7B
> > llm_load_print_meta: model ftype    = mostly Q4_0
> > llm_load_print_meta: model params   = 5.08 B
> > llm_load_print_meta: model size     = 2.66 GiB (4.50 BPW)
> > llm_load_print_meta: general.name   = LLaMA v2
> > llm_load_print_meta: BOS token = 1 '<s>'
> > llm_load_print_meta: EOS token = 2 '</s>'
> > llm_load_print_meta: UNK token = 0 '<unk>'
> > llm_load_print_meta: PAD token = 0 '<unk>'
> > llm_load_print_meta: LF token  = 13 '<0x0A>'
> > llm_load_tensors: ggml ctx size =    0.07 MB
> > error loading model: create_tensor: tensor 'output_norm.weight' not found
> > llama_load_model_from_file: failed to load model
> > llama_init_from_gpt_params: error: failed to load model '/models/ggml-model-q4_0.gguf'
> > main: error: unable to load model
> > ```
> 
> 可以检查一下SHA256.md中的文件名字与原model中实际的文件名字是否相同，我之前也遇到了这个问题，最后发现是“pytorch_model-00002-of-00002.bin”的名字没有对应导致第二个模型文件没有load进去，导致总参数只有5.08B。修改名字统一后成功运行。

确实是模型名字的问题，模型从`google drive`下载下来之后，第二个模型文件，从 `pytorch_model-00002-of-00002-002.bin` 变成了`pytorch_model-00002-of-00002-001.bin`，导致没加载上，修改之后参数正确了，也可以加载了。

**Comment by hillwater** [comment]
我也碰到了一样的问题，的确是google drive下载文件的问题，它会自动重命名，把 **`pytorch_model-00001-of-00002.bin`** 重命名为`**pytorch_model-00001-of-00002-001.bin**`，另一个`**pytorch_model-00002-of-00002.bin**`也有被重命名
