### ISSUE TITLE
C-Eval测试结果和您公开数据差距比较大，请问是否方便公开具体测试的参数？

### ISSUE THREAD

**Issue by X-Buring** [ymcui/Chinese-LLaMA-Alpaca-2#170]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

效果问题

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

您好，我最近想用C-Eval对自己继续训练的模型测试评分，下载后就先用您的Chinese-Llama系列模型先测试。测试过程中发现，我测试时候没法复现您在Chinese-LLaMA-2-13B，以及Chinese-LLaMA-Plus-33B上约40%的准确率，未经过sft的模型不太能很好地回答问题，Valid集上的准确率超不过30%。
我是下载的最新的Chinese-Llama-2项目的代码进行的测试，运行时候的命令如下（相关路径我隐去了，应该没啥相关的），请问是不是哪些参数跟您测试时候不太一样？您方便是否方便公开具体测试的参数？

```
python eval.py \
    --model_path ${model_path} \
    --cot False \
    --few_shot True \
    --with_prompt True \
    --constrained_decoding False \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv True \
    --do_test False \
    --output_dir ${output_path} 
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
{
  "accountant": {
    "score": 20.408163265306122,
    "num": 49,
    "correct": 10.0
  },
  "art_studies": {
    "score": 21.21212121212121,
    "num": 33,
    "correct": 7.0
  },
  "advanced_mathematics": {
    "score": 21.05263157894737,
    "num": 19,
    "correct": 4.0
  },
  "basic_medicine": {
    "score": 21.05263157894737,
    "num": 19,
    "correct": 4.0
  },
  "business_administration": {
    "score": 27.272727272727273,
    "num": 33,
    "correct": 9.0
  },
  "chinese_language_and_literature": {
    "score": 17.391304347826086,
    "num": 23,
    "correct": 4.0
  },
  "civil_servant": {
    "score": 25.53191489361702,
    "num": 47,
    "correct": 12.0
  },
  "clinical_medicine": {
    "score": 40.90909090909091,
    "num": 22,
    "correct": 9.0
  },
  "college_chemistry": {
    "score": 25.0,
    "num": 24,
    "correct": 6.0
  },
  "college_physics": {
    "score": 26.31578947368421,
    "num": 19,
    "correct": 4.999999999999999
  },
  "college_programming": {
    "score": 29.72972972972973,
    "num": 37,
    "correct": 11.0
  },
  "computer_architecture": {
    "score": 9.523809523809524,
    "num": 21,
    "correct": 2.0
  },
  "computer_network": {
    "score": 15.789473684210526,
    "num": 19,
    "correct": 3.0
  },
  "discrete_mathematics": {
    "score": 31.25,
    "num": 16,
    "correct": 5.0
  },
  "education_science": {
    "score": 27.586206896551722,
    "num": 29,
    "correct": 8.0
  },
  "electrical_engineer": {
    "score": 27.027027027027028,
    "num": 37,
    "correct": 10.0
  },
  "environmental_impact_assessment_engineer": {
    "score": 22.580645161290324,
    "num": 31,
    "correct": 7.0
  },
  "fire_engineer": {
    "score": 25.806451612903224,
    "num": 31,
    "correct": 8.0
  },
  "high_school_biology": {
    "score": 26.31578947368421,
    "num": 19,
    "correct": 4.999999999999999
  },
  "high_school_chemistry": {
    "score": 5.2631578947368425,
    "num": 19,
    "correct": 1.0
  },
  "high_school_chinese": {
    "score": 21.05263157894737,
    "num": 19,
    "correct": 4.0
  },
  "high_school_geography": {
    "score": 26.31578947368421,
    "num": 19,
    "correct": 4.999999999999999
  },
  "high_school_history": {
    "score": 25.0,
    "num": 20,
    "correct": 5.0
  },
  "high_school_mathematics": {
    "score": 11.11111111111111,
    "num": 18,
    "correct": 2.0
  },
  "high_school_physics": {
    "score": 26.31578947368421,
    "num": 19,
    "correct": 4.999999999999999
  },
  "high_school_politics": {
    "score": 15.789473684210526,
    "num": 19,
    "correct": 3.0
  },
  "ideological_and_moral_cultivation": {
    "score": 10.526315789473685,
    "num": 19,
    "correct": 2.0
  },
  "law": {
    "score": 37.5,
    "num": 24,
    "correct": 9.0
  },
  "legal_professional": {
    "score": 43.47826086956522,
    "num": 23,
    "correct": 10.0
  },
  "logic": {
    "score": 18.181818181818183,
    "num": 22,
    "correct": 4.000000000000001
  },
  "mao_zedong_thought": {
    "score": 20.833333333333332,
    "num": 24,
    "correct": 5.0
  },
  "marxism": {
    "score": 21.05263157894737,
    "num": 19,
    "correct": 4.0
  },
  "metrology_engineer": {
    "score": 33.333333333333336,
    "num": 24,
    "correct": 8.0
  },
  "middle_school_biology": {
    "score": 38.095238095238095,
    "num": 21,
    "correct": 8.0
  },
  "middle_school_chemistry": {
    "score": 35.0,
    "num": 20,
    "correct": 7.0
  },
  "middle_school_geography": {
    "score": 8.333333333333334,
    "num": 12,
    "correct": 1.0
  },
  "middle_school_history": {
    "score": 13.636363636363637,
    "num": 22,
    "correct": 3.0
  },
  "middle_school_mathematics": {
    "score": 10.526315789473685,
    "num": 19,
    "correct": 2.0
  },
  "middle_school_physics": {
    "score": 31.57894736842105,
    "num": 19,
    "correct": 6.0
  },
  "middle_school_politics": {
    "score": 9.523809523809524,
    "num": 21,
    "correct": 2.0
  },
  "modern_chinese_history": {
    "score": 26.08695652173913,
    "num": 23,
    "correct": 6.0
  },
  "operating_system": {
    "score": 31.57894736842105,
    "num": 19,
    "correct": 6.0
  },
  "physician": {
    "score": 24.489795918367346,
    "num": 49,
    "correct": 12.0
  },
  "plant_protection": {
    "score": 27.272727272727273,
    "num": 22,
    "correct": 6.0
  },
  "probability_and_statistics": {
    "score": 11.11111111111111,
    "num": 18,
    "correct": 2.0
  },
  "professional_tour_guide": {
    "score": 24.137931034482758,
    "num": 29,
    "correct": 7.0
  },
  "sports_science": {
    "score": 0.0,
    "num": 19,
    "correct": 0.0
  },
  "tax_accountant": {
    "score": 22.448979591836736,
    "num": 49,
    "correct": 11.0
  },
  "teacher_qualification": {
    "score": 27.272727272727273,
    "num": 44,
    "correct": 12.0
  },
  "urban_and_rural_planner": {
    "score": 32.608695652173914,
    "num": 46,
    "correct": 15.0
  },
  "veterinary_medicine": {
    "score": 26.08695652173913,
    "num": 23,
    "correct": 6.0
  },
  "college_economics": {
    "score": 36.36363636363637,
    "num": 55,
    "correct": 20.000000000000004
  },
  "grouped": {
    "STEM": {
      "correct": 104.0,
      "num": 430,
      "score": 0.24186046511627907
    },
    "Social Science": {
      "correct": 69.0,
      "num": 275,
      "score": 0.2509090909090909
    },
    "Humanities": {
      "correct": 61.0,
      "num": 257,
      "score": 0.23735408560311283
    },
    "Other": {
      "correct": 94.0,
      "num": 384,
      "score": 0.24479166666666666
    }
  },
  "All": {
    "score": 0.2436849925705795,
    "num": 1346,
    "correct": 328.0
  }
}
```
Chinese-llama-2-13B的5-shot测试结果，score仅有24

**Comment by ymcui** [comment]
1. LLaMA为什么要开启`with_prompt`呢？
2. `constrained_decoding`我们设置的是True，wiki里也是这么写的
3. 测试没有什么trick，超参就是temperature=0.2，如果复现不了多半是你的模型下载（或者合并）的有问题。

**Comment by X-Buring** [comment]
> 

感谢您的回复！
1. llama开启with_prompt这个是我疏忽了，我改正后再试试
2. constrained_decoding参数提供了两种测试方式，您试验中这两种方式测出来的结果差异大么？我这边其实是两个都试了一下，差异有一些但似乎不是太大
3. 可能是前面参数不一致导致的吧，我部署过模型进行推理，没发现异常，我再测试一下。

**Comment by ydove0324** [comment]
> > 1. LLaMA为什么要开启`with_prompt`呢？
> > 2. `constrained_decoding`我们设置的是True，wiki里也是这么写的
> > 3. 测试没有什么trick，超参就是temperature=0.2，如果复现不了多半是你的模型下载（或者合并）的有问题。
> 
> > 
> 
> 感谢您的回复！
> 
> 1. llama开启with_prompt这个是我疏忽了，我改正后再试试
> 2. constrained_decoding参数提供了两种测试方式，您试验中这两种方式测出来的结果差异大么？我这边其实是两个都试了一下，True的时候有时候会有response和预测的ans不一样的情况，觉得很不符合预期。
>    ![1](https://user-images.githubusercontent.com/8606089/262536127-cb08e0a2-c203-4ebc-8f9e-43679871760d.png)
> 3. 可能是前面参数不一致导致的吧，我部署过模型进行推理，没发现异常，我再测试一下。

您好 请问你的问题解决了吗 我也是13B的eval只有26% 也把with_prompt删去了

**Comment by ymcui** [comment]
我专门在colab上重新跑了一下，代码都是本项目开源的。以下是具体执行命令和结果（valid set），模型是Chinese-LLaMA-2-13B。自行比对和debug吧，或者从源头排查模型文件本身是否有问题。

### zero-shot
```python
!cd ./Chinese-LLaMA-Alpaca-2/scripts/ceval && CUDA_VISIBLE_DEVICES=0 python eval.py \
    --model_path /content/chinese-llama-2-13b-hf \
    --cot False \
    --few_shot False \
    --with_prompt False \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir /content/ceval-13b-0shot
```

结果（summary.json）：
```json
  "All": {
    "score": 0.40564635958395245,
    "num": 1346,
    "correct": 546.0
  }
}
```

### few-shot
```python
!cd ./Chinese-LLaMA-Alpaca-2/scripts/ceval && CUDA_VISIBLE_DEVICES=0 python eval.py \
    --model_path /content/chinese-llama-2-13b-hf \
    --cot False \
    --few_shot True \
    --with_prompt False \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir /content/ceval-13b-5shot
```

结果（summary.json）：
```json
  "All": {
    "score": 0.42719167904903416,
    "num": 1346,
    "correct": 575.0
  }
}
```

**Comment by X-Buring** [comment]
> 我专门在colab上重新跑了一下，代码都是本项目开源的。以下是具体执行命令和结果（valid set），模型是Chinese-LLaMA-2-13B。自行比对和debug吧，或者从源头排查模型文件本身是否有问题。
> 
> ### zero-shot
> ```python
> !cd ./Chinese-LLaMA-Alpaca-2/scripts/ceval && CUDA_VISIBLE_DEVICES=0 python eval.py \
>     --model_path /content/chinese-llama-2-13b-hf \
>     --cot False \
>     --few_shot False \
>     --with_prompt False \
>     --constrained_decoding True \
>     --temperature 0.2 \
>     --n_times 1 \
>     --ntrain 5 \
>     --do_save_csv False \
>     --do_test False \
>     --output_dir /content/ceval-13b-0shot
> ```
> 
> 结果（summary.json）：
> 
> ```json
>   "All": {
>     "score": 0.40564635958395245,
>     "num": 1346,
>     "correct": 546.0
>   }
> }
> ```
> 
> ### few-shot
> ```python
> !cd ./Chinese-LLaMA-Alpaca-2/scripts/ceval && CUDA_VISIBLE_DEVICES=0 python eval.py \
>     --model_path /content/chinese-llama-2-13b-hf \
>     --cot False \
>     --few_shot True \
>     --with_prompt False \
>     --constrained_decoding True \
>     --temperature 0.2 \
>     --n_times 1 \
>     --ntrain 5 \
>     --do_save_csv False \
>     --do_test False \
>     --output_dir /content/ceval-13b-5shot
> ```
> 
> 结果（summary.json）：
> 
> ```json
>   "All": {
>     "score": 0.42719167904903416,
>     "num": 1346,
>     "correct": 575.0
>   }
> }
> ```

我现在已经能复现出您上述的得分结果，我现在的问题不是在summary.json里，而是在程序运行时的输出上：
如果开启  --constrained_decoding True ，在运行时，我会发下有的问题模型输出的 response 和测试程序提取到的 ans 并不一致。
而且当我设置   --constrained_decoding False 后，模型也并不总是在第一个token输出预测的答案，有时会先分析问题、在最后再给出答案，在  --constrained_decoding False 设置下就没发现模型输出的 response 和测试程序提取到的 ans 不一致的问题，我想问一下您是不是也有这种情况，如果有的话、为什么还要采用 --constrained_decoding True 的方式进行测试；如果您那边没有这种情况的话，我想排查一下可能问题在哪。

最后感谢您的回复！

**Comment by X-Buring** [comment]
> > constrained_decoding参数提供了两种测试方式，您试验中这两种方式测出来的结果差异大么？我这边其实是两个都试了一下，True的时候有时候会有response和预测的ans不一样的情况，觉得很不符合预期。
> 
> 正常，response是模型直接生成的结果，而抽取的ans还考虑了其他候选标签的概率

我没太理解，为什么模型直接生成的结果，不能作为ans呢？我觉得直观上看，如果模型输出的句子是“C”，我觉得无论如何不应该计算出ans是其他选项啊，我没理解您的逻辑，能更详细的解释一下么？
另外我设置 --constrained_decoding False 后，以正则表达式从模型生成的文本中提取答案时，没发现类似的问题，提取出来的ans和我从模型输出里直观上得到的答案是基本一致的。

**Comment by airaria** [comment]
response的结果是模型生成的第一个token，可以拿它做为答案。

只是我们采用了一种稍不同的策略。在constrained_decoding=True解码策略下，比如response的token是C，但A+_A的概率超过C+_C，那么最终答案就是A。

哪种策略更好没有绝对的对错之分，依据实际效果和需求决定。
