### ISSUE TITLE
openai_api_server_vllm.py 部署出错

### ISSUE THREAD

**Issue by zzx16045223** [ymcui/Chinese-LLaMA-Alpaca-2#178]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

LLaMA-2-13B

### 操作系统

Linux

### 详细描述问题

UDA_VISIBLE_DEVICES=3 python openai_api_server_vllm.py --model /workspace/ypg/Chinese-LLaMA-Alpaca-2/llama2_model/chinese-alpaca-2-13b --tokenizer-mode slow --served-model-name chinese-llama-alpaca-2

无法绑定端口
INFO:     Started server process [1851872]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

### 依赖情况（代码类问题务必提供）

peft                      0.3.0.dev0
sentence-transformers     2.2.2
torch                     2.0.1
torchvision               0.15.2
transformers              4.31.0

### 运行日志或截图

INFO:     Started server process [1851872]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

**Comment by ymcui** [comment]
非vllm的有没有这个问题？

**Comment by zzx16045223** [comment]
> 非vllm的有没有这个问题？

我试过非llm的，那个没有问题，带vllm的一直出现端口无法绑定的问题，我的8000端口没有被占用

**Comment by GoGoJoestar** [comment]
部署时可以通过`--port`参数设置端口号，换成其他的端口试下
