### ISSUE TITLE
基于Llama2-7B的基座模型进行二次预训练，推理时出现重复和无法停止现象

### ISSUE THREAD

**Issue by YinSonglin1997** [ymcui/Chinese-LLaMA-Alpaca-2#179]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
采用您的代码框架对Llama2进行中文二次预训练，训练结束后推理发现，回复有重复，且无法停止，见下图：
![1692801347222](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/90330685/354fb814-ccc7-469c-95ca-b09711ec834d)
请问这是什么原因？有什么办法解决吗？或者说在接下来指令精调时是否有影响？
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by airaria** [comment]
是偶尔出现还是频繁现象？
另外，如果后面正常进行了SFT，那么对最终模型的效果基本没有影响。

**Comment by YinSonglin1997** [comment]
> 是偶尔出现还是频繁现象？ 另外，如果后面正常进行了SFT，那么对最终模型的效果基本没有影响。

感谢您的回复。是频繁现象，推理时偶尔不重复，但是一直无法停止。还有我们发现一个现象，有时候回复会重复输入内容，但清空历史后该现象会消失。
![1692836842515](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/90330685/8f4b36a9-f506-4ffa-b9ac-8e9412a4f68b)

**Comment by airaria** [comment]
你是用gradio_demo.py测试llama模型？ gradio_demo.py会加上prompt，不适合测llama模型；
如果你想看llama模型的生成效果，建议用inference_hf.py测试

**Comment by suyan-liang** [comment]
> 

我也出现了这个问题，为什么会这样呢？如果我想用gradio_demo.py怎么操作？

**Comment by YinSonglin1997** [comment]
> 你是用gradio_demo.py测试llama模型？ gradio_demo.py会加上prompt，不适合测llama模型； 如果你想看llama模型的生成效果，建议用inference_hf.py测试

好的，我后面又进行了SFT，能正常对话。但我发现模型好像并不能联系上文，例如下图所示：
![1693188852927](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/90330685/9151daf7-cc3d-4c34-a360-38bd80f6259c)
当我问刚才提的问题时，模型并不能答复，请问这是什么原因呢？

**Comment by huxiaosheng123** [comment]
可以参考：https://github.com/huxiaosheng123/open-llama2

**Comment by yunhao233** [comment]
我在使用llama2-7b 基座模型测试生成也遇到了类似的问题，模型的生成回答只是在重复我的输入
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/44170254/9f5cb22c-0a51-4123-a01c-03606b96bb56)
