### ISSUE TITLE
合并中间checkpoint

### ISSUE THREAD

**Issue by altria-zewei-wang** [ymcui/Chinese-LLaMA-Alpaca-2#181]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

想问一下能不能合并中途的checkpoint查看效果？直接用merge_llama2_with_chinese_lora_low_mem会报错

### 运行日志或截图

================================================================================
Base model: ../../configs
LoRA model: /training/output/scripts/training/checkpoing-22200
Loading /training/output/scripts/training/checkpoing-22200
Cannot find lora model on the disk. Downloading lora model from hub...
Traceback (most recent call last):
  File "/mnt/d/Chinese-LLaMA-Alpaca-2/scripts/merge_llama2_with_chinese_lora_low_mem.py", line 238, in <module>
    lora_model_path = snapshot_download(repo_id=lora_model_path)
  File "/home/zw238/miniconda3/envs/train/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/zw238/miniconda3/envs/train/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/training/output/scripts/training/checkpoing-22200'. Use `repo_type` argument if needed.

**Comment by airaria** [comment]
checkpoint-XXX目录下有pt_lora_model或sft_model目录，里面应该有adapter_model.bin。并时指定该文件夹

**Comment by altria-zewei-wang** [comment]
你好，合并后出现这个问题：RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]，请问有可能是哪里出错了呢

**Comment by airaria** [comment]
是合并后推理的时候报错？tokenizer的问题。
检查一下tokenizer是否正确？或者直接从我们发布的模型文件夹中复制tokenizer相关文件
