### ISSUE TITLE
run_sft.sh使用 --flash_attn会报错

### ISSUE THREAD

**Issue by zzx16045223** [ymcui/Chinese-LLaMA-Alpaca-2#186]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Alpaca-2-13B

### 操作系统

Linux

### 详细描述问题

使用  --flash_attn参数进行指令精调出错

lr=1e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/workspace/ypg/Chinese-LLaMA-Alpaca-2/llama2_model/chinese-alpaca-2-13b
chinese_tokenizer_path=/workspace/ypg/Chinese-LLaMA-Alpaca-2/llama2_model/chinese-alpaca-2-13b
dataset_dir=/workspace/ypg/Chinese-LLaMA-Alpaca-2/dataset/cailian_data/20230824_1000_data
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
output_dir=/workspace/ypg/Chinese-LLaMA-Alpaca-2/output/20230824_1000_data/1_epoch
# peft_model=/workspace/ypg/Chinese-LLaMA-Alpaca-2/llama2_model/chinese-alpaca-2-13b
validation_file=/workspace/ypg/Chinese-LLaMA-Alpaca-2/dataset/cailian_data/20230824_1000_data/output.json

num_train_epochs=1
max_seq_length=5000

deepspeed_config_file=ds_zero2_no_offload.json

torchrun --nnodes 1 --nproc_per_node 2 run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed $RANDOM \
    --fp16 \
    --num_train_epochs ${num_train_epochs} \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 1000 \
    --save_steps 1000 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length ${max_seq_length} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --modules_to_save ${modules_to_save} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False \
    --flash_attn

File "/opt/conda/envs/llama_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ypg/Chinese-LLaMA-Alpaca-2/scripts/training/flash_attn_patch.py", line 59, in forward
    assert not use_cache, "use_cache is not supported"
AssertionError: use_cache is not supported
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2097697) of binary: /opt/conda/envs/llama_env/bin/python

### 依赖情况（代码类问题务必提供）

peft                      0.3.0.dev0
sentence-transformers     2.2.2
torch                     2.0.1
torchvision               0.15.2
transformers              4.31.0

### 运行日志或截图

  File "/workspace/ypg/Chinese-LLaMA-Alpaca-2/scripts/training/flash_attn_patch.py", line 59, in forward
    assert not use_cache, "use_cache is not supported"
AssertionError: use_cache is not supported
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2097697) of binary: /opt/conda/envs/llama_env/bin/python

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/46176408/d3c4e7fe-3594-46dd-ae1f-0a08492fb245)

**Comment by iMountTai** [comment]
pull最新代码试试
