### ISSUE TITLE
请问指令精调后的模型，输入什么都只按指令训练的格式输出，这是什么原因？

### ISSUE THREAD

**Issue by czhcc** [ymcui/Chinese-LLaMA-Alpaca-2#190]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

指令精调，执行合并后，使用模型时，似乎对合适的问句回复是训练的效果。但如果用其它问句，尽然也按训练的格式输出。这是怎么回事？换system_prompt也一样。
使用的基础模型是chinese-alpaca-2-7b。

用来训练的2万条数据都是这样的格式
{
        "instruction": "基于知识图谱生成问句，转换成图查询结构",
        "input": "庞咏梅的车",
        "output": "{条件:{类型：人}，属性：{姓名：庞咏梅}，目标:{类型：车}}"
    }
只是姓名不一样，这样会有影响吗

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by czhcc** [comment]
重新训练了一遍又没事了

**Comment by Dmm2584v** [comment]
你好，想问一下你这个指令微调的时候，改system_prompt(You are a helpful assistant. 你是一个乐于助人的助手。)了吗？

**Comment by Dmm2584v** [comment]
训了多少epoch？
