### ISSUE TITLE
langchain_qa.py 模型拉起很慢

### ISSUE THREAD

**Issue by cccgw** [ymcui/Chinese-LLaMA-Alpaca-2#193]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

使用项目下载的chinese-alpaca-2-7b-hf，在执行langchain_qa.py发现拉起模型很慢，大约需要5分钟以上还没有反应，但最终会拉成功。每次都能重现，不知道有没有遇到类似情况。

```
python langchain_qa.py \
  --embedding_path /root/autodl-tmp/data/text2vec-large-chinese \
  --model_path /root/autodl-tmp/data/chinese-alpaca-2-7b-hf  \
  --file_path doc.txt \
  --chain_type refine


```
在langchain_qa.py执行到这一步的时候，会非常慢。
```
    print("loading LLM...")
    model = HuggingFacePipeline.from_model_id(model_id=model_path,
            task="text-generation",
            device=0,
            model_kwargs={
                          "torch_dtype" : load_type,
                          "low_cpu_mem_usage" : True,
                          "temperature": 0.2,
                          "max_length": 1000,
                          "repetition_penalty":1.1}
            )
```

### 依赖情况（代码类问题务必提供）

```
peft                           0.3.0.dev0
sentence-transformers          2.2.2
torch                          2.0.0+cu118
torchvision                    0.15.1+cu118
transformers                   4.30.2
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by fattho0919** [comment]
AutoTokenizer.from_pretrained(ziqingyang/chinese-llama-2-7b) 也會

**Comment by ymcui** [comment]
原版llama-2是否速度慢？

**Comment by iMountTai** [comment]
检查一下要求的依赖是不是正确安装了？我加载模型大约50s
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/35353688/dc155fb5-6190-4a60-8682-b8264acdebbc)

**Comment by airaria** [comment]
有可能是autotokenizer的问题，
手动把lanagchain中的HuggingFacePipeline下的
```python
tokenizer = AutoTokenizer.from_pretrained(model_id, **_model_kwargs)
```
改成
```
tokenizer = LlamaTokenizer.from_pretrained(...)
```
试试

**Comment by cccgw** [comment]
手动把lanagchain中的HuggingFacePipeline下的

tokenizer = AutoTokenizer.from_pretrained(model_id, **_model_kwargs)
改成

tokenizer = LlamaTokenizer.from_pretrained(...)
亲测有效，感谢。记得从transformer import LlamaTokenizer

**Comment by ZhishanQ** [comment]
> transformer import LlamaTokenizer

transformers import LlamaTokenizer
而不是transformer import LlamaTokenizer
