### ISSUE TITLE
会开源33B模型吗？

### ISSUE THREAD

**Issue by lucasjinreal** [ymcui/Chinese-LLaMA-Alpaca-2#194]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

None

### 操作系统

Linux

### 详细描述问题

`楼主会开源33B模型吗？目前13b看起来效果也比较有限

### 依赖情况（代码类问题务必提供）

w

### 运行日志或截图

w

**Comment by ymcui** [comment]
你应该先看一下meta发布了Llama-2-34B模型没有。

**Comment by lucasjinreal** [comment]
@ymcui 貌似WizardCoder 34b humaneval上已经超过老版本的gpt4了。llama2 license. 不知楼主是否考虑？

**Comment by ymcui** [comment]
目前这个时间节点暂无计划。
