### ISSUE TITLE
赞！动作真快！能否直接上 plus 版本？

### ISSUE THREAD

**Issue by jamesljl** [ymcui/Chinese-LLaMA-Alpaca-2#2]

**Comment by ymcui** [comment]
会综合考虑训练速度做权衡。
顺利的话会直接出Plus版（120G+数据），但可能不叫这个名字。

**Comment by lucasjinreal** [comment]
@ymcui 请问一下这里的120G是sft的数据还是pretrain的数据

**Comment by ymcui** [comment]
> @ymcui 请问一下这里的120G是sft的数据还是pretrain的数据

预训练数据。SFT数据我们项目一般按条目数计，例如3M，4M。
