### ISSUE TITLE
模型转换失败，报告“can't find model in directory”

### ISSUE THREAD

**Issue by liqiang28** [ymcui/Chinese-LLaMA-Alpaca-2#200]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Alpaca-2-13B

### 操作系统

macOS

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
python3 convert.py zh-models/13B/

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
Traceback (most recent call last):
  File "/Users/liqiang/Projects/llm/chinese-llama/llama.cpp/convert.py", line 1172, in <module>
    main()
  File "/Users/liqiang/Projects/llm/chinese-llama/llama.cpp/convert.py", line 1120, in main
    model_plus = load_some_model(args.model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liqiang/Projects/llm/chinese-llama/llama.cpp/convert.py", line 1033, in load_some_model
    raise Exception(f"Can't find model in directory {path}")
Exception: Can't find model in directory zh-models/13B

**Comment by liqiang28** [comment]
已经按照要求 安装了requirements.txt 中所有的依赖

**Comment by ymcui** [comment]
你应该补充一下问题的上下文信息。
1. 看你的命令应该是指llama.cpp的步骤？
2. `zh-models/13B/`目录里存放的是什么？里面有哪些文件（`ls`）？从哪里获取的？

**Comment by liqiang28** [comment]
目录里面存放的是从百度网盘下载的chinese-alpaca-2-13b-hf 文件夹中的内容， 目录中的文件列表如下：
liqiang@oarsmans-MacBook-Pro-M1 13B % ls
SHA256.md
config.json
generation_config.json
pytorch_model-00001-of-00003.bin.baiduyun.p.downloading
pytorch_model-00002-of-00003.bin.baiduyun.p.downloading
pytorch_model-00003-of-00003.bin.baiduyun.p.downloading
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer.model
tokenizer_config.json

**Comment by liqiang28** [comment]
Sorry, 可能是我的错，我才发现我的chinese-alpaca-2-13b-hf 模型文件并没有下载完成，可能是这个问题，我等下载完再试一下。顺便问一下，完整版的模型下载完之后，应该用convert.py命令转换一下，然后再加载使用，这个我没有理解错吧？谢谢

**Comment by liqiang28** [comment]
好的，明白了，我等全部下载完了再试试，谢谢
