### ISSUE TITLE
微调后tokenizer 分词错误

### ISSUE THREAD

**Issue by mengban** [ymcui/Chinese-LLaMA-Alpaca-2#202]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
auto_t.encode("吃了吗</s>")
[1, 29871, 32050, 34353, 829, 29879, 29958]
```
在alpaca-7b的基础上进行sft全参微调 使用ckpt的模型和tokenizer 进行分词 发现</s>不能正确分出来。如上图所示

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
torch                         2.0.1
torchaudio                    2.0.2
torchvision                   0.15.2
transformers                  4.32.0
transformers-stream-generator 0.0.4
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
auto_t.encode("吃了吗</s>")
[1, 29871, 32050, 34353, 829, 29879, 29958]
```

**Comment by mengban** [comment]
> SFT不会对tokenizer做改动。请检查是否加载了正确的tokenizer？ 我运行的结果如下：
> 
> ```python
> from transformers import LlamaTokenizer
> tokenizer = LlamaTokenizer.from_pretrained('ziqingyang/chinese-llama-2-7b')
> print(tokenizer.encode("吃了吗</s>")) #[1, 29871, 35302, 32013, 2]
> ```

SFT 过程中最后使用了 trainer.save_model() 进行了ckpt的保存 保存目录如下：
```
total 13G
drwxr-xr-x  2 root root 4.0K 8月  29 17:44 .
drwxr-xr-x 15 root root 4.0K 8月  28 16:14 ..
-rw-r--r--  1 root root  630 8月  28 16:15 config.json
-rw-r--r--  1 root root  132 8月  28 16:15 generation_config.json
-rw-r--r--  1 root root 9.4G 8月  28 16:16 pytorch_model-00001-of-00002.bin
-rw-r--r--  1 root root 3.7G 8月  28 16:16 pytorch_model-00002-of-00002.bin
-rw-r--r--  1 root root  27K 8月  28 16:15 pytorch_model.bin.index.json
-rw-r--r--  1 root root  435 8月  28 16:15 special_tokens_map.json
-rw-r--r--  1 root root  788 8月  28 16:15 tokenizer_config.json
-rw-r--r--  1 root root 2.6M 8月  28 16:15 tokenizer.json.
-rw-r--r--  1 root root 825K 8月  28 16:15 tokenizer.model
```

然后后面Auto**.from_pretrained()  都传的这个目录
就发现tokenizer 出现了</s> 分错的现象

**Comment by airaria** [comment]
> 然后后面Auto**.from_pretrained() 都传的这个目录
> 就发现tokenizer 出现了 分错的现象

经测试发现AutoTokenizer和LlamaTokenizer行为不一致，你用LlamaTokenizer.from_pretrained()初始化tokenizer试试

**Comment by mengban** [comment]
> 

嗯嗯 我试了 LlamaTokenizer是正常的。
AutoTokenizer 实例化出来的是LlamaTokenizerFast  
但是他把</s> 拆开了感觉就很奇怪。。。

**Comment by mengban** [comment]
> > 然后后面Auto**.from_pretrained() 都传的这个目录
> > 就发现tokenizer 出现了 分错的现象
> 
> 经测试发现AutoTokenizer和LlamaTokenizer行为不一致，你用LlamaTokenizer.from_pretrained()初始化tokenizer试试

嗯嗯 我试了 LlamaTokenizer是正常的。
AutoTokenizer 实例化出来的是LlamaTokenizerFast  
但是他把</s> 拆开了感觉就很奇怪。。。

**Comment by mengban** [comment]
update:
对比了下meta 官方的模型 slow tokenizer和fast tokenizer的分词结果 对同一句话 分词结果是相同的：
```
from transformers import LlamaTokenizer, LlamaTokenizerFast, AutoModel

model_name_or_path = "meta-llama/Llama-2-7b-chat-hf"
sentence = "吃了吗</s>"

llama_t = LlamaTokenizer.from_pretrained(model_name_or_path)
llama_t_fast = LlamaTokenizerFast.from_pretrained(model_name_or_path)

print(llama_t(sentence))
print(llama_t_fast(sentence))

```
输出为
> {'input_ids': [1, 29871, 232, 147, 134, 30743, 232, 147, 154, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
{'input_ids': [1, 29871, 232, 147, 134, 30743, 232, 147, 154, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

然后对比了下`ziqingyang/chinese-alpaca-2-7b` 对同一句话 分词结果是不同的
```
from transformers import LlamaTokenizer, LlamaTokenizerFast

model_name_or_path = "ziqingyang/chinese-alpaca-2-7b"
sentence = "吃了吗</s>"

llama_t = LlamaTokenizer.from_pretrained(model_name_or_path)
llama_t_fast = LlamaTokenizerFast.from_pretrained(model_name_or_path)

print(llama_t(sentence))
print(llama_t_fast(sentence))
```
输出为
>{'input_ids': [1, 29871, 35302, 32013, 2], 'attention_mask': [1, 1, 1, 1, 1]}
{'input_ids': [1, 29871, 32050, 34353, 2], 'attention_mask': [1, 1, 1, 1, 1]}


对同一句话 slow 和fast分词器分词结果是不同的。这个现象符合你们预期吗

**Comment by TengLi931128** [comment]
> > > 然后后面Auto**.from_pretrained() 都传的这个目录
> > > 就发现tokenizer 出现了 分错的现象
> > 
> > 
> > 经测试发现AutoTokenizer和LlamaTokenizer行为不一致，你用LlamaTokenizer.from_pretrained()初始化tokenizer试试
> 
> 嗯嗯 我试了 LlamaTokenizer是正常的。 AutoTokenizer 实例化出来的是LlamaTokenizerFast 但是他把`</s> `拆开了感觉就很奇怪。。。

+1，我之前也发现了同样的问题，在脚本里修改设置--use_fast_tokenizer False才可以。是不是在扩充词表的时候有一些bug？

**Comment by airaria** [comment]
> 对同一句话 slow 和fast分词器分词结果是不同的。这个现象符合你们预期吗

相关问题我们会进一步定位。
此外，我们在扩充词表、预训练、精调整个过程中用的都是slow的LlamaTokenizer
所以最保险是的方式是在下游中也用LlamaTokenizer初始化tokenizer。
