### ISSUE TITLE
怎样在指令精调时指定训练使用的GPU

### ISSUE THREAD

**Issue by czhcc** [ymcui/Chinese-LLaMA-Alpaca-2#205]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-13B

### 操作系统

Linux

### 详细描述问题

如题。有多块GPU，但只想使用其中一块进行训练。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by czhcc** [comment]
没事了，用
export CUDA_VISIBLE_DEVICES=
解决了，开始直接写
CUDA_VISIBLE_DEVICES=
在sh里没效果

**Comment by xiaoToby** [comment]
> 没事了，用 export CUDA_VISIBLE_DEVICES= 解决了，开始直接写 CUDA_VISIBLE_DEVICES= 在sh里没效果

我这边试了，好像还是没有实现多卡训练的效果，无论是在sh文件内写入export CUDA_VISIBLE_DEVICES=，还是在sh文件外定义export CUDA_VISIBLE_DEVICES 这个环境，都没有用。。。。。
