### ISSUE TITLE
显存不足情况下是否可以直接精调训练量化模型

### ISSUE THREAD

**Issue by tabusearch** [ymcui/Chinese-LLaMA-Alpaca-2#207]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
    if model_args.model_name_or_path:
        torch_dtype = (
            model_args.torch_dtype
            if model_args.torch_dtype in ["auto", None]
            else getattr(torch, model_args.torch_dtype)
        )
        model = LlamaForCausalLM.from_pretrained(
            model_args.model_name_or_path,
            from_tf=bool(".ckpt" in model_args.model_name_or_path),
            config=config,
            cache_dir=model_args.cache_dir,
            revision=model_args.model_revision,
            use_auth_token=True if model_args.use_auth_token else None,
            torch_dtype=torch_dtype,
            low_cpu_mem_usage=True,
            quantization_config=BitsAndBytesConfig(
            load_in_8bit = True
            )
        )
    else:
        model = AutoModelForCausalLM.from_config(config)
        n_params = sum({p.data_ptr(): p.numel() for p in model.parameters()}.values())
        logger.info(f"Training new model from scratch - Total size={n_params/2**20:.2f}M params")
```
显存不足的情况下是否支持直接训练量化模型。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```
peft                         0.3.0.dev0
pytorch-lightning            2.0.2
torch                        2.0.1
torchaudio                   0.9.0
torchmetrics                 0.11.4
torchvision                  0.15.1
transformers                 4.31.0

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
尝试后发现会报错：
  File "/home/xx/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xx/miniconda3/envs/llm/lib/python3.9/site-packages/peft/tuners/lora.py", line 532, in forward
    output = self.lora_B(self.lora_A(self.lora_dropout(x))).to(expected_dtype) * self.scaling
  File "/home/xx/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xx/miniconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)

**Comment by ymcui** [comment]
如果你熟悉QLoRA，那当然是可以的。我们目前还没整理QLoRA的适配代码，感兴趣的话可以自行修改适配。

**Comment by tabusearch** [comment]
根据qlora的指引。我自己也改了下量化模型的训练，是可以训练起来的。主要是在加载模型的时候（ LlamaForCausalLM.from_pretrained）提供量化参数（quantization_config）。
另外，加载完成后还需要加一句    model = prepare_model_for_kbit_training(model)
谢谢两位的指导。
if model_args.model_name_or_path:
        torch_dtype = (
            model_args.torch_dtype
            if model_args.torch_dtype in ["auto", None]
            else getattr(torch, model_args.torch_dtype)
        )
        model = LlamaForCausalLM.from_pretrained(
            model_args.model_name_or_path,
            from_tf=bool(".ckpt" in model_args.model_name_or_path),
            config=config,
            cache_dir=model_args.cache_dir,
            revision=model_args.model_revision,
            use_auth_token=True if model_args.use_auth_token else None,
            torch_dtype=torch_dtype,
            low_cpu_mem_usage=True,
            **quantization_config=BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16
            )**
        )

另外，还想借这个楼问下，当我采用“基于Chinese-LLaMA-2 LoRA进行指令精调”时（即：提供peft_path）。训练会报错，我看加载lora模型的时候似乎is_trainable这个参数默认设置的False，我把这个参数改为True就可以正常训练了，不知道这个是作者遗漏的问题还是哪里我调整的不对。    
if training_args.peft_path is not None:
        logger.info("Peft from pre-trained model")
        model = PeftModel.from_pretrained(model, training_args.peft_path, **is_trainable=True**)
