### ISSUE TITLE
Llama-2-13B-hf与alpaca2-13b-lora合并前需要词表合并吗？

### ISSUE THREAD

**Issue by liyunhan** [ymcui/Chinese-LLaMA-Alpaca-2#208]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Alpaca-2-13B

### 操作系统

Windows

### 详细描述问题

有几个问题希望得到回答：
1. 请问“Chinese-Alpaca-2-LoRA-13B”等都是在“Llama-2-13b-hf”的基础上进行增量训练得到的吗？即中文的增量预训练和指令Prompt？
2. readme有详细的讲解了lora和基石模型合并的方法，请问还需要做词表合并吗？如果我想自己从huggingface加载模型，肯定是需要先合并词表的吧？可是没有看到相关的介绍或是方法？ 

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
1. 第一个问题：不是。见FAQ回答 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/faq_zh#问题6chinese-alpaca-2是llama-2-chat训练得到的吗 
2. 第二个问题：不需要词表合并。LoRA模型带的词表就是已经合并过的。所谓的合并指的是权重的合并，我们的脚本会做好这些，你只需要按照我们wiki的步骤操作就行了。

**Comment by airaria** [comment]
1. 是
2. 使用我们配套发布的tokenizer，不需要再做词表合并，发布的tokenizer已经是合并后的了。

**Comment by liyunhan** [comment]
> 1. 第一个问题：不是。见FAQ回答 [https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/faq_zh#问题6chinese-alpaca-2是llama-2-chat训练得到的吗](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/faq_zh#%E9%97%AE%E9%A2%986chinese-alpaca-2%E6%98%AFllama-2-chat%E8%AE%AD%E7%BB%83%E5%BE%97%E5%88%B0%E7%9A%84%E5%90%97)
> 2. 第二个问题：不需要词表合并。LoRA模型带的词表就是已经合并过的。所谓的合并指的是权重的合并，我们的脚本会做好这些，你只需要按照我们wiki的步骤操作就行了。

第一个问题：Chinese-Alpaca-2是在Chinese-LLaMA-2的基础上得到，所有方法都是通过Lora。那就是先通过Lora的方式训练了Chinese-LLaMA-2，再进一步通过Lora的方式精调。这个流程等于说：从头到尾都是在一个Lora参数上展开训练的？

**Comment by ymcui** [comment]
可以这么理解。Alpaca-2训练阶段会加载LLaMA-2的LoRA继续训练。
我们一代的项目是两个独立的LoRA，二代（本项目）里都采用一个LoRA的形式了。

**Comment by liyunhan** [comment]
> 可以这么理解。Alpaca-2训练阶段会加载LLaMA-2的LoRA继续训练。 我们一代的项目是两个独立的LoRA，二代（本项目）里都采用一个LoRA的形式了。

第二个问题：我看到LoRA的文件夹中有tokenizer.model，这个应该是sentencepiece训练后保存的产物，即已包含您提到的合并后的词表。基于此，如果自行加载的流程：
1. 将tokenizer.model转换成huggingface能加载的文件；
2. 使用huaggingface中的llamaTokenizer加载；
3. 照常使用即可。
我的理解是这样，不知道对吗？

**Comment by liyunhan** [comment]
感谢您的回复。

**Comment by ymcui** [comment]
合并之后可以直接被HF加载，不需要其他的操作了。
你可以直接下载合并后的权重：https://huggingface.co/ziqingyang/chinese-alpaca-2-13b/tree/main
之后直接用以下代码就可以加载。
```
tokenizer = LlamaTokenizer.from_pretrained(模型目录, legacy=True)
```

**Comment by liyunhan** [comment]
> 合并之后可以直接被HF加载，不需要其他的操作了。 你可以直接下载合并后的权重：https://huggingface.co/ziqingyang/chinese-alpaca-2-13b/tree/main 之后直接用以下代码就可以加载。
> 
> ```
> tokenizer = LlamaTokenizer.from_pretrained(模型目录, legacy=True)
> ```

非常感谢您！！
