### ISSUE TITLE
请问有没有本地部署的详细教程

### ISSUE THREAD

**Issue by fangyifei222** [ymcui/Chinese-LLaMA-Alpaca-2#209]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

LLaMA-2-13B

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
我下载了代码包和llama2-13B的模型，请问模型应该放到哪里，代码应该运行哪个，才能开始问答，能不能出个详细教程

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
1. llama2不是拿来聊天的。聊天请用alpaca2。
2. 教程都在项目wiki里，选择适合自己的，按步骤操作：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki

**Comment by fangyifei222** [comment]
请问lora模型是针对某一领域微调后的模型吗？

**Comment by fangyifei222** [comment]
> 1. llama2不是拿来聊天的。聊天请用alpaca2。
> 2. 教程都在项目wiki里，选择适合自己的，按步骤操作：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki

请问lora模型是针对特定领域微调后的模型吗？
