### ISSUE TITLE
请问如果想做全量微调的话，和Lora微调的代码一样吗？

### ISSUE THREAD

**Issue by changyuying** [ymcui/Chinese-LLaMA-Alpaca-2#21]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by iMountTai** [comment]
去掉lora相关的配置代码后，可以全量微调。

**Comment by changyuying** [comment]
好的，谢谢您



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月31日 15:49 |
| 收件人 | ***@***.***> |
| 抄送至 | Chang ***@***.***>***@***.***> |
| 主题 | Re: [ymcui/Chinese-LLaMA-Alpaca-2] 请问如果想做全量微调的话，和Lora微调的代码一样吗？ (Issue #21) |

去掉lora相关的配置代码后，可以全量微调。

**Comment by QJShan** [comment]
> 去掉lora相关的配置代码后，可以全量微调。

你好，请问进行全量微调时也是使用因果推理的损失函数吗(交叉熵损失)

**Comment by airaria** [comment]
> > 去掉lora相关的配置代码后，可以全量微调。
> 
> 你好，请问进行全量微调时也是使用因果推理的损失函数吗(交叉熵损失)

是

**Comment by Double-bear** [comment]
> 去掉lora相关的配置代码后，可以全量微调。

请问全量参数训练checkpoint应该如何保存？我用之前的savecallback似乎没有办法把参数保存下来
