### ISSUE TITLE
alpaca推理和指令微调

### ISSUE THREAD

**Issue by Dmm2584v** [ymcui/Chinese-LLaMA-Alpaca-2#214]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

python inference/inference_hf.py \
--base_model ./chinese-alpaca-2-7b \
--with_prompt \
--interactive

### 依赖情况（代码类问题务必提供）

peft                     0.5.0
torch                    2.0.1
torchaudio               2.0.0
torchvision              0.15.0
transformers             4.29.2

### 运行日志或截图

用alpaca-7b 做简单的提问，为什么alpaca-7b无法得到正确回答？
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/51921083/ec543c06-458d-47d4-a4ce-e856ef38db54)

如果需要做指令微调，training/build_dataset.py里面关于system prompt是否需要删除或者修改？

**Comment by Dmm2584v** [comment]
关于system prompt和instruction，在微调阶段到底有什么区别？

**Comment by ymcui** [comment]
1. 你截图的情况多半是因为你下载的模型不完整。
2. 继续训练的时候system prompt可以改，但是没什么太大必要。

**Comment by Dmm2584v** [comment]
1. 我确实是少了SHA文件，谢谢
2. 如果sft不改变system prompt，那在推理的时候也不需要改变。那么其实输入所有都是在放在instruction里面，那system prompt存在的意义是什么？

**Comment by ymcui** [comment]
1. system字段相当于给模型提供“前提”或者“人设”，多数大模型都有类似的设置，你可以参考补充相关知识。
2. inference阶段不是不能改system prompt，比如你可以要求模型回复的尽量简短，就可以加上相应的文字说明（但系统并不是一定会follow你的要求）。

**Comment by Dmm2584v** [comment]
你好，我现在需要做一个分类任务的指令微调，sft格式：
prompt格式：
"[INST] <<SYS>>\n" 
"You are a helpful assistant. 你是一个乐于助人的助手。\n"
"<</SYS>>\n\n{instruction} [/INST]"

数据格式：
{
        "instruction": "你是一个文本分类器，根据下列问题对问题分类，一共六个类别：A：路由器，B：交换机，C：安全，D：WLAN，E：网管软件，F：CE交换机。要求：不要回答问题，只对问题分类，输出分类选项。",
        "input": "AR720 能否实现上下行接口实时速率和累计上下行流量的监控",
        "output": "A"
}

存在几个问题：
因为是分类任务，所以我把它改造为选择题形式，2w+的训练数据，3个epoch，在测试阶段，我按照ceval，用第一个token在6个选项中输出最有可能的选项

1. 在sft训练时loss下降的很快，50步就已经到了0.1损失。但是测试输出准确率很低20%？
2. 测试阶段，输出A和C选项很多，占60%，但训练集中B选项数据量最多的，所以这种情况是训练不够吗？
3. 关于sft训练的loss计算，在build_dataset里面，最终会把instruction+input+output作为label_input?作为自回归任务，不应该是只用instruction+input去预测output吗？https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/9047f48feda9ff1adf6b7241906ec73beeeecfe3/scripts/training/build_dataset.py#L46
