### ISSUE TITLE
在LLaMA-2-13B的基础上再pt和sft

### ISSUE THREAD

**Issue by TengLi931128** [ymcui/Chinese-LLaMA-Alpaca-2#218]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-13B

### 操作系统

None

### 详细描述问题

你好，我想在LLaMA-2-13B的基础上么，再进行全参数（并不使用lora）pt和sft，发现不同的**学习率**对结果有一定的影响，请问关于这种情况：

1. 根据你们的经验，有什么推荐的lr值么？
2. pt和sft过程的lr，有哪些应有的逻辑关系么（例如sft的lr应该取pt阶段最后的lr值）？

十分感谢。

**Comment by ymcui** [comment]
1. LR设置并没有固定的推荐值，取决于你的训练量、模型大小、训练模式（LoRA、全量）等因素，需要自己尝试并观察train/valid loss下降情况
2. 同理，两个阶段之间LR也不是继承关系，并没有类似经验公式的东西
