### ISSUE TITLE
请问120G中文语料包括什么内容？增量训练添加英文语料是否更合适呢？

### ISSUE THREAD

**Issue by peiyingxin** [ymcui/Chinese-LLaMA-Alpaca-2#22]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

其他问题

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

**Comment by nuoma** [comment]
100G应该是pClue从cc里筛出来的中文。
我理解本项目的目的是增强中文能力。如果是从增强其基础能力的方面出发，是不是爬虫数据占比太大了点？
比如说中文占60%，增加电子书等语料来源，英文30%的话从the pile抽。我这样理解对吗？
谢谢

**Comment by ymcui** [comment]
1、增量100G里大部分是cc数据，是我们用cc_net自己爬取的，只筛选出高质量的部分。还有一部分百科数据。
2、增量训练添加英文语料，不好说，如果是很general的数据看似没有必要。原版已经用2T token训练了，不太清楚这样加进去还能有多少收益。

**Comment by nuoma** [comment]
> > 我的个人经验是，可能会训歪掉。我用您的方法，使用了化学相关的语料（2千万字）进行增量预训练（是基座模型），发现同样用Ceval去跑的话（few shot做题目），对比vanilla基座模型，化学生物方面涨点比较厉害（20涨到25的样子），但是其他领域有好多都会降点。
> 
> 如果捎带其他方面的语料，是否能减轻其他领域掉点问题呢？

是的，我会去试验一下。这个想法是受到这篇文章的启发：https://zhuanlan.zhihu.com/p/643805698

**Comment by QJShan** [comment]
> 我的个人经验是，可能会训歪掉。我用您的方法，使用了化学相关的语料（2千万字）进行增量预训练（是基座模型），发现同样用Ceval去跑的话（few shot做题目），对比vanilla基座模型，化学生物方面涨点比较厉害（20涨到25的样子），但是其他领域有好多都会降点。

请问你们在训练的时候是使用因果推理(交叉熵损失预测下一个词)，还是兼容使用gmask的方法。

**Comment by X-jun-0130** [comment]
> > > 我的个人经验是，可能会训歪掉。我用您的方法，使用了化学相关的语料（2千万字）进行增量预训练（是基座模型），发现同样用Ceval去跑的话（few shot做题目），对比vanilla基座模型，化学生物方面涨点比较厉害（20涨到25的样子），但是其他领域有好多都会降点。
> > 
> > 
> > 如果捎带其他方面的语料，是否能减轻其他领域掉点问题呢？
> 
> 是的，我会去试验一下。这个想法是受到这篇文章的启发：https://zhuanlan.zhihu.com/p/643805698

ChatHome_Development and Evaluation of a Domain-Specific Language.这篇论文里面的结果,对于领域的训练可能行业:通用1:5;但采用MIP的话,如果不使用通用数据,也可以取得非常好的结果

**Comment by nuoma** [comment]
> 

非常有用的信息，值得仔细研读，感谢分享！

**Comment by nuoma** [comment]
> > > > 我的个人经验是，可能会训歪掉。我用您的方法，使用了化学相关的语料（2千万字）进行增量预训练（是基座模型），发现同样用Ceval去跑的话（few shot做题目），对比vanilla基座模型，化学生物方面涨点比较厉害（20涨到25的样子），但是其他领域有好多都会降点。
> > > 
> > > 
> > > 如果捎带其他方面的语料，是否能减轻其他领域掉点问题呢？
> > 
> > 
> > 是的，我会去试验一下。这个想法是受到这篇文章的启发：https://zhuanlan.zhihu.com/p/643805698
> 
> ChatHome_Development and Evaluation of a Domain-Specific Language.这篇论文里面的结果,对于领域的训练可能行业:通用1:5;但采用MIP的话,如果不使用通用数据,也可以取得非常好的结果

非常有用的信息，值得仔细研读，感谢分享！

**Comment by nuoma** [comment]
> > 我的个人经验是，可能会训歪掉。我用您的方法，使用了化学相关的语料（2千万字）进行增量预训练（是基座模型），发现同样用Ceval去跑的话（few shot做题目），对比vanilla基座模型，化学生物方面涨点比较厉害（20涨到25的样子），但是其他领域有好多都会降点。
> 
> 请问你们在训练的时候是使用因果推理(交叉熵损失预测下一个词)，还是兼容使用gmask的方法。

run_clm casual language model
