### ISSUE TITLE
关于外文语料通过扩充新词表后再训练的问题（试图保留chinese llama2对中文的理解能力）

### ISSUE THREAD

**Issue by ElivisC** [ymcui/Chinese-LLaMA-Alpaca-2#223]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

您好，我正在尝试使用自己的外文语料在llama 2来进行大语言模型微调同时还希望保留您这边提供的模型的中文能力，遇到如下问题：
我试图通过您提供的方法扩充chinese llama2的词表，然后基于您提供的合并后的chinese llama2进行pt是否可行？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by airaria** [comment]
如果需要再扩充词表，建议步骤如下：
1. 在您的外语语料上训练tokenizer
2. 将您的tokenizer和chinese-llama-2 tokenizer合并
3. 扩展合并后的chinese-llama-2的vocab size，使其embed_tokens和lm_head的大小与合并后的tokenizer大小一致
4. 在3的模型上预训练

**Comment by ElivisC** [comment]
@airaria 谢谢您！目前已经是按照您提到的1，2两步做过了，关于第3步，我自己的做法是将`run_clm_pt_with_peft.py`中的一个if判断给修改成了我合并后的vocab_size大小，我看代码中自动reize了那个vocab的大小到扩充后词表的大小。到这里我还忽略了什么么？目前训练完成的基座模型对外文的续写能力表现较好，但是对中英文已经出现了混乱，比如：续写的还是以我训练的外文为主

**Comment by airaria** [comment]
首先你可以在你resize模型后，不经过任何训练的情况下测试中英文续写能力，效果应该和resize之前不会有太大变化；
其次，建议在训练时也加入少量中英文，防止模型遗忘中英文知识
