### ISSUE TITLE
生成量化版本模型相关问题，gguf' has no attribute 'should_skip_tensor_TMP'

### ISSUE THREAD

**Issue by Intermatrix** [ymcui/Chinese-LLaMA-Alpaca-2#224]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

精调时使用的基模型是chinese-alpaca-2-7b，将之与精调后得到的sft_lora_model进行了合并，并将合并后的模型放在了sft_v0_combine文件夹中。而后对合并得到的全量模型权重进行convert.py时报错，显示
  File "/root/model/llama.cpp/convert.py", line 975, in convert_model_names
    if gguf.should_skip_tensor_TMP(ARCH, params.n_layer, name_new):
AttributeError: module 'gguf' has no attribute 'should_skip_tensor_TMP'

### 依赖情况（代码类问题务必提供）

# packages in environment at /root/.local/conda/envs/python39:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.aliyun.com/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.aliyun.com/anaconda/pkgs/main
accelerate                0.22.0                   pypi_0    pypi
aiohttp                   3.8.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bitsandbytes              0.41.0                   pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.aliyun.com/anaconda/pkgs/main
brotlipy                  0.7.0           py39h27cfd23_1003    https://mirrors.aliyun.com/anaconda/pkgs/main
bzip2                     1.0.8                h7b6447c_0    https://mirrors.aliyun.com/anaconda/pkgs/main
ca-certificates           2023.05.30           h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
cchardet                  2.1.7                    pypi_0    pypi
certifi                   2023.7.22        py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
cffi                      1.15.1           py39h74dc2b5_0    https://mirrors.aliyun.com/anaconda/pkgs/main
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
cmake                     3.27.2                   pypi_0    pypi
cryptography              41.0.2           py39h774aba0_0    https://mirrors.aliyun.com/anaconda/pkgs/main
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cudatoolkit               11.8.0               h6a678d5_0    https://mirrors.aliyun.com/anaconda/pkgs/main
datasets                  2.14.4                   pypi_0    pypi
deepspeed                 0.10.2                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.3                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0    https://mirrors.aliyun.com/anaconda/pkgs/main
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
gguf                      0.3.1                    pypi_0    pypi
giflib                    5.2.1                h5eee18b_3    https://mirrors.aliyun.com/anaconda/pkgs/main
gmp                       6.2.1                h295c915_3    https://mirrors.aliyun.com/anaconda/pkgs/main
gmpy2                     2.1.2            py39heeb90bb_0    https://mirrors.aliyun.com/anaconda/pkgs/main
gnutls                    3.6.15               he1e5248_0    https://mirrors.aliyun.com/anaconda/pkgs/main
hjson                     3.1.0                    pypi_0    pypi
huggingface-hub           0.16.4                   pypi_0    pypi
idna                      3.4              py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
intel-openmp              2021.4.0          h06a4308_3561    https://mirrors.aliyun.com/anaconda/pkgs/main
jinja2                    3.1.2            py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
jpeg                      9e                   h5eee18b_1    https://mirrors.aliyun.com/anaconda/pkgs/main
lame                      3.100                h7b6447c_0    https://mirrors.aliyun.com/anaconda/pkgs/main
lcms2                     2.12                 h3be6417_0    https://mirrors.aliyun.com/anaconda/pkgs/main
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.aliyun.com/anaconda/pkgs/main
lerc                      3.0                  h295c915_0    https://mirrors.aliyun.com/anaconda/pkgs/main
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.7.2.10                      0    nvidia
libcurand                 10.3.3.141                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
libffi                    3.3                  he6710b0_2    https://mirrors.aliyun.com/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.aliyun.com/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.aliyun.com/anaconda/pkgs/main
libiconv                  1.16                 h7f8727e_2    https://mirrors.aliyun.com/anaconda/pkgs/main
libidn2                   2.3.4                h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
libnpp                    11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libpng                    1.6.39               h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.aliyun.com/anaconda/pkgs/main
libtasn1                  4.19.0               h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
libtiff                   4.5.0                h6a678d5_2    https://mirrors.aliyun.com/anaconda/pkgs/main
libunistring              0.9.10               h27cfd23_0    https://mirrors.aliyun.com/anaconda/pkgs/main
libwebp                   1.2.4                h11a3e52_1    https://mirrors.aliyun.com/anaconda/pkgs/main
libwebp-base              1.2.4                h5eee18b_1    https://mirrors.aliyun.com/anaconda/pkgs/main
lit                       16.0.6                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0    https://mirrors.aliyun.com/anaconda/pkgs/main
markupsafe                2.1.3                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    https://mirrors.aliyun.com/anaconda/pkgs/main
mkl-service               2.4.0            py39h7f8727e_0    https://mirrors.aliyun.com/anaconda/pkgs/main
mkl_fft                   1.3.1            py39hd3c417c_0    https://mirrors.aliyun.com/anaconda/pkgs/main
mkl_random                1.2.2            py39h51133e4_0    https://mirrors.aliyun.com/anaconda/pkgs/main
mpc                       1.1.0                h10f8cd9_1    https://mirrors.aliyun.com/anaconda/pkgs/main
mpfr                      4.0.2                hb69a4c5_1    https://mirrors.aliyun.com/anaconda/pkgs/main
mpmath                    1.3.0            py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.aliyun.com/anaconda/pkgs/main
nettle                    3.7.3                hbbd107a_1    https://mirrors.aliyun.com/anaconda/pkgs/main
networkx                  3.1              py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
ninja                     1.11.1                   pypi_0    pypi
numpy                     1.24.0                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openh264                  2.1.1                h4ff587b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
openssl                   1.1.1v               h7f8727e_0    https://mirrors.aliyun.com/anaconda/pkgs/main
packaging                 23.1                     pypi_0    pypi
pandas                    2.1.0                    pypi_0    pypi
peft                      0.6.0.dev0               pypi_0    pypi
pillow                    9.4.0            py39h6a678d5_0    https://mirrors.aliyun.com/anaconda/pkgs/main
pip                       23.2.1           py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
psutil                    5.9.5                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   13.0.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    https://mirrors.aliyun.com/anaconda/pkgs/main
pydantic                  1.10.12                  pypi_0    pypi
pyopenssl                 23.2.0           py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
pysocks                   1.7.1            py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
python                    3.9.5                h12debd9_4    https://mirrors.aliyun.com/anaconda/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   2.0.1           py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
regex                     2023.8.8                 pypi_0    pypi
requests                  2.31.0           py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
safetensors               0.3.3                    pypi_0    pypi
scipy                     1.11.2                   pypi_0    pypi
sentencepiece             0.1.98                   pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
six                       1.16.0             pyhd3eb1b0_1    https://mirrors.aliyun.com/anaconda/pkgs/main
sqlite                    3.41.2               h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
sympy                     1.12                     pypi_0    pypi
tk                        8.6.12               h1ccaba5_0    https://mirrors.aliyun.com/anaconda/pkgs/main
tokenizers                0.13.3                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchaudio                2.0.2                py39_cu117    pytorch
torchtriton               2.0.0                      py39    pytorch
torchvision               0.15.2               py39_cu117    pytorch
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.31.0                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing_extensions         4.7.1            py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.4                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0    https://mirrors.aliyun.com/anaconda/pkgs/main
xxhash                    3.3.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
yarl                      1.9.2                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
zstd                      1.5.5                hc292b87_0    https://mirrors.aliyun.com/anaconda/pkgs/main

### 运行日志或截图

(python39) root@dl-230826193223xmn-pod-jupyter-7859557b45-xvg7b:~/model/llama.cpp# python convert.py ~/model/llama.cpp/zh-models/7B/sft_v0_combine 
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00001-of-00002.bin
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00001-of-00002.bin
Loading model file /root/model/llama.cpp/zh-models/7B/sft_v0_combine/pytorch_model-00002-of-00002.bin
params = Params(n_vocab=55296, n_embd=4096, n_mult=5504, n_layer=32, n_ctx=4096, n_ff=11008, n_head=32, n_head_kv=32, f_norm_eps=1e-05, f_rope_freq_base=None, f_rope_scale=None, ftype=None, path_model=PosixPath('/root/model/llama.cpp/zh-models/7B/sft_v0_combine'))
Loading vocab file '/root/model/llama.cpp/zh-models/7B/sft_v0_combine/tokenizer.model', type 'spm'
Permuting layer 0
Permuting layer 1
Permuting layer 2
Permuting layer 3
Permuting layer 4
Permuting layer 5
Permuting layer 6
Permuting layer 7
Permuting layer 8
Permuting layer 9
Permuting layer 10
Permuting layer 11
Permuting layer 12
Permuting layer 13
Permuting layer 14
Permuting layer 15
Permuting layer 16
Permuting layer 17
Permuting layer 18
Permuting layer 19
Permuting layer 20
Permuting layer 21
Permuting layer 22
Permuting layer 23
Permuting layer 24
Permuting layer 25
Permuting layer 26
Permuting layer 27
Permuting layer 28
Permuting layer 29
Permuting layer 30
Permuting layer 31
Traceback (most recent call last):
  File "/root/model/llama.cpp/convert.py", line 1173, in <module>
    main()
  File "/root/model/llama.cpp/convert.py", line 1160, in main
    model   = convert_model_names(model, params)
  File "/root/model/llama.cpp/convert.py", line 975, in convert_model_names
    if gguf.should_skip_tensor_TMP(ARCH, params.n_layer, name_new):
AttributeError: module 'gguf' has no attribute 'should_skip_tensor_TMP'

**Comment by ymcui** [comment]
1. SFT之前的模型有没有这个问题？
2. 尝试`git pull`最新的llama.cpp代码，重新编译一下（先`make clean`然后再编译）
3. 尝试更新gguf：`pip install -U gguf`

**Comment by Intermatrix** [comment]
> 

1. ：SFT之前没有此问题
2.&3. ：十分感谢！pull了最新的llama.cpp并且make clean后解决问题了

**Comment by Intermatrix** [comment]
> *

1：SFT之前没有此问题
2.&3. ：十分感谢！pull了最新的llama.cpp并且make clean后解决问题了。
感谢回复！

**Comment by Intermatrix** [comment]
> 1. SFT之前的模型有没有这个问题？
> 2. 尝试`git pull`最新的llama.cpp代码，重新编译一下（先`make clean`然后再编译）
> 3. 尝试更新gguf：`pip install -U gguf`

1：SFT之前没有此问题
2.&3. ：十分感谢！pull了最新的llama.cpp并且make clean后解决问题了。
感谢回复！
