### ISSUE TITLE
用脚本跑OpenAI API Server的时候为什么一直用的是CPU来推理

### ISSUE THREAD

**Issue by lynnroyal** [ymcui/Chinese-LLaMA-Alpaca-2#225]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
使用脚本
python scripts/openai_server_demo/openai_api_server.py --base_model /mnt/data/model/chinese-alpaca-2-7b-hf --tokenizer_path /mnt/data/code/Chinese-LLaMA-Alpaca-2/scripts/tokenizer
成功开启 openapi api server
通过接口调用的时候一直都是在用CPU，没有用到GPU
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
不指定`--gpus`默认加载模型到第0号GPU上，按照你的脚本运行，代码本身没有问题。你可以通过运行`torch.cuda_is_available()`测试一下你的cuda是否可用

**Comment by lynnroyal** [comment]
好的，多谢，好像我装的torch不是GPU版本的

**Comment by lynnroyal** [comment]
这个问题可以close了
