### ISSUE TITLE
精调之后无法输入中文

### ISSUE THREAD

**Issue by altria-zewei-wang** [ymcui/Chinese-LLaMA-Alpaca-2#226]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

指令精调alpaca merge好之后跑inference_hf.py，但是input只能输入英文（会回复中文），输入中文的话会报错。
<img width="1062" alt="截屏2023-08-31 23 49 13" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/89806797/8281189d-606d-4b1c-88f1-2a5c15b5fbcc">

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
不好说，可能是你精调训坏模型了，不知道你训完之后的词表是不是发生什么变化了。
