### ISSUE TITLE
如何增加chinese-llama2-Alpaca-2-16K(7B) 回复答案的长度？

### ISSUE THREAD

**Issue by dkw-wkd** [ymcui/Chinese-LLaMA-Alpaca-2#231]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

chinese-llama2与chatglm对比回答过于简短的问题，能够被解决吗？还有想问下官方作者训练数据的模板能公开吗？以便用户创建提问模板。（上边为chinese-llama2，下边为chatglm2-6b，在本地知识库和embedding模型都相同的情况下，回答的表现）
![4090e170acd6dea715afbc01c18afa2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/4bf08269-6f25-4d59-879c-9ab2fe4c300c) 
![8e1ab427b9fe9079b1024f274126b1d](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/b2a1e34f-86f7-43e0-9c9d-086dbbeb4084)

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by dkw-wkd** [comment]
> 你拿基底模型和chat模型比，有点不讲武德呀。使用**chinese-alpaca-2-7b-16k**得到的回复如下：
> ![image](https://user-images.githubusercontent.com/35353688/265448562-6a06795b-7a05-45a9-a15f-a8e19d7d7393.png)

我用的就是chinese-alpaca-2-7b-16k，你可以截个图给我吗？模型的文件夹

**Comment by dkw-wkd** [comment]
> ![image](https://user-images.githubusercontent.com/35353688/265473272-e5d007c0-75ca-45e4-8948-8eb1a1ede9a3.png)
> 你比较一下[SHA256.md](https://huggingface.co/ziqingyang/chinese-alpaca-2-7b-16k/blob/main/SHA256.md)

我用的模型和你一样，那你输入的模板能截个图吗？

**Comment by dkw-wkd** [comment]
> 参考[wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/inference_with_transformers_zh)

我说的是输入给大模型的文字模板，不是超参数

**Comment by iMountTai** [comment]
我直接跑的transformers inference脚本，代码里面有自带的模板。

**Comment by dkw-wkd** [comment]
![36937bfcf5aece52dcc21db05491828](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/e538d044-54f1-469e-8bb0-48af29edd5a8)
![71ac49ecfa93dd00fac9a7807812b73](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/717254c9-d616-474e-8eed-640314e0ec42)

上图为chinese-llama2-alpaca-2-16k的回答，下图为chatglm2-6b的回答，模板相同的情况下，chatglm2-6b回答的更丰富，这个问题有办法解决吗？

**Comment by ymcui** [comment]
`chinese-llama2-alpaca-2-16k` 这不是一个正确的模型名，你指的是Chinese-Alpaca-2-?B-16K吧。是否使用了我们提供的指令模板？形如：
```
[INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

$FIRST_INSTRUCTION [/INST]
```

**Comment by dkw-wkd** [comment]
> `chinese-llama2-alpaca-2-16k` 这不是一个正确的模型名，你指的是Chinese-Alpaca-2-?B-16K吧。是否使用了我们提供的指令模板？形如：
> 
> ```
> [INST] <<SYS>>
> You are a helpful assistant. 你是一个乐于助人的助手。
> <</SYS>>
> 
> $FIRST_INSTRUCTION [/INST]
> ```

在这个模板里如何加入通过知识库提取出的已知信息呢？
比如：
南阳市义务教育阶段学校暑假时间从7月3日起至8月31日结束，幼儿园参照执行。普通高中从7月14日起至8月31日结束。各中小学校（幼儿园）9月1日正式开学。驻马店市义务教育阶段学校及幼儿园原则上7月5日暑假正式开始，8月31日报到，9月1日(星期五）正式上课。普通高中7月15日暑假开始，8月31日报到，9月1日(星期五）正式上课。——安徽合肥义务教育学校：放假7月1日（周六）；报到8月31日（周四）；正式上课9月1日（周五）；幼儿园暑假时间参照义务教育学校执行。普通高中学校：放假7月8日（周六）；高一年级、高二年级8月31日（周四）报到9月1日（周五）正式上课；高三年级8月24日（周四）正式上课；中专学校暑假时间参照普通高中执行。
6月20日下午，由合肥市自贸委主办的“合肥自贸创新荟?制度创新专题培训会暨合肥片区研究院签约仪式”在合肥隆重举行，安徽省自贸办制度创新处处长后其洁、合肥片区管委会常务副主任刘梦龙、合肥学院党委委员王晓峰，合肥片区建设工作领导小组成员单位相关负责同志，以及片区重点产业龙头企业负责人约100人出席会议。6月20日下午，由合肥市自贸委主办的“合肥自贸创新荟?制度创新专题培训会暨合肥片区研究院签约仪式”在合肥隆重举行，安徽省自贸办制度创新处处长后其洁、合肥片区管委会常务副主任刘梦龙、合肥学院党委委员王晓峰，合肥片区建设工作领导小组成员单位相关负责同志，以及片区重点产业龙头企业负责人约100人出席会议。
安徽一批交通项目传来新消息炎炎夏日，骄阳似火，正值一年夏忙时，全省各地交通项目建设现场呈现出一片如火如荼的忙碌场景！各地交通运输部门纷纷开足马力，奋战当“夏”！合肥近日，引江济淮工程引江济巢段03标沐集大桥主桥拱肋低位拼装圆满完成，为主桥拱肋提升收官奠定了坚实的基础。据悉，新建沐集大桥主桥为单跨170米下承式钢箱系杆拱大跨度钢结构桥梁，桥宽24.1米。马鞍山市截至6月底，马鞍山市交通建设累计完成投资25.31亿元，完成年度计划的54.64%，S205围乌路一期工程、S442改建工程建成通车，交通基础设施建设取得新进展。今年以来，马鞍山市持续推进宁马高速“四改八”改扩建工程、宁和高速安徽段、S205围乌路改建工程等在建重点项目建设；
15个新一线城市，长三角地区占了5席，分别是杭州、苏州、南京、宁波和合肥。跟2013年比，多了三席（苏州、宁波和合肥），由此不难看出，长三角一体化过程中，区域发展对城市的带动。十多年前，作为省会的合肥，存在感并不强。这些年，除了长三角一体带来的发展红利外，合肥自身也在埋头苦干，押注京东方、抄底蔚来、投资长鑫存储，已经成为合肥“最牛风投城市”的重要注脚。而依托本地多所高等学府和各级科研机构，合肥的科技创新能力进一步加强，成为对外展示的重要能力。合肥。图片来源：视觉中国合肥。图片来源：视觉中国城市发展得好不好，人口是一个关键数据。2022年底，合肥人口增加了16.9万人，仅次于长沙和杭州。下一个十年，谁会继续霸榜，谁又会冲入一线，时间会给出答案。
长三角地区，表现不错。15个新一线城市，长三角地区占了5席，分别是杭州、苏州、南京、宁波和合肥。跟2013年比，多了三席（苏州、宁波和合肥），由此不难看出，长三角一体化过程中，区域发展对城市的带动。十多年前，作为省会的合肥，存在感并不强。这些年，除了长三角一体带来的发展红利外，合肥自身也在埋头苦干，押注京东方、抄底蔚来、投资长鑫存储，已经成为合肥“最牛风投城市”的重要注脚。而依托本地多所高等学府和各级科研机构，合肥的科技创新能力进一步加强，成为对外展示的重要能力。合肥。图片来源：视觉中国合肥。图片来源：视觉中国城市发展得好不好，人口是一个关键数据。2022年底，合肥人口增加了16.9万人，仅次于长沙和杭州。

如何把上面这段已知文字 一起输入给模型 作为限定 获取更丰富的答案？

**Comment by dkw-wkd** [comment]
> `chinese-llama2-alpaca-2-16k` 这不是一个正确的模型名，你指的是Chinese-Alpaca-2-?B-16K吧。是否使用了我们提供的指令模板？形如：
> 
> ```
> [INST] <<SYS>>
> You are a helpful assistant. 你是一个乐于助人的助手。
> <</SYS>>
> 
> $FIRST_INSTRUCTION [/INST]
> ```

使用的模型是这个chinese-alpaca-2-7b-16k，看了你们官方文档，使用这个模型可以更好的对话

**Comment by ymcui** [comment]
具体效果我不做过多讨论，属于prompt工程。这里主要是使用正确性的问题。
```
[INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

$FIRST_INSTRUCTION [/INST]
```
这里只有一个变量，就是$FIRST_INSTRUCTION，也就是你的用户输入，至于你要输入什么（例如问题、背景）可自行决定。比如`$FIRST_INSTRUCTION`的内容是`请你介绍一下中国的首都`，那么你需要给模型的输入就是（这里隐去了BOS, EOS符号）
```
[INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

请你介绍一下中国的首都 [/INST]
```

不同模型都有特定的指令模板，一般来说不能混着用。

**Comment by dkw-wkd** [comment]
> 

![19e5b0067ea3c7948cffa51732e83ab](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/81e0518c-cba6-49ab-9197-1d731175c42f)
用了你刚刚给的模板后的效果 看起来回答的更简略了，是模型层的原因吗

**Comment by ymcui** [comment]
你用的是我们的inference_hf.py脚本吗？如果不是的话就不清楚了，建议还是用我们写好的inference_hf.py测试。

**Comment by dkw-wkd** [comment]
> 你用的是我们的inference_hf.py脚本吗？如果不是的话就不清楚了，建议还是用我们写好的inference_hf.py测试。 特定案例的问题我们无法给出明确回答，只能是引导你用**正确的方式**使用我们的模型。

用了你们的模型作推理，但是基于langchain框架建立了本地知识库

**Comment by ymcui** [comment]
参考相关示例代码吧。
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/langchain_zh

**Comment by dkw-wkd** [comment]
> 参考相关示例代码吧。 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/langchain_zh

还有个问题，为啥问你们训练的chinese-llama2模型，是基于什么大语言模型开发的，他会回答我是基于chatgpt啊？如下所示
![f8cdcdc145d142eba5b49daa5d11e90](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/8011c2a7-89c2-4bd7-b5a0-b5deb03e64e3)
![cee0aa782bff91c9d10feecf4e0b8e1](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/75665807/345fb588-9436-44e6-9d75-20c78329dc10)

**Comment by ymcui** [comment]
> > 参考相关示例代码吧。 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/langchain_zh
> 
> 还有个问题，为啥问你们训练的chinese-llama2模型，是基于什么大语言模型开发的，他会回答我是基于chatgpt啊？如下所示 ![f8cdcdc145d142eba5b49daa5d11e90](https://user-images.githubusercontent.com/75665807/265612948-8011c2a7-89c2-4bd7-b5a0-b5deb03e64e3.png) ![cee0aa782bff91c9d10feecf4e0b8e1](https://user-images.githubusercontent.com/75665807/265612958-345fb588-9436-44e6-9d75-20c78329dc10.png)

因为我们并没有加入身份数据。不必纠结这个。

**Comment by dkw-wkd** [comment]
> > > 参考相关示例代码吧。 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/langchain_zh
> > 
> > 
> > 还有个问题，为啥问你们训练的chinese-llama2模型，是基于什么大语言模型开发的，他会回答我是基于chatgpt啊？如下所示 ![f8cdcdc145d142eba5b49daa5d11e90](https://user-images.githubusercontent.com/75665807/265612948-8011c2a7-89c2-4bd7-b5a0-b5deb03e64e3.png) ![cee0aa782bff91c9d10feecf4e0b8e1](https://user-images.githubusercontent.com/75665807/265612958-345fb588-9436-44e6-9d75-20c78329dc10.png)
> 
> 因为我们并没有加入身份数据。不必纠结这个。

但是问原生llama模型的话 它肯定会回答 自己是基于llama模型开发的吧？

**Comment by ymcui** [comment]
模型输出什么很大程度上取决于用什么样的训练数据。至于你说原版llama会不会这样，建议你自行尝试。

**Comment by dkw-wkd** [comment]
> 你拿基底模型和chat模型比，有点不讲武德呀。使用**chinese-alpaca-2-7b-16k**得到的回复如下： ![image](https://user-images.githubusercontent.com/35353688/265448562-6a06795b-7a05-45a9-a15f-a8e19d7d7393.png)

我用的就是chinese-alpaca-2-7b-16k模型 只是加入了本地知识库检索出来的已知信息，回答就被压缩了。
