### ISSUE TITLE
chinese-alpaca-13b-16k的ceval和cmmlu分数较chinese-alpaca-13b低很多

### ISSUE THREAD

**Issue by IWANNAGO** [ymcui/Chinese-LLaMA-Alpaca-2#236]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ziqingyang/chinese-alpaca-2-13b-16k")
model = AutoModelForCausalLM.from_pretrained("ziqingyang/chinese-alpaca-2-13b-16k")
```
从huggingface上直接下载的模型，然后测试ceval和cmmlu分数，0.32和0.34对比chinese-alpaca-2-13b的分数为0.42和0.43，请问一下作者是否测试过16k模型的ceval和cmmlu，如果测试过分数是怎样的，以及生成的参数有需要较大的改动吗？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by IWANNAGO** [comment]
> 贴一下你的ceval运行参数？
python eval.py \
    --model_path ${model_path} \
    --few_shot False \
    --with_prompt True \
    --constrained_decoding True \
    --output_dir ${output_path}
其余都是默认参数

**Comment by airaria** [comment]
> python eval.py 
> --model_path ${model_path} 
> --few_shot False 
> --with_prompt True 
> --constrained_decoding True 
> --output_dir ${output_path}
> 其余都是默认参数

不需要改动代码，可以直接使用本项目内的eval.py。transformers版本是否较旧？因为较老的transformers版本不支持PI上下文拓展，建议更新一下transformers版本。

**Comment by zeng9t** [comment]
chinese-alpaca-2-13b-16k测试下来会有不少输出末尾重复的现象，比如：

根据已知信息无法回答该问题。请提供更多相关信息，以便能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够能够

**Comment by IWANNAGO** [comment]
> transformers

应该是版本太低，transformer改为4.31版本后模型效果正常

**Comment by IWANNAGO** [comment]
> 

应该是transformers的版本太低了，改为4.31应该可以
