### ISSUE TITLE
关于带有长上下文的sft训练和长上下文sft的问题

### ISSUE THREAD

**Issue by WeixuanXiong** [ymcui/Chinese-LLaMA-Alpaca-2#237]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```

```
您好，感谢分享！想咨询一下您一些模型训练的问题。

请问您训练Chinese-Alpaca-2-16K是否按照Chinese-LLama-2 -> Chinese-Alpaca-2 -> Chinese-Alpaca-2-16k这个流程进行呢？5M Instruction Fine-tuning的过程中长上下文数据和其他数据的分布情况。 Long Context FT是怎么进行的呢。

我们也进行了一些长上下文方面的实验，但NTK的效果好于PI，请问是出于什么原因导致Chinese-Alpaca-2-16K采用PI进行长上下文训练呢？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
```
请问您训练Chinese-Alpaca-2-16K是否按照Chinese-LLama-2 -> Chinese-Alpaca-2 -> Chinese-Alpaca-2-16k这个流程进行呢？
```
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2?tab=readme-ov-file#模型简介 
这里的模型关系图应该比较清晰了。Alpaca-2-16K是直接在Alpaca-2的基础上增量训练得到的。

```
5M Instruction Fine-tuning的过程中长上下文数据和其他数据的分布情况。
```
5M SFT数据暂无细节要公开，感兴趣的话可以看我们的技术报告，里面有一些粗粒度的说明。

```
Long Context FT是怎么进行的呢。
```
参考meta的论文：https://arxiv.org/abs/2306.15595

```
我们也进行了一些长上下文方面的实验，但NTK的效果好于PI，请问是出于什么原因导致Chinese-Alpaca-2-16K采用PI进行长上下文训练呢？
```
同上，目前的版本只是一个复现PI增量训练的基础方案，并没有其他特殊考虑。至于你提到的`NTK好于PI`也不是不可能。

**Comment by zeng9t** [comment]
请问下16K模型训练的时候，max_seq_length设置的是多少？

**Comment by Jxh99** [comment]
您好，请问如果我们想在alpaca2-16k的基础上，用自己的长文本数据再次进行sft，还需要使用位置插值的方法吗？还是正常sft就可以？

**Comment by yajingsunno** [comment]
> 您好，请问如果我们想在alpaca2-16k的基础上，用自己的长文本数据再次进行sft，还需要使用位置插值的方法吗？还是正常sft就可以？

我也有这个疑问。在alpaca2-16K的基础上微调，我目前设置max-length为4096，加了ntk，sft进行微调，模型一直在重复生成，测试也无法记住训练语料

**Comment by airaria** [comment]
> 您好，请问如果我们想在alpaca2-16k的基础上，用自己的长文本数据再次进行sft，还需要使用位置插值的方法吗？还是正常sft就可以？

直接用transformers(>=4.31.0)加载alpaca2-16k，默认会进行位置插值，不用也不要做其他改动

**Comment by airaria** [comment]
> > 您好，请问如果我们想在alpaca2-16k的基础上，用自己的长文本数据再次进行sft，还需要使用位置插值的方法吗？还是正常sft就可以？
> 
> 我也有这个疑问。在alpaca2-16K的基础上微调，我目前设置max-length为4096，加了ntk，sft进行微调，模型一直在重复生成，测试也无法记住训练语料

请问是如何添加ntk的？目前的transformers的官方代码中NTK与PI不能同时使用，所以可能因为这个原因导致训练效果不好
