### ISSUE TITLE
wiki中的pt_scripts_zh的load_in_kbits 參數不能使用

### ISSUE THREAD

**Issue by ian08005454** [ymcui/Chinese-LLaMA-Alpaca-2#239]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
torchrun --nnodes 1 --nproc_per_node 4 run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --do_train \
    --seed 69 \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 40 \
    --block_size ${block_size} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --modules_to_save ${modules_to_save} \
    --torch_dtype float16\
    # --load_in_kbits 8 

```
--load_in_kbits 8 參數無法使用，錯誤訊息使找不到這個參數，已經都pull最新版的了
如果要int8 除了這個參數還有其他方法嗎?

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
因为 #229 还没合并

**Comment by ymcui** [comment]
相关PR已合并。可以拉取最新代码再尝试。

**Comment by ssm0808** [comment]
我重新拉了代码，运行精调脚本有这样的报错“ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft.utils.other'”，我的peft版本是0.3.0.dev0，请问是需要更新最新的peft版本吗？

**Comment by airaria** [comment]
> 我重新拉了代码，运行精调脚本有这样的报错“ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft.utils.other'”，我的peft版本是0.3.0.dev0，请问是需要更新最新的peft版本吗？

scripts/training/peft和run_clm_pt_with_peft.py在同一个目录吗？需要使用我们提供的这个peft版本

**Comment by ssm0808** [comment]
> > 我重新拉了代码，运行精调脚本有这样的报错“ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft.utils.other'”，我的peft版本是0.3.0.dev0，请问是需要更新最新的peft版本吗？
> 
> scripts/training/peft和run_clm_pt_with_peft.py在同一个目录吗？需要使用我们提供的这个peft版本

scripts/training/peft和run_clm_pt_with_peft.py在同一个目录，而且使用13e53fc这个版本的peft。

**Comment by Double-bear** [comment]
> > > 我重新拉了代码，运行精调脚本有这样的报错“ImportError: cannot import name 'prepare_model_for_int8_training' from 'peft.utils.other'”，我的peft版本是0.3.0.dev0，请问是需要更新最新的peft版本吗？
> > 
> > 
> > scripts/training/peft和run_clm_pt_with_peft.py在同一个目录吗？需要使用我们提供的这个peft版本
> 
> scripts/training/peft和run_clm_pt_with_peft.py在同一个目录，而且使用13e53fc这个版本的peft。

+1 我也出现了这个问题

**Comment by iMountTai** [comment]
代码中使用的是自定义的`prepare_model_for_kbit_training`，没有'prepare_model_for_int8_training'这个方法呀？

**Comment by ssm0808** [comment]
> 代码中使用的是自定义的`prepare_model_for_kbit_training`，没有'prepare_model_for_int8_training'这个方法呀？

![20230906-140703(WeLinkPC)](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/15920855/95c3cc2c-723e-435c-b828-ef57e2d5a4b4)

**Comment by ssm0808** [comment]
![20230906-140703(WeLinkPC)](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/15920855/b6835fd2-6cbd-4bb4-a26d-62ecbafcabae)
![20230906-141642(WeLinkPC)](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/15920855/1bacafad-fa2c-4e85-bd78-c442fff5c751)
把这两个地方的prepare_model_for_int8_training删掉就可以了。

**Comment by iMountTai** [comment]
谢谢，稍后我们修复该问题。

**Comment by ian08005454** [comment]
load_in_kbits的參數已可以用了謝謝大家的協助。
但我發現load_in_kbits = 8的時候顯示卡記憶體用量與儲存的模型大小都沒甚麼改變，照理來說不是應該要變小一半嗎?
然後還想藉此詢問一下gradient_accumulation_steps 應該是不會增加VRAM的使用量的吧?
