### ISSUE TITLE
想预训练自己的chinese-llama，需要执行Pretrain stage 1吗

### ISSUE THREAD

**Issue by MonetCH** [ymcui/Chinese-LLaMA-Alpaca-2#242]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
您好，

我目前有自行搜集了一些资料集，想进行meta llama的pretrain，建立如您一般的chinese llama，

准备了3.5G data，进行1000steps训练，loss降至2.5后就不再下降。

inference出的结果也不尽人意，如乱码一般(見運行日志)。

想请问是否是在pretrain方面出问题？是否需要执行在第一版chinese-llama-alpaca提到的Pre-training Stage 1?

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/39763018/64f5733c-b2e5-498a-9360-20c6985c9a15)

**Comment by ymcui** [comment]
1. 不需要进行stage 1，效果差和这个没有关系。
2. 不太清楚你用的inference脚本是什么。llama只适合进行续写，不适合用来交互。
3. loss降低到一定程度之后的确就不会有太显著的下降了，但这并不代表模型效果不会进一步提升。

**Comment by MonetCH** [comment]
谢谢您的解答，第一点和第三点我了解了，
关于第二点，我是要进行续写，使用的脚本是
python scripts/inference/inference_hf.py \
    --base_model path_to_original_llama_2_hf_dir \
    --lora_model path_to_chinese_llama2 \
    --with_prompt 
那针对回答乱码的问题，刚刚忘记提到说，我有在自行使用sentencepiece建立新的tokenizer，也有执行您所提供的merge方法，请问这是否也会造成影响呢?

**Comment by ymcui** [comment]
1. llama模型不能用`--with_prompt`，这个选项是给Alpaca设置的。
2. 你是说你自己扩充了新词表是吗？那有可能会导致训练不充分。我不是很清楚你的使用场景，通常情况下没有必要继续扩充词表了。

**Comment by MonetCH** [comment]
您好，感謝您的回答
1. 了解，我知道了，謝謝！但經過剛才實測仍是亂碼
2. 是的，我是想尝试看看让模型回答繁体中文，因为目前仍会简繁夹杂，我想让模型能够只回答繁体。还是说也不需要我自己建立新的tokenizer，只要使用繁体资料集即可？

**Comment by ymcui** [comment]
我是不建议扩词表的，必要性不是很强，因为繁体中文和简体中文之间有很多token是共享的。
你需要做的是用繁体中文数据让模型学习繁体中文语境下的pattern，这一点并不一定需要扩充繁体中文词表。
至于你提到的简繁夹杂的问题，可能还是因为你扩充词表之后新token训练不充分，导致模型并没有训练到位导致的。

**Comment by MonetCH** [comment]
好的，我了解了，感谢您的回答，我会再继续努力，谢谢您开源了这么棒的专案！

**Comment by MonetCH** [comment]
不好意思，能再请教您一下，您当初用20M资料集训练Chinese-llama时，大概训练了多少个steps呢？我改用您的tokenizer做Pretrain，我目前跑了10000steps(1.68epochs)，效果仍跟我在上面放的结果一样

模型配置:
base-model : meta-llama2
tokenizer: ziqingyang/chinese-llama-2-7b

**Comment by airaria** [comment]
> 不好意思，能再请教您一下，您当初用20M资料集训练Chinese-llama时，大概训练了多少个steps呢？我改用您的tokenizer做Pretrain，我目前跑了10000steps(1.68epochs)，效果仍跟我在上面放的结果一样
> 
> 模型配置: base-model : meta-llama2 tokenizer: ziqingyang/chinese-llama-2-7b

如果loss较高，可以增加训练数据训练继续观察；
如果loss确实比较低了，建议从数据角度检查问题。比如确认是否使用了正确的tokenizer、生成的data cache中的数据的正确性，以及是否删除了由旧数据生成的cache（否则模型会加载旧的cache）？
