### ISSUE TITLE
quantize.exe执行没有任何反应，也不报错

### ISSUE THREAD

**Issue by kaixuanjames** [ymcui/Chinese-LLaMA-Alpaca-2#248]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Windows

### 详细描述问题

量化FP16模型时，quantize.exe运行没有任何反应
![1dfe3070135fd84a50b01d6e10803fc](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/133489631/6ca42d11-52eb-4003-88f1-21c5b2f2ae17)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
你可能要先看一下`quantize.exe`能否正确启动。
linux/macOS下只运行`quantize`会输出帮助信息，如下所示。
```bash
> ./quantize
usage: ./quantize [--help] [--allow-requantize] [--leave-output-tensor] model-f32.gguf [model-quant.gguf] type [nthreads]

  --allow-requantize: Allows requantizing tensors that have already been quantized. Warning: This can severely reduce quality compared to quantizing from 16bit or 32bit
  --leave-output-tensor: Will leave output.weight un(re)quantized. Increases model size but may also increase quality, especially when requantizing

Allowed quantization types:
   2  or  Q4_0   :  3.56G, +0.2166 ppl @ LLaMA-v1-7B
   3  or  Q4_1   :  3.90G, +0.1585 ppl @ LLaMA-v1-7B
   8  or  Q5_0   :  4.33G, +0.0683 ppl @ LLaMA-v1-7B
   9  or  Q5_1   :  4.70G, +0.0349 ppl @ LLaMA-v1-7B
  10  or  Q2_K   :  2.63G, +0.6717 ppl @ LLaMA-v1-7B
  12  or  Q3_K   : alias for Q3_K_M
  11  or  Q3_K_S :  2.75G, +0.5551 ppl @ LLaMA-v1-7B
  12  or  Q3_K_M :  3.07G, +0.2496 ppl @ LLaMA-v1-7B
  13  or  Q3_K_L :  3.35G, +0.1764 ppl @ LLaMA-v1-7B
  15  or  Q4_K   : alias for Q4_K_M
  14  or  Q4_K_S :  3.59G, +0.0992 ppl @ LLaMA-v1-7B
  15  or  Q4_K_M :  3.80G, +0.0532 ppl @ LLaMA-v1-7B
  17  or  Q5_K   : alias for Q5_K_M
  16  or  Q5_K_S :  4.33G, +0.0400 ppl @ LLaMA-v1-7B
  17  or  Q5_K_M :  4.45G, +0.0122 ppl @ LLaMA-v1-7B
  18  or  Q6_K   :  5.15G, -0.0008 ppl @ LLaMA-v1-7B
   7  or  Q8_0   :  6.70G, +0.0004 ppl @ LLaMA-v1-7B
   1  or  F16    : 13.00G              @ 7B
   0  or  F32    : 26.00G              @ 7B
          COPY   : only copy tensors, no quantizing
```

如果这样也没有任何输出的话就得看一下编译是否正确，或者换成WSL/git bash等方案运行程序。

**Comment by kaixuanjames** [comment]
> 你可能要先看一下`quantize.exe`能否正确启动。 linux/macOS下只运行`quantize`会输出帮助信息，如下所示。
> 
> ```shell
> > ./quantize
> usage: ./quantize [--help] [--allow-requantize] [--leave-output-tensor] model-f32.gguf [model-quant.gguf] type [nthreads]
> 
>   --allow-requantize: Allows requantizing tensors that have already been quantized. Warning: This can severely reduce quality compared to quantizing from 16bit or 32bit
>   --leave-output-tensor: Will leave output.weight un(re)quantized. Increases model size but may also increase quality, especially when requantizing
> 
> Allowed quantization types:
>    2  or  Q4_0   :  3.56G, +0.2166 ppl @ LLaMA-v1-7B
>    3  or  Q4_1   :  3.90G, +0.1585 ppl @ LLaMA-v1-7B
>    8  or  Q5_0   :  4.33G, +0.0683 ppl @ LLaMA-v1-7B
>    9  or  Q5_1   :  4.70G, +0.0349 ppl @ LLaMA-v1-7B
>   10  or  Q2_K   :  2.63G, +0.6717 ppl @ LLaMA-v1-7B
>   12  or  Q3_K   : alias for Q3_K_M
>   11  or  Q3_K_S :  2.75G, +0.5551 ppl @ LLaMA-v1-7B
>   12  or  Q3_K_M :  3.07G, +0.2496 ppl @ LLaMA-v1-7B
>   13  or  Q3_K_L :  3.35G, +0.1764 ppl @ LLaMA-v1-7B
>   15  or  Q4_K   : alias for Q4_K_M
>   14  or  Q4_K_S :  3.59G, +0.0992 ppl @ LLaMA-v1-7B
>   15  or  Q4_K_M :  3.80G, +0.0532 ppl @ LLaMA-v1-7B
>   17  or  Q5_K   : alias for Q5_K_M
>   16  or  Q5_K_S :  4.33G, +0.0400 ppl @ LLaMA-v1-7B
>   17  or  Q5_K_M :  4.45G, +0.0122 ppl @ LLaMA-v1-7B
>   18  or  Q6_K   :  5.15G, -0.0008 ppl @ LLaMA-v1-7B
>    7  or  Q8_0   :  6.70G, +0.0004 ppl @ LLaMA-v1-7B
>    1  or  F16    : 13.00G              @ 7B
>    0  or  F32    : 26.00G              @ 7B
>           COPY   : only copy tensors, no quantizing
> ```
> 
> 如果这样也没有任何输出的话就得看一下编译是否正确，或者换成WSL/git bash等方案运行程序w

> 你可能要先看一下`quantize.exe`能否正确启动。 linux/macOS下只运行`quantize`会输出帮助信息，如下所示。
> 
> ```shell
> > ./quantize
> usage: ./quantize [--help] [--allow-requantize] [--leave-output-tensor] model-f32.gguf [model-quant.gguf] type [nthreads]
> 
>   --allow-requantize: Allows requantizing tensors that have already been quantized. Warning: This can severely reduce quality compared to quantizing from 16bit or 32bit
>   --leave-output-tensor: Will leave output.weight un(re)quantized. Increases model size but may also increase quality, especially when requantizing
> 
> Allowed quantization types:
>    2  or  Q4_0   :  3.56G, +0.2166 ppl @ LLaMA-v1-7B
>    3  or  Q4_1   :  3.90G, +0.1585 ppl @ LLaMA-v1-7B
>    8  or  Q5_0   :  4.33G, +0.0683 ppl @ LLaMA-v1-7B
>    9  or  Q5_1   :  4.70G, +0.0349 ppl @ LLaMA-v1-7B
>   10  or  Q2_K   :  2.63G, +0.6717 ppl @ LLaMA-v1-7B
>   12  or  Q3_K   : alias for Q3_K_M
>   11  or  Q3_K_S :  2.75G, +0.5551 ppl @ LLaMA-v1-7B
>   12  or  Q3_K_M :  3.07G, +0.2496 ppl @ LLaMA-v1-7B
>   13  or  Q3_K_L :  3.35G, +0.1764 ppl @ LLaMA-v1-7B
>   15  or  Q4_K   : alias for Q4_K_M
>   14  or  Q4_K_S :  3.59G, +0.0992 ppl @ LLaMA-v1-7B
>   15  or  Q4_K_M :  3.80G, +0.0532 ppl @ LLaMA-v1-7B
>   17  or  Q5_K   : alias for Q5_K_M
>   16  or  Q5_K_S :  4.33G, +0.0400 ppl @ LLaMA-v1-7B
>   17  or  Q5_K_M :  4.45G, +0.0122 ppl @ LLaMA-v1-7B
>   18  or  Q6_K   :  5.15G, -0.0008 ppl @ LLaMA-v1-7B
>    7  or  Q8_0   :  6.70G, +0.0004 ppl @ LLaMA-v1-7B
>    1  or  F16    : 13.00G              @ 7B
>    0  or  F32    : 26.00G              @ 7B
>           COPY   : only copy tensors, no quantizing
> ```
> 
> 如果这样也没有任何输出的话就得看一下编译是否正确，或者换成WSL/git bash等方案运行程序。

我的系统是win10系统，利用cmake生成的这些可执行文件，如下图红框中的命令，但是生成的这些exe好像都是同样的问题，运行不起来
![764f5086542374e565a5ce0be566c71](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/133489631/0374f364-cf0c-472b-90f7-19b9b607f52d)

**Comment by kaixuanjames** [comment]
> 你可能要先看一下`quantize.exe`能否正确启动。 linux/macOS下只运行`quantize`会输出帮助信息，如下所示。
> 
> ```shell
> > ./quantize
> usage: ./quantize [--help] [--allow-requantize] [--leave-output-tensor] model-f32.gguf [model-quant.gguf] type [nthreads]
> 
>   --allow-requantize: Allows requantizing tensors that have already been quantized. Warning: This can severely reduce quality compared to quantizing from 16bit or 32bit
>   --leave-output-tensor: Will leave output.weight un(re)quantized. Increases model size but may also increase quality, especially when requantizing
> 
> Allowed quantization types:
>    2  or  Q4_0   :  3.56G, +0.2166 ppl @ LLaMA-v1-7B
>    3  or  Q4_1   :  3.90G, +0.1585 ppl @ LLaMA-v1-7B
>    8  or  Q5_0   :  4.33G, +0.0683 ppl @ LLaMA-v1-7B
>    9  or  Q5_1   :  4.70G, +0.0349 ppl @ LLaMA-v1-7B
>   10  or  Q2_K   :  2.63G, +0.6717 ppl @ LLaMA-v1-7B
>   12  or  Q3_K   : alias for Q3_K_M
>   11  or  Q3_K_S :  2.75G, +0.5551 ppl @ LLaMA-v1-7B
>   12  or  Q3_K_M :  3.07G, +0.2496 ppl @ LLaMA-v1-7B
>   13  or  Q3_K_L :  3.35G, +0.1764 ppl @ LLaMA-v1-7B
>   15  or  Q4_K   : alias for Q4_K_M
>   14  or  Q4_K_S :  3.59G, +0.0992 ppl @ LLaMA-v1-7B
>   15  or  Q4_K_M :  3.80G, +0.0532 ppl @ LLaMA-v1-7B
>   17  or  Q5_K   : alias for Q5_K_M
>   16  or  Q5_K_S :  4.33G, +0.0400 ppl @ LLaMA-v1-7B
>   17  or  Q5_K_M :  4.45G, +0.0122 ppl @ LLaMA-v1-7B
>   18  or  Q6_K   :  5.15G, -0.0008 ppl @ LLaMA-v1-7B
>    7  or  Q8_0   :  6.70G, +0.0004 ppl @ LLaMA-v1-7B
>    1  or  F16    : 13.00G              @ 7B
>    0  or  F32    : 26.00G              @ 7B
>           COPY   : only copy tensors, no quantizing
> ```
> 
> 如果这样也没有任何输出的话就得看一下编译是否正确，或者换成WSL/git bash等方案运行程序。

请问quantize在win10下运行需要哪些环境呢

**Comment by kaixuanjames** [comment]
> 你可能要先看一下`quantize.exe`能否正确启动。 linux/macOS下只运行`quantize`会输出帮助信息，如下所示。
> 
> ```shell
> > ./quantize
> usage: ./quantize [--help] [--allow-requantize] [--leave-output-tensor] model-f32.gguf [model-quant.gguf] type [nthreads]
> 
>   --allow-requantize: Allows requantizing tensors that have already been quantized. Warning: This can severely reduce quality compared to quantizing from 16bit or 32bit
>   --leave-output-tensor: Will leave output.weight un(re)quantized. Increases model size but may also increase quality, especially when requantizing
> 
> Allowed quantization types:
>    2  or  Q4_0   :  3.56G, +0.2166 ppl @ LLaMA-v1-7B
>    3  or  Q4_1   :  3.90G, +0.1585 ppl @ LLaMA-v1-7B
>    8  or  Q5_0   :  4.33G, +0.0683 ppl @ LLaMA-v1-7B
>    9  or  Q5_1   :  4.70G, +0.0349 ppl @ LLaMA-v1-7B
>   10  or  Q2_K   :  2.63G, +0.6717 ppl @ LLaMA-v1-7B
>   12  or  Q3_K   : alias for Q3_K_M
>   11  or  Q3_K_S :  2.75G, +0.5551 ppl @ LLaMA-v1-7B
>   12  or  Q3_K_M :  3.07G, +0.2496 ppl @ LLaMA-v1-7B
>   13  or  Q3_K_L :  3.35G, +0.1764 ppl @ LLaMA-v1-7B
>   15  or  Q4_K   : alias for Q4_K_M
>   14  or  Q4_K_S :  3.59G, +0.0992 ppl @ LLaMA-v1-7B
>   15  or  Q4_K_M :  3.80G, +0.0532 ppl @ LLaMA-v1-7B
>   17  or  Q5_K   : alias for Q5_K_M
>   16  or  Q5_K_S :  4.33G, +0.0400 ppl @ LLaMA-v1-7B
>   17  or  Q5_K_M :  4.45G, +0.0122 ppl @ LLaMA-v1-7B
>   18  or  Q6_K   :  5.15G, -0.0008 ppl @ LLaMA-v1-7B
>    7  or  Q8_0   :  6.70G, +0.0004 ppl @ LLaMA-v1-7B
>    1  or  F16    : 13.00G              @ 7B
>    0  or  F32    : 26.00G              @ 7B
>           COPY   : only copy tensors, no quantizing
> ```
> 
> 如果这样也没有任何输出的话就得看一下编译是否正确，或者换成WSL/git bash等方案运行程序。

我是在win10系统下运行的，不知道为什么啥反应都没有

**Comment by ymcui** [comment]
不太清楚windows。建议你用WSL或者git bash环境安装。具体安装方法自己网上检索一下吧。
