### ISSUE TITLE
使用廣東話數據集微調後對話異常

### ISSUE THREAD

**Issue by Naozumi520** [ymcui/Chinese-LLaMA-Alpaca-2#250]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

macOS

### 详细描述问题

```
naozumi@1-64-20-077 Chinese-LLaMA-Alpaca-2-main-3 % SYSTEM="You are a helpful and stupid assistant. 你是一个乐于助人的助手。"         
FIRST_INSTRUCTION=你好                                                   
    
./main -m /Users/naozumi/Downloads/merge_mix/ggml-model-f16-q4_k.gguf  \
--color -i -c 4096 -t 8 --temp 0.2 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 \
--in-prefix-bos --in-prefix ' [INST] ' --in-suffix ' [/INST]' -p \
"[INST] <<SYS>>
$SYSTEM<</SYS>>

$FIRST_INSTRUCTION [/INST]"
```

<img width="1334" alt="Screenshot 2023-09-06 at 9 27 38 PM" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/52615455/8fb9340c-a1c9-405a-af6f-3c9de6224541">

( 煮貓 ?

1. 模型初次沒有回答“你好”的問題, 產生了一個奇怪的角色背景和隨機答案
2. 當詢問模型“如何煮雞蛋”時，模型的答案答非所問

### 依赖情况（代码类问题务必提供）

```
bitsandbytes              0.41.0
peft                      0.3.0.dev0
sentencepiece             0.1.97
torch                     2.0.1
torchaudio                2.0.2
torchcrepe                0.0.18
transformers              4.31.0
```

**Comment by Naozumi520** [comment]
腳本參數保持相同，除了模型、數據集路徑和刪除了 `--modules_to_save ${modules_to_save}`

**Comment by ymcui** [comment]
你可以贴一下`run_sft.sh`的具体内容，重点说明以下两个参数加载的是什么，以排查是否是你第二步合并模型的时候弄错了。
```
    --model_name_or_path ${pretrained_model} \
    --peft_path ${peft_model} \
```

**Comment by Naozumi520** [comment]
```
pretrained_model=/Users/Downloads/chinese-llama-2-7b
chinese_tokenizer_path=/Users/Downloads/chinese-llama-2-7b
dataset_dir=/Users/Downloads/cantonese_dataset
per_device_train_batch_size=1
per_device_eval_batch_size=1
gradient_accumulation_steps=8
max_seq_length=512
output_dir=output_dir
validation_file=validation_file_name
```

至於你表示的peft_path，我沒有在示例中看到。不知道是什麼？我並沒有輸入

**Comment by ymcui** [comment]
1. `pretrained_model=/Users/Downloads/chinese-llama-2-7b`你这里指定的是Chinese-LLaMA-2？
2. 如果你没有指定`peft_path`，那就相当于新初始化一个LoRA。

**Comment by Naozumi520** [comment]
> 1. `pretrained_model=/Users/Downloads/chinese-llama-2-7b`你这里指定的是Chinese-LLaMA-2？
> 
> 2. 如果你没有指定`peft_path`，那就相当于新初始化一个LoRA。

1. 是alpaca. 對話版本。
2. 哦，原來如此。諗我應該如何設定呢？文檔並沒有任何相關介紹。

**Comment by ymcui** [comment]
1. 如果你用Chinese-Alpaca-2-7B（未经过你SFT）做预测，是否会出现答非所问的情况？如果结果正常，那么可能就是你SFT阶段把模型训坏了（例如超参数设置不合理等原因）。如果结果也不正常，那说明你需要检查Alpaca-2-7B的模型文件是否完整。
2. 原则上你这么训是没有问题的，即Alpaca-2 + 全新初始化的LoRA。

**Comment by Naozumi520** [comment]
1. 用未經SFT的 Chinese-Alpaca-2-7B 做預測很正常，但是當我SFT退，就答非所問了。

2. 如果我使用peft_path，應該指向哪裡？

這面是我的數據集:

<img width="1141" alt="Screenshot 2023-09-07 at 12 27 05 PM" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/52615455/931c7932-b8f0-4188-9b19-09c1143a81d8">

**Comment by ymcui** [comment]
情况1（你现在的方案）：训练一个新的alpaca-lora （不提供`peft_path`参数）
```
    --model_name_or_path Chinese-Alpaca-2-7B \
```

情况2：继续训练alpaca-lora
```
    --model_name_or_path 原版英文llama-2-7b-hf \
    --peft_path Chinese-Alpaca-2-7B-LoRA \
```

**Comment by Naozumi520** [comment]
當我設置了peft_path之後，會出現OOM. 請問是否有方法解決？我這邊是4090 24gb.

**Comment by iMountTai** [comment]
参考[显存占用](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh#关于显存占用)

**Comment by Naozumi520** [comment]
另外，如果`model_name_or_path`是填寫原版英文llama-2-7b-hf, `peft_path`是填寫Chinese-Alpaca-2-7B-LoRA, `tokenizer_name_or_path` 應該指向哪個文件夾? 我嘗試指向Chinese-Alpaca-2-7B-LoRA, 不過在推理時遇到`error loading model: create_tensor: tensor 'token_embd.weight' has wrong shape; expected  4096, 55296, got  4096, 32000,     1,     1`.
