### ISSUE TITLE
量化后，推理加载模型时错误”ggml_metal_init() failed“

### ISSUE THREAD

**Issue by swy755565055** [ymcui/Chinese-LLaMA-Alpaca-2#252]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

macOS

### 详细描述问题

系统是macos，已经量化完成，在执行./chat.sh zh-models/7B/Chinese-Alpaca-2-7B/ggml-model-q4_0.gguf 时报错，搞不懂什么问题啊

### chat.sh内容如下

  1 #!/bin/bash
  2 
  3 # temporary script to chat with Chinese Alpaca-2 model
  4 # usage: ./chat.sh alpaca2-ggml-model-path your-first-instruction
  5 
  6 SYSTEM_PROMPT='You are a helpful assistant. 你是一个乐于助人的助手。'
  7 # SYSTEM_PROMPT='You are a helpful assistant. 你是一个乐于助人的助手。请你提供专业、有逻辑、内容真实、有价值的详细回复。' # Try this one, if you prefer longer response.
  8 MODEL_PATH=$1
  9 FIRST_INSTRUCTION=$2
 10 
 11 ./main -m "$MODEL_PATH" \
 12 --color -i -c 4096 -t 8 --temp 0.5 --rope-scale 4 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 \
 13 --in-prefix-bos --in-prefix ' [INST] ' --in-suffix ' [/INST]' -p \
 14 "[INST] <<SYS>>
 15 $SYSTEM_PROMPT
 16 <</SYS>>
 17 
 18 $FIRST_INSTRUCTION [/INST]"

### 运行日志或截图
Log start
main: warning: scaling RoPE frequency by 0.25 (default 1.0)
main: build = 1187 (178b185)
main: seed  = 1694051421
llama_model_loader: loaded meta data with 19 key-value pairs and 291 tensors from zh-models/7B/Chinese-Alpaca-2-7B/ggml-model-q4_0.gguf (version GGUF V2 (latest))
llama_model_loader: - tensor    0:                token_embd.weight q4_0     [  4096, 55296,     1,     1 ]
...
llama_model_loader: - kv  18:               general.quantization_version u32     
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_0:  225 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_print_meta: format         = GGUF V2 (latest)
llm_load_print_meta: arch           = llama
llm_load_print_meta: vocab type     = SPM
llm_load_print_meta: n_vocab        = 55296
llm_load_print_meta: n_merges       = 0
llm_load_print_meta: n_ctx_train    = 4096
llm_load_print_meta: n_ctx          = 4096
llm_load_print_meta: n_embd         = 4096
llm_load_print_meta: n_head         = 32
llm_load_print_meta: n_head_kv      = 32
llm_load_print_meta: n_layer        = 32
llm_load_print_meta: n_rot          = 128
llm_load_print_meta: n_gqa          = 1
llm_load_print_meta: f_norm_eps     = 1.0e-05
llm_load_print_meta: f_norm_rms_eps = 1.0e-05
llm_load_print_meta: n_ff           = 11008
llm_load_print_meta: freq_base      = 10000.0
llm_load_print_meta: freq_scale     = 0.25
llm_load_print_meta: model type     = 7B
llm_load_print_meta: model ftype    = mostly Q4_0
llm_load_print_meta: model size     = 6.93 B
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: mem required  = 3773.80 MB (+ 2048.00 MB per state)
..............................................................................................
llama_new_context_with_model: kv self size  = 2048.00 MB
ggml_metal_init: allocating
ggml_metal_init: found device: AMD Radeon Pro 455
ggml_metal_init: found device: Intel(R) HD Graphics 530
ggml_metal_init: picking default device: AMD Radeon Pro 455
ggml_metal_init: loading '/Users/sunwenyu/Desktop/8室/大模型/llama.cpp/ggml-metal.metal'
ggml_metal_init: loaded kernel_add                         0x7fc503808550 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_add_row                     0x7fc503808b40 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul                         0x7fc503809290 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul_row                     0x7fc5038099e0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_scale                       0x7fc50380a130 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_silu                        0x7fc50380a880 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_relu                        0x7fc50380afd0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_gelu                        0x7fc50380b720 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_soft_max                    0x7fc50380be70 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_diag_mask_inf               0x7fc50380c5c0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_f16                0x7fc50380cd10 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q4_0               0x7fc50380d5d0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q4_1               0x7fc50380dd20 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q8_0               0x7fc50380e470 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q2_K               0x7fc50380ebc0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q3_K               0x7fc50380f310 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q4_K               0x7fc50380fa60 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q5_K               0x7fc5038101b0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_get_rows_q6_K               0x7fc503810900 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_rms_norm                    0x7fc5038112e0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_norm                        0x7fc5038118d0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_f16_f32             0x7fc5038121a0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_f16_f32_1row        0x7fc5038128f0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q4_0_f32            0x7fc503813040 | th_max =  768 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q4_1_f32            0x7fc503813790 | th_max =  768 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q8_0_f32            0x7fc503813ee0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q2_K_f32            0x7fc503814630 | th_max =  768 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q3_K_f32            0x7fc503814d80 | th_max =  512 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q4_K_f32            0x7fc5038154d0 | th_max =  768 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q5_K_f32            0x7fc503815da0 | th_max =  768 | th_width =   64
ggml_metal_init: loaded kernel_mul_mat_q6_K_f32            0x7fc5038164f0 | th_max = 1024 | th_width =   64
ggml_metal_init: loaded kernel_mul_mm_f16_f32                         0x0 | th_max =    0 | th_width =    0
ggml_metal_init: load pipeline error: Error Domain=CompilerError Code=2 "SC compilation failure
There is a call to an undefined label" UserInfo={NSLocalizedDescription=SC compilation failure
There is a call to an undefined label}
llama_new_context_with_model: ggml_metal_init() failed
llama_init_from_gpt_params: error: failed to create context with model 'zh-models/7B/Chinese-Alpaca-2-7B/ggml-model-q4_0.gguf'
main: error: unable to load model

**Comment by ymcui** [comment]
信息不太完整，你需要贴一下：
1. 转换模型使用的具体命令，以及chat.sh里的内容
2. log信息不完整，屏幕输出log里的`llm_load_print_meta`开头的meta信息。

**Comment by swy755565055** [comment]
> 信息不太完整，你需要贴一下：
> 
> 1. 转换模型使用的具体命令，以及chat.sh里的内容
> 2. log信息不完整，屏幕输出log里的`llm_load_print_meta`开头的meta信息。

已更新

**Comment by ymcui** [comment]
大概明白了。目前llama.cpp在macOS下是默认会启用Metal的，主要面向M系列芯片。
看你的log，应该是英特尔CPU + AMD显卡，似乎会与Metal有一些兼容性问题。
所以有几个方向供你参考：
1. 不用GPU：在启动模型时加上`-ngl 0`，看看是否能正常加载
2. 用GPU：可能需要考虑hipBLAS / CBLAST等方式重新编译llama.cpp，具体流程参考 https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#blas-build

**Comment by swy755565055** [comment]
> 大概明白了。目前llama.cpp在macOS下是默认会启用Metal的，主要面向M系列芯片。 看你的log，应该是英特尔CPU + AMD显卡，似乎会与Metal有一些兼容性问题。 所以有几个方向供你参考：
> 
> 1. 不用GPU：在启动模型时加上`-ngl 0`，看看是否能正常加载
> 2. 用GPU：可能需要考虑hipBLAS / CBLAST等方式重新编译llama.cpp，具体流程参考 https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#blas-build

嗯CPU可以，AMD的GPU是兼容性问题
