### ISSUE TITLE
C-Eval评测Alpaca-2复现问题

### ISSUE THREAD

**Issue by Shirley-Xi** [ymcui/Chinese-LLaMA-Alpaca-2#253]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

您好，非常感谢你们的工作。目前在做结果复现，遇到一些问题。（后续基于Chinese-Llama系列模型做继续预训练，需要对比指标的变化）
同样的模型和参数配置，CMMLU评测的结果均可复现。C-Eval评测，Chinese-LLaMA-2-13B和7B的结果也都能复现。但Chinese-Alpaca-2-13B、Chinese-Alpaca-2-7B的结果复现有较大差异。
C-Eval Valid集的评测复现结果为：(括号中是官方结果）
Chinese-Alpaca-2-13B zero-shot：42.3 （44.3）
Chinese-Alpaca-2-13B five-shot：36.2（45.9）
Chinese-Alpaca-2-7B zero-shot：41.2 （41.3）
Chinese-Alpaca-2-7B five-shot：30.7 （42.9）
部分复现结果有较大差异，不知道是脚本参数配置有差异还是其他原因，一步步待排查。请问评估脚本参数和官方评估实验是一致的吗？非常感谢！

下面是以alpaca-2-13B zero shot为例的评测脚本。其他alpaca-2的测试只改动model(选7B或13B）和few-shot部分（0 shot或 5 shot).

```
model_path=/data/chinese-alpaca-2-13b
output_path=./output/chinese-alpaca-2-13b-0
python eval.py \
    --model_path ${model_path} \
    --cot False \
    --few_shot False \
    --with_prompt True \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir ${output_path}
    --input_dir data
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

Chinese-Alpaca-2-13B 0shot  C-Eval Valid评测结果
```
  "All": {
    "score": 0.4227340267459138,
    "num": 1346,
    "correct": 569.0
  }
```

Chinese-Alpaca-2-13B 5shot  C-Eval Valid评测结果
```
"All": {
    "score": 0.36181277860326894,
    "num": 1346,
    "correct": 487.0
  }
```

Chinese-Alpaca-2-7B 5shot  C-Eval Valid评测结果
```
  "All": {
    "score": 0.30683506686478457,
    "num": 1346,
    "correct": 413.0
  }
```

**Comment by ymcui** [comment]
`--with_prompt False`试一下。这类NLU数据集有的时候不用指令模板会获得更好的效果。

**Comment by Shirley-Xi** [comment]
> `--with_prompt False`试一下。这类NLU数据集有的时候不用指令模板会获得更好的效果。

感谢！改了`--with_prompt False`，Alpaca2-7B的结果能复现。Alpaca2-13B的结果还是有差异（zero-shot最好结果42.3, 5-shot最好结果43.7）还有其他要注意的调整吗？谢谢！

**Comment by ymcui** [comment]
还可以尝试`--constrained_decoding False`，增加随机性。
