### ISSUE TITLE
pt和sft的时候，报错：AttributeError: 'LlamaForCausalLM' object has no attribute 'sava checkpoint'，peft照着requirments无法安装，自己pip install的。

### ISSUE THREAD

**Issue by ppppls115** [ymcui/Chinese-LLaMA-Alpaca-2#258]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
# 运行脚本前请仔细阅读wiki(https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/pt_scripts_zh)
# Read the wiki(https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/pt_scripts_zh) carefully before running the script
lr=2e-4
lora_rank=64
lora_alpha=128
lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"
lora_dropout=0.05

pretrained_model=/data/liang/model/chinese-alpaca-2-13b-hf
chinese_tokenizer_path=/data/liang/model/chinese-alpaca-2-13b-hf
dataset_dir=/home/liang/code/Chinese-LLaMA-Alpaca-2-main/dataset
data_cache=/home/liang/code/Chinese-LLaMA-Alpaca-2-main/data_cache
per_device_train_batch_size=1
gradient_accumulation_steps=8
block_size=512
output_dir=output_dir

deepspeed_config_file=ds_zero2_no_offload.json

# torchrun --nnodes 1 --nproc_per_node 1 run_clm_pt_with_peft.py \

CUDA_VISIBLE_DEVICES=2 python run_clm_pt_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --data_cache_dir ${data_cache} \
    --validation_split_percentage 0.001 \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --do_train \
    --seed 666 \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --block_size ${block_size} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --torch_dtype float16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```
bitsandbytes                  0.41.0
peft                          0.3.0
sentencepiece                 0.1.97
torch                         2.0.1
transformers                  4.31.0
transformers-stream-generator 0.0.4

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
Traceback (most recent call last):
  File "/home/liang/code/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 445, in <module>
    main()
  File "/home/liang/code/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 418, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/trainer.py", line 1927, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/trainer.py", line 2265, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/transformers/trainer.py", line 2326, in _save_checkpoint
    self.model_wrapped.save_checkpoint(output_dir)
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/peft/peft_model.py", line 290, in __getattr__
    return getattr(self.base_model, name)
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/peft/tuners/lora.py", line 280, in __getattr__
    return getattr(self.model, name)
  File "/home/liang/anaconda3/envs/llm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'save_checkpoint'

**Comment by Qznan** [comment]
可参照#166 解决哈
