### ISSUE TITLE
chinese-alpaca2-7b中SHA256.md提供的值与自己算的值不一样

### ISSUE THREAD

**Issue by zzx16045223** [ymcui/Chinese-LLaMA-Alpaca-2#261]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

None

### 操作系统

Linux

### 详细描述问题

这是自己算的
sha256sum config.json 
2dcbbb625d02f4d12406d71b28d5cfac71fdffd332a0d91bc163655b35a185ac  config.json

sha256sum generation_config.json 
343026a3ef80bf1c69ad858cc414a87037bb9725d12cd24b7a194eabcc520e2d  generation_config.json

这是SHA256.md中提供的
68f516b143f9cdfe669efb3ae4edd707ff6e996559a68160d9f2d900e5bf1a3a  config.json
a8094d0e4f79ad03cb77120df07d86e6fcf77b9654b5ca8323ecccdb40b3d84d  generation_config.json

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
不同transformers版本转换出来的问题，如果JSON里的重要字段一致的话就不必纠结。
