### ISSUE TITLE
Chinese-Alpaca-2-7B 的训练方式具体是什么？

### ISSUE THREAD

**Issue by Olivia-xu** [ymcui/Chinese-LLaMA-Alpaca-2#264]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

想和楼主请教下，相关下载链接里 Chinese-Alpaca-2-7B 分为lora model和full model， 区别是Chinese-Alpaca-2-7B lora model部分是Lora参数，Chinese-Alpaca-2-7B full model是Lora参数与base model合并后的参数吗？ 但是两者都是Lora训练方式而不是全参数微调是吗？

### 依赖情况（代码类问题务必提供）

无

### 运行日志或截图

无

**Comment by ymcui** [comment]
1. 中文Alpaca-2 = 原版Llama-2 + 中文Alpaca-2-LoRA
2. 不是全量微调，再不理解就看看技术报告吧。
