### ISSUE TITLE
使用llamacpp提供的api_like_OAI的API时，回复的文本内容还有USER和ASSISTANT的对话，这是否受参数控制？

### ISSUE THREAD

**Issue by Shimooth** [ymcui/Chinese-LLaMA-Alpaca-2#265]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

调用API生成的文本还附有对话信息，拉慢响应速度，以下是具体操作：
在llamacpp中用./server启动后
再执行llamacpp中examples/server/api_like_OAI.py脚本后
再运行以下脚本

# coding=utf-8
import sys
import os
sys.path.append(os.path.dirname(os.getcwd()))
from flask import Flask, render_template, request,jsonify
import urllib.request
import requests
import base64
import time
import json

message=[]

app = Flask(__name__,static_url_path="/static")
@app.route('/message', methods=['POST'])
#"""定义应答函数，用于获取输入信息并返回相应的答案"""
def reply():
    #从请求中获取输入信息
    query = request.form['msg']
    print('query:'+query)
    messages.append({'role': 'user', 'content': query})
    requrl = "http://127.0.0.1:8081/v1/chat/completions"
    headers = {'Content-Type': 'application/json'}
    query_arr = dict()
    query_arr['messages'] = messages
    response=requests.post(requrl,headers= headers,json = query_arr)
    response_text=json.loads(response.text)
    print('--------------------------')
    print("response:"+str(response_text))
    res_msg = response_text['choices'][0]['message']['content']
    messages.append({'role': 'assistant', 'content': res_msg})
    return jsonify( { 'text': res_msg } )

@app.route("/")
def index(): 
    return render_template("index.html")

# 启动APP
if (__name__ == "__main__"): 
    app.run(host = '0.0.0.0', port = 8807) 

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/142218075/a158c69a-9db0-4f53-9035-1058cadd34f9)

**Comment by ymcui** [comment]
不太清楚你是怎么起的server，多半是调用的时候没有嵌套Alpaca-2模板导致的。
仿照`scripts/llamacpp/server_curl_example.sh`脚本排查吧。

**Comment by Shimooth** [comment]
> 不太清楚你是怎么起的server，多半是调用的时候没有嵌套Alpaca-2模板导致的。 仿照`scripts/llamacpp/server_curl_example.sh`脚本排查吧。

感谢！我发觉我使用的方法有点繁琐了，改用了scripts/openai_server_demo/openai_api_server.py启服务，没有再出现上述问题。但是我发现使用这个接口显存会越用越大，这是正常的吗？
<img width="497" alt="企业微信截图_16950299887863" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/142218075/1ef66cd6-4ceb-4118-b648-e0a57fcd4cae">
<img width="496" alt="企业微信截图_1695030085565" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/142218075/5a0b3434-a915-4821-9f55-e08f9e26511a">
