### ISSUE TITLE
api_calls_zh部署后调用, 提示 Connection refused

### ISSUE THREAD

**Issue by neal668** [ymcui/Chinese-LLaMA-Alpaca-2#270]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
执行如下代码部署
python3 scripts/openai_server_demo/openai_api_server.py --base_model chinese-alpaca-2-lora-13b --tokenizer_path /chinese-alpaca-2-lora-13b
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
无新增依赖, 默认使用项目中的requirements
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
curl http://localhost:19327/v1/completions \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "告诉我中国的首都在哪里"
  }'
curl: (7) Failed to connect to localhost port 19327: Connection refused
```

**Comment by ymcui** [comment]
换个端口试试
