### ISSUE TITLE
计划支持fastchat吗

### ISSUE THREAD

**Issue by Mr-IT007** [ymcui/Chinese-LLaMA-Alpaca-2#273]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

模型计划支持fastchat吗

**Comment by feiandxs** [comment]
其实已经支持了。我自己正在用fastchat跑。 不过有个问题是我跑16k的alpaca-2 的时候，虽然设置了16k，但总是长度没达到的时候就没截断，同时GPU还在运行，我感觉是fastchat的问题，没能很好的识别出来它的实际长度。

**Comment by garyyang85** [comment]
@feiandxs 请问使用fastchat时16K长度被截断的问题解决了么？
