### ISSUE TITLE
privategpt无法载入模型

### ISSUE THREAD

**Issue by 8188** [ymcui/Chinese-LLaMA-Alpaca-2#277]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

我按本仓库教程使用privateGPT，报错如下，请问是怎么回事？路径没问题，否则报路径不存在（python3.10）
```
python privateGPT.py
```
Traceback (most recent call last):
  File "/home/dell/mystuff/privateGPT-main/privateGPT.py", line 158, in <module>
    main()
  File "/home/dell/mystuff/privateGPT-main/privateGPT.py", line 42, in main
    llm = LlamaCpp(
  File "/usr/local/miniconda3/envs/llama/lib/python3.10/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /home/dell/models/chinese-alpaca-2-7b-hf/ggml-model-f16.bin. Received error  (type=value_error)

单独执行Llama()也报错
>>> from llama_cpp import Llama
>>> llm = Llama(model_path="/home/dell/models/chinese-alpaca-2-7b-hf/ggml-model-f16.bin")
gguf_init_from_file: invalid magic number 67676a74
error loading model: llama_model_loader: failed to load model from /home/dell/models/chinese-alpaca-2-7b-hf/ggml-model-f16.bin

llama_load_model_from_file: failed to load model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/miniconda3/envs/llama/lib/python3.10/site-packages/llama_cpp/llama.py", line 323, in __init__
    assert self.model is not None
AssertionError

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
说明你llama-cpp-python安装的有问题。卸载之后按官方的最新说明重新安装试试吧。

**Comment by 8188** [comment]
@ymcui 老的格式不支持了，用ggml-model-f16.gguf就ok，但是速度极慢，不知道为什么无法使用GPU，但已经装了gpu支持
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir

```
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type  f16:  226 tensors
llm_load_print_meta: format         = GGUF V2 (latest)
llm_load_print_meta: arch           = llama
llm_load_print_meta: vocab type     = SPM
llm_load_print_meta: n_vocab        = 55296
llm_load_print_meta: n_merges       = 0
llm_load_print_meta: n_ctx_train    = 4096
llm_load_print_meta: n_ctx          = 4096
llm_load_print_meta: n_embd         = 4096
llm_load_print_meta: n_head         = 32
llm_load_print_meta: n_head_kv      = 32
llm_load_print_meta: n_layer        = 32
llm_load_print_meta: n_rot          = 128
llm_load_print_meta: n_gqa          = 1
llm_load_print_meta: f_norm_eps     = 1.0e-05
llm_load_print_meta: f_norm_rms_eps = 1.0e-05
llm_load_print_meta: n_ff           = 11008
llm_load_print_meta: freq_base      = 10000.0
llm_load_print_meta: freq_scale     = 1
llm_load_print_meta: model type     = 7B
llm_load_print_meta: model ftype    = mostly F16
llm_load_print_meta: model size     = 6.93 B
llm_load_print_meta: general.name   = LLaMA v2
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: PAD token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.09 MB
llm_load_tensors: mem required  = 13217.11 MB (+ 2048.00 MB per state)
...............................................................................................
llama_new_context_with_model: kv self size  = 2048.00 MB
llama_new_context_with_model: compute buffer total size =  281.47 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | 
```

**Comment by ymcui** [comment]
1. 应该还是llama-cpp-python安装的有点问题，看你的log里并没有GPU offload相关信息。你可以试试直接用llama.cpp的`./main`加载这个模型，并且启用GPU加速`-ngl 100`。
2. 另外，F16模型可以转成量化版，从而起到提速作用（但主要还是先解决上面说的无法调用GPU的问题）。
