### ISSUE TITLE
Chinese-Alpaca-2-LoRA-13B merge target?

### ISSUE THREAD

**Issue by gameveloster** [ymcui/Chinese-LLaMA-Alpaca-2#278]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] I have read the [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki) and [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [LangChain](https://github.com/hwchase17/langchain), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), we recommend checking the corresponding project for solutions

### Type of Issue

None

### Base Model

Chinese-LLaMA-2 (7B/13B)

### Operating System

Linux

### Describe your issue in detail

Is there LoRA files for `Chinese-Alpaca-2-LoRA-13B` that is used to merge into `Chinese-LLaMA-2-13B` instead of `meta-llama/Llama-2-13b-hf`?

Was `Chinese-Alpaca-2-LoRA-13B` Lora created from `meta-llama/Llama-2-13b-hf` or from `Chinese-LLaMA-2-13B`?

Thank you

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

```
# Please copy-and-paste your logs here.
```

**Comment by ymcui** [comment]
You should regard Chinese-Alpaca-2 as an instruction-tuned LLaMA.
Technically speaking, `Chinese-Alpaca-2-LoRA-13B` **inherits** the weight of `Chinese-LLaMA-2-LoRA-13B` and perform further instruction tuning.
That being said, the base model (meta's llama) has not been changed in training both LLaMA and Alpaca. You should still use Meta's Llama-2 for merging purpose.
