### ISSUE TITLE
多个bin文件如何合并？

### ISSUE THREAD

**Issue by naiqiu2023** [ymcui/Chinese-LLaMA-Alpaca-2#280]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Windows

### 详细描述问题

我在HF上看到模型是多个bin文件，我要在PrivateGPT中加载，我需要把bin文件进行合并吗？

**Comment by ymcui** [comment]
privateGPT加载的不是HF格式，是llama.cpp的GGML/GGUF或者GPT4All格式。你还是仔细看一下wiki吧。修改配置文件一步已经将清楚了。
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/privategpt_zh#step-2-修改配置文件
```
MODEL_PATH：指向大模型存放位置，这里指向的是llama.cpp支持的GGML文件
```

**Comment by naiqiu2023** [comment]
您的意思是说？我需要做模型的转换是吗？

**Comment by naiqiu2023** [comment]
不好意思，可能是我没有表述清楚；
我要使用https://huggingface.co/ziqingyang/chinese-alpaca-2-13b/tree/main这个模型来做嵌入，但是我在hf上下载的话都是bin文件，privateGPT支持的是ggml,gguf格式，我需要做转换吗？

**Comment by ymcui** [comment]
你还是指代清楚一点吧，是指配置文件里的`EMBEDDINGS_MODEL_NAME`还是`MODEL_PATH`？
- MODEL_PATH：要求是llama.cpp的模型格式
- EMBEDDINGS_MODEL_NAME：SentenceTransformers词向量

**Comment by ymcui** [comment]
如果你说的是EMBEDDINGS_MODEL_NAME，那为什么要用13b这么大的模型做呢？本身EMBEDDINGS_MODEL的作用是用来做索引的，应当选用轻量级的模型。

**Comment by naiqiu2023** [comment]
> 你还是指代清楚一点吧，是指配置文件里的`EMBEDDINGS_MODEL_NAME`还是`MODEL_PATH`？
> 
> * MODEL_PATH：要求是llama.cpp的模型格式
> * EMBEDDINGS_MODEL_NAME：SentenceTransformers词向量

抱歉，您说的，我明白，就是如果我要用privategpt的话，MODEL_PATH模型必须是llama.cpp支持的模型格式，我清楚。

我看了项目的说明，这里有个完整模型的下载地址，
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/145083412/f2bc14c7-ae3a-495d-a90b-d0dfa915c027)

我打开以后呢，模型的文件格式是bin格式的。
我是不是要做转换成ggml模型？

非常感谢？

**Comment by naiqiu2023** [comment]
> 如果你说的是EMBEDDINGS_MODEL_NAME，那为什么要用13b这么大的模型做呢？本身EMBEDDINGS_MODEL的作用是用来做索引的，应当选用轻量级的模型。

谢谢，我明白您的说的嵌入模型必须是轻量模型，我已经明白。

**Comment by ymcui** [comment]
HF -> GGML格式在llama.cpp的教程里已经写了。
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh

**Comment by naiqiu2023** [comment]
> HF -> GGML格式在llama.cpp的教程里已经写了。 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh

谢谢，非常感谢。

**Comment by fgyang** [comment]
> > HF -> GGML格式在llama.cpp的教程里已经写了。 https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/llamacpp_zh
> 
> 谢谢，非常感谢。

您好，您的问题解决了么？我是用privategpt也是相同的问题,多个bin文件,如果执行模型,MODEL_PATH=F:/privateGPT/model/chinese-alpaca-2-13b-hf就是这个位置应该如何做,我该怎么弄?
