### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for

### ISSUE THREAD

**Issue by luoxianjun** [ymcui/Chinese-LLaMA-Alpaca-2#281]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
执行 python scripts/openai_server_demo/openai_api_server.py --base_model /home/ubuntu/chineseLLaMA/chinese-alpaca-2-13b-hf

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```
bitsandbytes                 0.41.0
peft                         0.5.0
sentencepiece                0.1.97
torch                        2.0.1+cu118
torchvision                  0.15.2+cu118
transformers                 4.31.0

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
<img width="1064" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/5306492/acf79926-39b0-4746-b222-62e27849b48c">
<img width="1116" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/5306492/7d9c52a3-7081-4c90-b48c-2c6296bb6bcf">

**Comment by airaria** [comment]
文件是否损坏了？
检查一下模型文件的SHA
```bash
sha256sum /home/ubuntu/chineseLLaMA/chinese-alpaca-2-13b-hf/pytorch*bin
```
是否和以下值一致：
```
pytorch_model-00001-of-00003.bin 6ad30c3f94918dfdba08b7d45d9bc02d18f3ac2b203e5b63c7995faa9bc1f476
pytorch_model-00002-of-00003.bin b368203429e4a55c196e736f4f7e0e6e500b98bcb9cb07a9c16c7017eb4fcdae
pytorch_model-00003-of-00003.bin de16e560d27af8eb129ea54d84cac471768e7176770518e07dd437b1857fae21
```

**Comment by luoxianjun** [comment]
确实文件损坏了
