### ISSUE TITLE
请问4090的4卡如何lora微调LLaMA2  13b的版本啊，现有的方式总是出现OOM，查看发现只是数据并行了，并没有模型参数并行

### ISSUE THREAD

**Issue by C-rawler** [ymcui/Chinese-LLaMA-Alpaca-2#282]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
torchrun --nnodes 1 --nproc_per_node 4  run_clm_sft_with_peft.py \
    --deepspeed ${deepspeed_config_file} \
    --model_name_or_path ${pretrained_model} \
    --tokenizer_name_or_path ${chinese_tokenizer_path} \
    --dataset_dir ${dataset_dir} \
    --per_device_train_batch_size ${per_device_train_batch_size} \
    --per_device_eval_batch_size ${per_device_eval_batch_size} \
    --do_train \
    --do_eval \
    --seed 2023 \
    --fp16 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate ${lr} \
    --warmup_ratio 0.03 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 10 \
    --save_strategy steps \
    --save_total_limit 3 \
    --evaluation_strategy steps \
    --eval_steps 100 \
    --save_steps 200 \
    --gradient_accumulation_steps ${gradient_accumulation_steps} \
    --preprocessing_num_workers 8 \
    --max_seq_length ${max_seq_length} \
    --output_dir ${output_dir} \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --lora_rank ${lora_rank} \
    --lora_alpha ${lora_alpha} \
    --trainable ${lora_trainable} \
    --lora_dropout ${lora_dropout} \
    --modules_to_save ${modules_to_save} \
    --torch_dtype float16 \
    --validation_file ${validation_file} \
    --load_in_kbits 16 \
    --gradient_checkpointing \
    --ddp_find_unused_parameters False

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
Loading checkpoint shards:  67%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                                          | 2/3 [00:16<00:08,  8.26s/it]
Traceback (most recent call last):
  File "/mnt/nvme1n1/shiyan/project/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 534, in <module>
    main()
  File "/mnt/nvme1n1/shiyan/project/Chinese-LLaMA-Alpaca-2-main/scripts/training/run_clm_sft_with_peft.py", line 411, in main
    model = LlamaForCausalLM.from_pretrained(
  File "/home/admin/install/anaconda3/envs/train_llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/admin/install/anaconda3/envs/train_llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3563, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/admin/install/anaconda3/envs/train_llm/lib/python3.9/site-packages/transformers/modeling_utils.py", line 745, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/admin/install/anaconda3/envs/train_llm/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 313, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 2; 23.65 GiB total capacity; 23.19 GiB already allocated; 2.06 MiB free; 23.19 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by airaria** [comment]
可以修改deepspeed_config_file，以ZeRO-3的形式训练

**Comment by airaria** [comment]
也支持量化训练，设置`--load_in_kbits 4`或`load_in_kbits 8`也可以降低显存占用

**Comment by C-rawler** [comment]
我改成ZeRO-3形式训练还是有点问题
"zero_optimization": {
        "stage": 3,
        "allgather_partitions": true,
        "allgather_bucket_size": 1e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 1e8,
        "contiguous_gradients": true,
	"stage3_gather_16bit_weights_on_model_save": true
    },
同时把训练文件里的low_cpu_mem_usage=True,  device_map=device_map,给注释掉了。
最后训练的时候报错：
AssertionErrorAssertionErrorAssertionErrorAssertionError: {'id': 363, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0, 5120), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {1407}, 'ds_tensor.shape': torch.Size([0])}: 
{'id': 363, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0, 5120), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {1407}, 'ds_tensor.shape': torch.Size([0])}: 
: {'id': 363, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0, 5120), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {1407}, 'ds_tensor.shape': torch.Size([0])}{'id': 363, 'status': 'NOT_AVAILABLE', 'numel': 0, 'ds_numel': 0, 'shape': (0,), 'ds_shape': (0, 5120), 'requires_grad': True, 'grad_shape': None, 'persist': True, 'active_sub_modules': {1407}, 'ds_tensor.shape': torch.Size([0])}

  0%|                                                                                                                        | 0/123 [00:01<?, ?it/s]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 490896 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 490893) of binary: /home/admin/install/anaconda3/envs/train_llm/bin/python

请问是不是哪里修改的不对啊

**Comment by ssm0808** [comment]
我也遇到同样的问题，没有实现模型参数并行。修改了ZeRO-3形式训练也是有点问题：
zero3：
{
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto",
            "warmup_type": "linear"
        }
    },
    "zero_optimization": {
        "stage": 3,
        "stage3_gather_16bit_weights_on_model_save": true,
        "reduce_scatter": true,
        "overlap_comm": true,
        "contiguous_gradients": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 100,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
