### ISSUE TITLE
模型载入错误

### ISSUE THREAD

**Issue by lnelxon** [ymcui/Chinese-LLaMA-Alpaca-2#289]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Windows

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
使用模型时，加载发生错误

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
Traceback (most recent call last):

File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 488, in load_state_dict

return torch.load(checkpoint_file, map_location=map_location)
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\[serialization.py](http://serialization.py/)”, line 791, in load

with _open_file_like(f, 'rb') as opened_file:
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\[serialization.py](http://serialization.py/)”, line 271, in _open_file_like

return _open_file(name_or_buffer, mode)
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\torch\[serialization.py](http://serialization.py/)”, line 252, in init

super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ‘models\Chinese-Alpaca-2-13B\pytorch_model-00001-of-00003.bin’

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File “E:\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py”, line 194, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “E:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 77, in load_model

output = load_func_map[loader](model_name)
File “E:\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 147, in huggingface_loader

model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=shared.args.trust_remote_code)
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 563, in from_pretrained

return model_class.from_pretrained(
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 3187, in from_pretrained

) = cls._load_pretrained_model(
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 3560, in _load_pretrained_model

state_dict = load_state_dict(shard_file)
File “E:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 491, in load_state_dict

with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: ‘models\Chinese-Alpaca-2-13B\pytorch_model-00001-of-00003.bin’

**Comment by cheney369** [comment]
你这是模型没下载完全吧？或者模型地址写错了。

**Comment by lnelxon** [comment]
> 你这是模型没下载完全吧？或者模型地址写错了。

重新下载模组一样，地址指的是model下吗

**Comment by ymcui** [comment]
运行的什么程序，怎么调用的（命令行、加载模型对应的代码等）？
