### ISSUE TITLE
运行到 ./chat.sh zh-models/7B/ggml-model-q4_k.gguf '你好'，报： 段错误（核心已转储）

### ISSUE THREAD

**Issue by lckj2009** [ymcui/Chinese-LLaMA-Alpaca-2#291]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
#  ./chat.sh zh-models/7B/ggml-model-q4_k.gguf '你好'
./chat.sh: 第 18 行： 57623 段错误               （核心已转储） ./main -m "$MODEL_PATH" --color -i -c 4096 -t 8 --temp 0.5 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 -eps 1e-5 --in-prefix-bos --in-prefix ' [INST] ' --in-suffix ' [/INST]' -p "[INST] <<SYS>>
$SYSTEM_PROMPT
<</SYS>>

$FIRST_INSTRUCTION [/INST]"

```

### 依赖情况（代码类问题务必提供）

```
# requirements.txt 等环境齐全
```

### 运行日志或截图

```
#  ./chat.sh zh-models/7B/ggml-model-q4_k.gguf '你好'
./chat.sh: 第 18 行： 57623 段错误               （核心已转储） ./main -m "$MODEL_PATH" --color -i -c 4096 -t 8 --temp 0.5 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 -eps 1e-5 --in-prefix-bos --in-prefix ' [INST] ' --in-suffix ' [/INST]' -p "[INST] <<SYS>>
$SYSTEM_PROMPT
<</SYS>>

$FIRST_INSTRUCTION [/INST]"

```

**Comment by cheney369** [comment]
遇到同一个问题
./chat.sh: line 18: 11719 Segmentation fault      (core dumped) ./main -m "$MODEL_PATH" --color -i -c 4096 -t 8 --temp 0.5 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 --in-prefix-bos --in-prefix ' [INST] ' --in-suffix ' [/INST]' -p "[INST] <<SYS>>
$SYSTEM_PROMPT
<</SYS>>

$FIRST_INSTRUCTION [/INST]"

**Comment by ymcui** [comment]
系统内存什么配置？ 降低到`-c 512`试试？

**Comment by cheney369** [comment]
> 系统内存什么配置？ 降低到`-c 512`试试？
CPU64G。使用-c 512也会出现同样的问题。
我不使用chat.sh，直接使用./main -m {model_path} 也会出现这样的问题。

**Comment by ymcui** [comment]
@cheney369 
加载原版llama是否有这个问题？还是说只有我们的中文模型会这样？
如果原版llama也有问题说明你的环境可能有问题。去llama.cpp那边找找有没有解决方案吧。
https://github.com/search?q=repo%3Aggerganov%2Fllama.cpp+segmentation+fault&type=issues

**Comment by cheney369** [comment]
> @cheney369
> 加载原版llama是否有这个问题？还是说只有我们的中文模型会这样？
> 如果原版llama也有问题说明你的环境可能有问题。去llama.cpp那边找找有没有解决方案吧。
> https://github.com/search?q=repo%3Aggerganov%2Fllama.cpp+segmentation+fault&type=issues

十分感谢，目前解决方法应该是这个https://github.com/ggerganov/llama.cpp/issues/1354#issuecomment-1546921037。上述链接好像也是在谈论你们这个中文模型问题。
之前使用$ make LLAMA_CUBLAS=1 会出现这个 Segmentation fault (core dumped)问题，重新make clean 和$ make之后，可运行，算是暂时解决运行问题。

**Comment by lckj2009** [comment]
上面的各位，问题已经解决，是之前克隆的llama.cpp有问题，重新克隆就没事了。说真的，我觉得这个东西克隆下来不稳定。

**Comment by cheney369** [comment]
> 上面的各位，问题已经解决，是之前克隆的llama.cpp有问题，重新克隆就没事了。说真的，我觉得这个东西克隆下来不稳定。
我早上重新试了下 make clean，重新编译了一遍，竟然就好了，CPU和GPU都能用。我这边不是我clone的问题，估计是我昨天编译的操作有问题导致的。
