### ISSUE TITLE
新扩充的词表模型会开源么？

### ISSUE THREAD

**Issue by jiejie1993** [ymcui/Chinese-LLaMA-Alpaca-2#30]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

扩充后的词表模型（55296）会开源出来么？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
下载的模型压缩包中的tokenizer.model就是

**Comment by sun1092469590** [comment]
> 下载的模型压缩包中的tokenizer.model就是

如果想要自己重训练下13b呢，中文词表要怎么弄？chinese_tokenizer_path=path/to/chinese/llama-2/tokenizer/dir

**Comment by airaria** [comment]
> 如果想要自己重训练下13b呢，中文词表要怎么弄？chinese_tokenizer_path=path/to/chinese/llama-2/tokenizer/dir

13B模型可以使用同样的词表

**Comment by sun1092469590** [comment]
> > 如果想要自己重训练下13b呢，中文词表要怎么弄？chinese_tokenizer_path=path/to/chinese/llama-2/tokenizer/dir
> 
> 13B模型可以使用同样的词表

啥意思呢？将现在该项目中开源的7b中的tokenizer.model直接替换掉llama-2-13b中的tokenizer.model？

**Comment by airaria** [comment]
13B模型用的chinese_tokenizer_path和7B模型用的是相同的

**Comment by sun1092469590** [comment]
> 13B模型用的chinese_tokenizer_path和7B模型用的是相同的

哦哦，好的好的，谢谢哈
