### ISSUE TITLE
提交到c-eval提示不是每个类目都大于等于50道题

### ISSUE THREAD

**Issue by yingwen330** [ymcui/Chinese-LLaMA-Alpaca-2#300]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```

python eval.py \
    --model_path /data/models/chinese-alpaca-2-13b-hf \
    --cot False \
    --few_shot False \
    --with_prompt True \
    --constrained_decoding True \
    --temperature 0.2 \
    --n_times 1 \
    --ntrain 5 \
    --do_save_csv False \
    --do_test False \
    --output_dir /data/project/evalresult-13b \
```

### 依赖情况（代码类问题务必提供）

```
sentence-transformers 2.2.2
sentencepiece         0.1.99
torch                 2.0.1
torchvision           0.15.2
transformers          4.33.2

```

### 运行日志或截图

![a384f23f9cf2da982fe17f163fd0ac7](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/131145127/5911b830-d5ee-4e64-ab5b-16fdbcacba57)

**Comment by iMountTai** [comment]
设置`--do_test True`
