### ISSUE TITLE
Chinese-Alpaca-2为何训练的时候用的是单轮prompt，推理的时候可以直接用多轮prompt?

### ISSUE THREAD

**Issue by minmie** [ymcui/Chinese-LLaMA-Alpaca-2#303]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

你好，本项目说 “在Chinese-LLaMA-2的基础上，利用有标注指令数据进行进一步精调，得到Chinese-Alpaca-2系列模型”
于是我看了一下sft的源码，发现构造的数据都是单轮对话prompt，如下图：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/e1d8a0d6-f0a4-4a35-99e5-3ee746dbc9cc)

但是项目里说，这样训练好后的Chinese-Alpaca-2却支持多轮对话，并且推理的时候使用的是如下prompt:
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/ba71e3fb-63c4-4fd9-b952-5f04581644eb)

我有几个问题：

1. 训练的时候使用的单轮对话数据，推理的时候也能支持多轮对话？
2. 训练的时候都是单轮对话的prompt，推理的时候直接使用多轮对话prompt，模型也能理解吗？（多轮对话的prompt模型从没见过）

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by airaria** [comment]
微调训练时也使用了多轮对话数据，格式和你提供的图二相同。

**Comment by minmie** [comment]
> 微调训练时也使用了多轮对话数据，格式和你提供的图二相同。

你好，图一就是微调训练的代码，你看这代码可以看出，第一：数据就是单轮的，第二：prompt也是单轮的啊，没看到多轮prompt中的<s></s>token

**Comment by minmie** [comment]
> 因多轮数据无统一的存储格式，也无统一的将多轮数据转换成目标prompt格式的方法，需要针对不同来源的数据分别处理，因此这部分代码较繁杂，我们尚未整理并开源。
> 
> 你若有训练的需要，可以将手上的多轮数据按多轮格式拼接成prompt并制作成dataset即可。

@airaria    你好

意思是，该项目在训练Chinese-LLaMA-2使用的是多轮的prompt(包含\<s>和 \</s>)，只不过开源的代码是单轮prompt的微调。
如果我需要，我可以按照上述多轮prompt自己构造训练数据去微调
以上是我的理解，不知道对不对

**Comment by airaria** [comment]
> 意思是，该项目在训练Chinese-LLaMA-2使用的是多轮的prompt(包含<s>和 </s>)，只不过开源的代码是单轮prompt的微调。 如果我需要，我可以按照上述多轮prompt自己构造训练数据去微调 以上是我的理解，不知道对不对

是的。另外，准确的说是在训练Chinese-Alapca-2时在多轮数据上使用的是多轮的prompt

**Comment by minmie** [comment]
> > 意思是，该项目在训练Chinese-LLaMA-2使用的是多轮的prompt(包含和 )，只不过开源的代码是单轮prompt的微调。 如果我需要，我可以按照上述多轮prompt自己构造训练数据去微调 以上是我的理解，不知道对不对
> 
> 是的。另外，准确的说是在训练Chinese-Alapca-2时在多轮数据上使用的是多轮的prompt

@airaria 谢谢
感觉这点是不是要在项目中说明一下，不然容易让人产生疑惑。
