### ISSUE TITLE
关于llama.cpp推理，make我有疑问

### ISSUE THREAD

**Issue by lckj2009** [ymcui/Chinese-LLaMA-Alpaca-2#304]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
问题： llama.cpp我用 make 编译。编译过程中结果出现了如下错误：
examples/baby-llama/baby-llama.cpp: In function ‘int main(int, char**)’:
examples/baby-llama/baby-llama.cpp:611:78: warning: ‘kv_self.llama_kv_cache::v’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  611 |                 vc = ggml_set_2d(ctx0, vc, Vcur, (   n_ctx)*ggml_element_size(kv_self.v),
      |                                                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
examples/baby-llama/baby-llama.cpp:1582:27: note: ‘kv_self.llama_kv_cache::v’ was declared here
 1582 |     struct llama_kv_cache kv_self;
      |                           ^~~~~~~
examples/baby-llama/baby-llama.cpp:610:101: warning: ‘kv_self.llama_kv_cache::k’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  610 |                 kc = ggml_set_1d(ctx0, kc, ggml_reshape_1d(ctx0, Kcur, n_embd*N), (ggml_element_size(kv_self.k)*n_embd)*(il*n_ctx + n_past));
      |                                                                                    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
examples/baby-llama/baby-llama.cpp:1582:27: note: ‘kv_self.llama_kv_cache::k’ was declared here
 1582 |     struct llama_kv_cache kv_self;
      |
  
之后再次运行make时。是这样的显示：
I llama.cpp build info: 
I UNAME_S:   Linux
I UNAME_P:   x86_64
I UNAME_M:   x86_64
I CFLAGS:    -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c11   -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wdouble-promotion -Wshadow -Wstrict-prototypes -Wpointer-arith -Wmissing-prototypes -Werror=implicit-int -Wno-unused-function -pthread -march=native -mtune=native 
I CXXFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native 
I NVCCFLAGS:  -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread    -Wno-pedantic -Xcompiler "-march=native -mtune=native "
I LDFLAGS:    
I CC:        cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
I CXX:       g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

make: 对“default”无需做任何事。

我不确认编译是否有问题或者编译成功了，但是后续的转化和推理命令是能运行的，但是推理的回答非常奇怪，经常带上[INST]这样的标签，还重复回答等等，比较乱。是不是我这边 make 编译的时候就没有编译好？请问怎么解决呢？

```

### 依赖情况（代码类问题务必提供）

```
#requirements.txt 等环境齐全
#安装了gcc g++ make
```

### 运行日志或截图

```
g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  -Wno-missing-declarations examples/train-text-from-scratch/train-text-from-scratch.cpp ggml.o llama.o common.o k_quants.o ggml-alloc.o -o train-text-from-scratch  
examples/train-text-from-scratch/train-text-from-scratch.cpp: In function ‘ggml_tensor* llama_build_train_graphs(my_llama_model*, ggml_allocr*, ggml_context*, ggml_cgraph*, ggml_cgraph*, ggml_cgraph*, ggml_tensor**, ggml_tensor*, ggml_tensor*, int, int, bool, bool)’:
examples/train-text-from-scratch/train-text-from-scratch.cpp:735:68: warning: ‘kv_scale’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  735 |             struct ggml_tensor * t16_1 = ggml_scale_inplace        (ctx, t16_0, kv_scale);          set_name(t16_1, "t16_1"); assert_shape_4d(t16_1, N, N, n_head, n_batch);
      |                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  examples/convert-llama2c-to-ggml/convert-llama2c-to-ggml.cpp ggml.o llama.o k_quants.o ggml-alloc.o -o convert-llama2c-to-ggml  


………………………………………………

g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  examples/baby-llama/baby-llama.cpp ggml.o llama.o common.o k_quants.o ggml-alloc.o -o baby-llama  
examples/baby-llama/baby-llama.cpp: In function ‘int main(int, char**)’:
examples/baby-llama/baby-llama.cpp:611:78: warning: ‘kv_self.llama_kv_cache::v’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  611 |                 vc = ggml_set_2d(ctx0, vc, Vcur, (   n_ctx)*ggml_element_size(kv_self.v),
      |                                                             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
examples/baby-llama/baby-llama.cpp:1582:27: note: ‘kv_self.llama_kv_cache::v’ was declared here
 1582 |     struct llama_kv_cache kv_self;
      |                           ^~~~~~~
examples/baby-llama/baby-llama.cpp:610:101: warning: ‘kv_self.llama_kv_cache::k’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  610 |                 kc = ggml_set_1d(ctx0, kc, ggml_reshape_1d(ctx0, Kcur, n_embd*N), (ggml_element_size(kv_self.k)*n_embd)*(il*n_ctx + n_past));
      |                                                                                    ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
examples/baby-llama/baby-llama.cpp:1582:27: note: ‘kv_self.llama_kv_cache::k’ was declared here
 1582 |     struct llama_kv_cache kv_self;
      |                           ^~~~~~~
g++ -I. -Icommon -D_XOPEN_SOURCE=600 -D_GNU_SOURCE -DNDEBUG -DGGML_USE_K_QUANTS  -std=c++11 -fPIC -O3 -Wall -Wextra -Wpedantic -Wcast-qual -Wmissing-declarations -Wno-unused-function -Wno-multichar -Wno-format-truncation -Wno-array-bounds -pthread  -march=native -mtune=native  examples/beam-search/beam-search.cpp ggml.o llama.o common.o k_quants.o ggml-alloc.o -o beam-search  

```

**Comment by ymcui** [comment]
1. 先执行`make clean`，然后再执行`make`（或者带其他参数的`make`），以生成最新的二进制文件
2. 关于你说效果异常的问题，你应该贴一下运行的**具体命令**，使用了什么模型，输出是什么样的。

**Comment by lckj2009** [comment]
> 1. 先执行`make clean`，然后再执行`make`（或者带其他参数的`make`），以生成最新的二进制文件
> 2. 关于你说效果异常的问题，你应该贴一下运行的**具体命令**，使用了什么模型，输出是什么样的。

Chinese-LLaMA-Alpaca-2的Chinese-LLaMA-2-7B模型，百度网盘下载。据说无需合并。我就直接用llama.cpp的make编译了。Chinese-LLaMA-Alpaca-2里面的chat.sh直接做推理，推理命令 ./chat.sh zh-models/7B/ggml-model-q4_k.gguf '你好'
。推理效果如下：
 [INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

你好 [/INST]  < /SYS>>  这里是系统管理器，你可以在里面找到很多有用的帮助工具和实用程序。
 [INST] 你好
 [/INST]  【Instant】即刻、立即、即时； 【insta-matic】自动机械式； 【instinctive】本能的； 【instrumental】音乐中的乐器； 【instrumentalism】音乐中以乐器为主，不注重歌词和旋律。 1. （英语）Instant,immediately,instantly,immediately,immediate,immediatly,immediatel,instantaneously,instantaneous,instinctive,instinctual,instrumental,instrumentality,instrumentalism,instrumentally,instrumentation,instrumentalist,instrumentalize,instinctively,instinctuality,instrumen

**Comment by lckj2009** [comment]
chat.sh 内容如下：
#!/bin/bash

# temporary script to chat with Chinese Alpaca-2 model
# usage: ./chat.sh alpaca2-ggml-model-path your-first-instruction

SYSTEM_PROMPT='You are a helpful assistant. 你是一个乐于助人的助手。'
# SYSTEM_PROMPT='You are a helpful assistant. 你是一个乐于助人的助手。请你提供专业、有逻辑、内容真实、有价值的详细回复。' # Try this one, if you prefer longer response.
MODEL_PATH=$1
FIRST_INSTRUCTION=$2

./main -m "$MODEL_PATH" \
--color -i -c 4096 -t 8 --temp 0.5 --top_k 40 --top_p 0.9 --repeat_penalty 1.1 \
--in-prefix-bos --in-prefix ' [INST] ' --in-suffix ' [/INST]' -p \
"[INST] <<SYS>>
$SYSTEM_PROMPT
<</SYS>>

$FIRST_INSTRUCTION [/INST]"
我用的就是这个项目的chat.sh。原封不动，一点没变。我想先问问。1、make编译会不会报我上面那个错误。2、这种回答你们遇到过吗？大概是什么原因？谢谢

**Comment by ymcui** [comment]
我觉得你应该先仔细看看：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#模型选择指引
聊天要用Alpaca，不是LLaMA模型。

**Comment by lckj2009** [comment]
> 我觉得你应该先仔细看看：[https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#模型选择指引](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#%E6%A8%A1%E5%9E%8B%E9%80%89%E6%8B%A9%E6%8C%87%E5%BC%95) 聊天要用Alpaca，不是LLaMA模型。

就是说，我少了合并Alpaca这一步的原因吗？有时候回答中出现的 [INST]是不是有BUG？

**Comment by ymcui** [comment]
你先用正确的模型加载再考虑输出里的[INST]的问题。
前面已经说过了，你应该下载Alpaca模型而不是LLaMA模型。
以下链接里有完整版的Alpaca模型地址，不需要你提到的合并步骤。
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#完整模型下载

**Comment by lckj2009** [comment]
> 你先用正确的模型加载再考虑输出里的[INST]的问题。 前面已经说过了，你应该下载Alpaca模型而不是LLaMA模型。 以下链接里有完整版的Alpaca模型地址，不需要你提到的合并步骤。 [https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#完整模型下载](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#%E5%AE%8C%E6%95%B4%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD)
> 
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/16095339/269557472-b8317dbf-b492-4a71-9f79-af31bfdaf8be.png">



> 你先用正确的模型加载再考虑输出里的[INST]的问题。 前面已经说过了，你应该下载Alpaca模型而不是LLaMA模型。 以下链接里有完整版的Alpaca模型地址，不需要你提到的合并步骤。 [https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#完整模型下载](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#%E5%AE%8C%E6%95%B4%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD)
> 
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/16095339/269557472-b8317dbf-b492-4a71-9f79-af31bfdaf8be.png">

那请问一下，我训练的话是用txt文本文件就行吗？那文本的内容有规定是某种JSON格式吗？还是说随便什么格式甚至是无格式的txt内容都可以？

步骤是：
1、Chinese-Alpaca-2-7B这个模型作为pretrained_model的模型，然后把要训练的txt放在data目录里面。
2、修改run_pt.sh脚本，举点例子：
pretrained_model=pretrained_model路径
chinese_tokenizer_path=pretrained_model/tokenizer路径
dataset_dir=txt文件路径(第一次的话在Chinese-LLaMA-Alpaca-2下新建一个文件夹)
data_cache=data_cache路径(第一次的话在Chinese-LLaMA-Alpaca-2下新建一个文件夹)
per_device_train_batch_size=1
gradient_accumulation_steps=1
output_dir=输出训练好的模型的路径
block_size=512

这个配置对吧？
3、训练好之后，就是推理了，如果是使用transformers进行推理，可以选择是否和 Chinese-Alpaca-2-LoRA-7B 模型合并后推理吧？那 Chinese-Alpaca-2-7B 训练之后的模型，能不能用 llama.cpp的方式部署呢？如果可以的话，该是怎样的流程？

麻烦解答一下，谢谢！

**Comment by ymcui** [comment]
1. 这位同学你自己再好好看看wiki吧，你问的问题基本都是有相应文档支持的。
2. 有一些基本概念的东西我们也没有精力一个一个去解释（比如你的第三个问题），建议你先学习相应的基础知识再使用，否则你训出来了也是不能用的模型，还浪费算力。比如你想在alpaca上做预训练这个事情是否合理（alpaca上建议是做指令精调）。
3. 最后这个lora合并也是，没有这么用的。所以，我建议是先补充基础知识，了解来龙去脉再用。
