### ISSUE TITLE
我用原始的Chinese-LLaMA-2-7B去合并Chinese-LLaMA-2-LoRA-7B，一推理就乱字符，请问怎么解决

### ISSUE THREAD

**Issue by lckj2009** [ymcui/Chinese-LLaMA-Alpaca-2#307]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# Chinese-LLaMA-2-LoRA-7B合并Chinese-LLaMA-2-LoRA-7B，然后用llama.cpp去推理，结果就错乱字符了。
```

### 依赖情况（代码类问题务必提供）

```
# 官网的https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/manual_conversion_zh合并流程，然后用llama.cpp去推理。环境都是按照官网去安装的。
```

### 运行日志或截图

```
推理情况如下：
#  [INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

你好 [/INST] 的的 ； ； ！
 [INST] 西双版纳在哪里
 [/INST]的； ？ ？ ？
 [INST] 

```

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#lora模型下载
这里写的很清楚了，表里的LoRA是要和原版llama合并，不是和Chinese-LLaMA-2合并。

https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/manual_conversion_zh#step-1-获取原版llama-2-hf模型
这里也已经写的很清楚了，你还是再好好看看教程吧。

**Comment by ymcui** [comment]
**完整版模型不需要和LoRA合并。**
这一贴就关闭了，有问题你在之前的那个issue里继续提。
