### ISSUE TITLE
求处理后的用于预训练的txt格式的中文数据集，可以给个数据集全集或者部分子集的下载地址嘛？

### ISSUE THREAD

**Issue by qianghuangwhu** [ymcui/Chinese-LLaMA-Alpaca-2#311]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

求处理后的用于预训练的txt格式的中文数据集，可以给个数据集全集或者部分子集的下载地址嘛？

### 依赖情况（代码类问题务必提供）

求处理后的用于预训练的txt格式的中文数据集，可以给个数据集全集或者部分子集的下载地址嘛？

### 运行日志或截图

求处理后的用于预训练的txt格式的中文数据集，可以给个数据集全集或者部分子集的下载地址嘛？

**Comment by ymcui** [comment]
预训练数据暂不开源。自己在github里找找吧，有很多公开可用的中文语料。
文件格式方面就是普通的txt。

**Comment by qianghuangwhu** [comment]
好的，感谢回复！

Yiming Cui ***@***.***> 于2023年9月25日周一 08:17写道：
