### ISSUE TITLE
增加数据进行模型微调训练正确逻辑流程

### ISSUE THREAD

**Issue by lower01** [ymcui/Chinese-LLaMA-Alpaca-2#318]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

如果增加自己的数据进行微调，又想让模型适合对话交互
是应该基于Chinese-llama2模型进行增量预训练然后合并，然后用同一份数据转为指令模板的格式，再进行指令精调训练再合并？
还是直接基于Chinese-AIpaca2用有格式的数据进行指令精调训练就行了呢？
看在之前别的问题中说是使用Chinese-AIpaca2进行预训练是不合理的，会产生mismatch，让其丢失原有的对话能力

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
直接在Alpaca上进行预训练（非指令精调）是会失去一些对话能力的。
如果最终的目的是要做对话，有条件的话还是建议在Alpaca上进行指令精调。
如果手头有现成的指令数据自然是最好。如果都是纯文本数据，那就要思考怎么转化为指令形式。这里说的“转化”指的不是生搬硬套把数据改为指令形式，而是要考虑将数据转换为真正的指令数据，包括指令的多样性、格式等。

**Comment by lower01** [comment]
> 直接在Alpaca上进行预训练（非指令精调）是会失去一些对话能力的。 如果最终的目的是要做对话，有条件的话还是建议在Alpaca上进行指令精调。 如果手头有现成的指令数据自然是最好。如果都是纯文本数据，那就要思考怎么转化为指令形式。这里说的“转化”指的不是生搬硬套把数据改为指令形式，而是要考虑将数据转换为真正的指令数据，包括指令的多样性、格式等。

崔老师，对于指令精调任务，是让模型在学习到数据知识和特征的同时还能够学习指令？还是单纯学习指令回复模式，并不像增量预训练一样可以学习到数据的知识和特征？
