### ISSUE TITLE
预训练的输入数据量级和实际训练量级会相差很大？

### ISSUE THREAD

**Issue by zhangjiawei5911** [ymcui/Chinese-LLaMA-Alpaca-2#319]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

输入的数据是：
l运行log： Generating train split: 1118887 examples，共1118887
但是实际训练的数据是
运行log： Num train_samples  651064
而在训练脚本中，validation_split_percentage=0.001
也就是说除去作为验证集的数据，还有40多万的数据没有参与训练，想问下这是什么原因？会不会可能是因为这40多万的数据的token长度大于1024(我设置的block size)，所以未参与训练

**Comment by Lyu6PosHao** [comment]
我也想问这个问题。实际的处理应该是把所有samples拼起来，然后按block_size切块。

**Comment by iMountTai** [comment]
说明你的文本中短文本较少，拼起来切块后导致平均两个文本凑成一个sample。
