### ISSUE TITLE
使用 text generation web ui 部署 chinese-alpaca-2-7b-16k-hf 模型，AI 回复乱码

### ISSUE THREAD

**Issue by librame** [ymcui/Chinese-LLaMA-Alpaca-2#321]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

如题，电脑硬件环境是：9900K+32GB+3060 12G，系统是：RockyLinux 9.2+Python 3.9，第一次遇到 AI 回复乱码是啥情况？

### 依赖情况（代码类问题务必提供）

    # pip list | grep -E 'transformers|peft|torch|sentencepiece|bitsandbytes'
    peft                         0.5.0
    sentencepiece                0.1.99
    torch                        2.0.1
    transformers                 4.33.3

### 运行日志或截图

![屏幕截图 2023-10-03 084709](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/10363349/df9b9891-7b4c-4281-a0f3-e7430cc93c37)

**Comment by FWorldCodeZ** [comment]
你好,你的问题解决了吗

**Comment by librame** [comment]
> 你好,你的问题解决了吗

没有，时间有限，我换另一个AI项目部署了。
