### ISSUE TITLE
TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'

### ISSUE THREAD

**Issue by xiaowuzicode** [ymcui/Chinese-LLaMA-Alpaca-2#326]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Windows

### 详细描述问题

无

### 依赖情况（代码类问题务必提供）

无

### 运行日志或截图

2023-10-08 11:36:45,221 - ERROR - Exception in ASGI application
TypeError: xformers_forward() got an unexpected keyword argument 'padding_mask'

**Comment by Yeuoly** [comment]
请问解决了吗

**Comment by JackZhangY** [comment]
可能是transformers的版本问题，替换成requirement里的4.31.0版本

**Comment by lizhongv** [comment]
`def xformers_forward(
    self,
    hidden_states: torch.Tensor,
    attention_mask: Optional[torch.Tensor] = None,
    position_ids: Optional[torch.LongTensor] = None,
    past_key_value: Optional[Tuple[torch.Tensor]] = None,
    output_attentions: bool = False,
    use_cache: bool = False,
    padding_mask: Optional[torch.Tensor] = None,
) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
    bsz, q_len, _ = hidden_states.size()`

由于 新的transformers中的modeling_llama.py的LlamaAttention()中新加了 padding_mask参数
`  # Self Attention
        hidden_states, self_attn_weights, present_key_value = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            padding_mask=padding_mask,
        )`

所以在attn_and_long_ctx_patches.py的def xformers_forward()参数中添加 padding_mask参数就ok了

**Comment by lizhongv** [comment]
```python
def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Tuple[torch.Tensor]] = None,
        output_attentions: bool = False,
        use_cache: bool = False,
        padding_mask: Optional[torch.LongTensor] = None,
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
```
新的transformers中的LlamaAttention参数中新增padding_mask, 所以在attn_and_long_ctx_patches.py的xformers_forward中添加参数padding_mask
```python
def xformers_forward(
    self,
    hidden_states: torch.Tensor,
    attention_mask: Optional[torch.Tensor] = None,
    position_ids: Optional[torch.LongTensor] = None,
    past_key_value: Optional[Tuple[torch.Tensor]] = None,
    output_attentions: bool = False,
    use_cache: bool = False,
    padding_mask: Optional[torch.Tensor] = None,
) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
```
