### ISSUE TITLE
关于数据集的随机性

### ISSUE THREAD

**Issue by nuoma** [ymcui/Chinese-LLaMA-Alpaca-2#336]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

你好！

我对于数据集的随机性有一个疑问。假设我有若干个domain：论文，悟道，法律。我在处理训练数据集时，为了方便，3个domain形成了3个比较大的.txt文件（每个1G）。我会有点担心如果dataset在处理的时候是按照顺序来的，会出现3个domain的语料是有先后的顺序进行训练的。

翻了一下代码，原始的dataset经过tokenize了以后，会按照chunk进行group。grouped text使用train_test_split()，分出train部分，而随机化是在这里进行的。不知道这样理解对吗？谢谢

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by airaria** [comment]
是的，这里会进行一次随机化；此外在Trainer内部训练时也会对train_dataset再进行一次随机化

**Comment by nuoma** [comment]
谢谢！
