### ISSUE TITLE
你好，请问这里说的指令精调和RLHF事一个东西吗

### ISSUE THREAD

**Issue by QJShan** [ymcui/Chinese-LLaMA-Alpaca-2#34]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by ymcui** [comment]
不是。RLHF是指令精调（SFT）之后的步骤。
本项目相关模型暂不包含这一步。

**Comment by QJShan** [comment]
> 不是。RLHF是指令精调（SFT）之后的步骤。 本项目相关模型暂不包含这一步。

那readme中说的指令精调相比用120G中文语料库进行训练的区别是什么。是指令精调中的数据质量更高吗。

**Comment by ymcui** [comment]
120G无标注数据训练出来的是基座模型，不是用来直接对话的。指令精调是在基座模型的基础上进一步用有标注指令进行训练，使之更适合指令理解和对话。

更详细的细节建议你参考InstructGPT或者Llama-2等经典大模型的技术框架。
