### ISSUE TITLE
windows10, cmake 编译报错

### ISSUE THREAD

**Issue by ewwerpm** [ymcui/Chinese-LLaMA-Alpaca-2#341]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Windows

### 详细描述问题

```
D:\myProgram\ideaJava\yiZhiXiangMuZu\llama\llama.cpp\llama.cpp\build>cmake --build . --config Release
```

### 依赖情况（代码类问题务必提供）

运行 cmake .. 后，似乎没有报错，但是运行  cmake --build . --config Release 后，报错，怎么回事呢？谢谢
 

### 运行日志或截图

![M{}AZU8%SW@`U`LD1Y F{S2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/25223652/704add33-3a9d-4012-b22b-1b50daf9e113)

**Comment by ewwerpm** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/25223652/5b0a6758-317a-4086-90e2-bb486acf0232)
cmake .. ,  有报错，是问题的原因吗？谢谢

**Comment by ymcui** [comment]
windows下的问题实在是无能为力，你可以去llama.cpp那边用出错的那一条文本进行检索看看有没有其他人出现类似的问题。

**Comment by ewwerpm** [comment]
谢谢，我用make编译成功了（不过要下载一个exe软件），就不用cmake了
