### ISSUE TITLE
v100显卡, 开启vllm与不开启, 相同prompt下, 结果不一致

### ISSUE THREAD

**Issue by neal668** [ymcui/Chinese-LLaMA-Alpaca-2#344]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
分别执行以下代码, 通过交互方式输入内容
python3 scripts/inference/inference_hf.py --base_model chinese-alpaca-2-lora-13b --with_prompt --interactive --use_vllm
和
python3 scripts/inference/inference_hf.py --base_model chinese-alpaca-2-lora-13b --with_prompt --interactive

对inference_hf.py中, 第109行做了改动, 新增dtype='float16',
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
`--base_model `输入的是lora还是合并后的模型？如果是合并后的模型，是自己合并的还是直接下载的全量权重

**Comment by Lyu6PosHao** [comment]
可能是解码策略的问题，generation_config

**Comment by tkone2018** [comment]
@neal668 你好，请问你解决了吗
