### ISSUE TITLE
合并 chinese-alpaca-2-lora-7b 模型后，存在推理无法正常显示的问题

### ISSUE THREAD

**Issue by tanghui315** [ymcui/Chinese-LLaMA-Alpaca-2#352]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

未做任何微调，下载链接里面的chinese-llama-2-7b-16k 和 chinese-alpaca-2-lora-7b-16k 模型，如图，无法正确回答任何问题。同样测了 chinese-llama-2-7b 和  chinese-alpaca-2-lora-7b 也是一样的问题， 合了模型推理也一样有问题。

只有单用chinese-alpaca-2-7b 模型推理是没问题的。  我怀疑 7b 模型 的lora 模型存在问题。单独测了基础模型模型没问题，合并了alpaca-2-lora就存在推理问题了。还请作者自己查证一下。 测了之前老的llama-1 的模型，没有问题。 

### 依赖情况（代码类问题务必提供）

chinese-llama-2-7b-16k 
chinese-alpaca-2-lora-7b-16k 
chinese-llama-2-7b-16k 
chinese-alpaca-2-lora-7b-16k 

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/2942609/0d45ba96-eac2-4ce2-a702-0aa85c805732)

**Comment by iMountTai** [comment]
`chinese-llama-2-7b-16k`本身就是已经合并过的模型，不需要再合并了。

**Comment by tanghui315** [comment]
> `chinese-llama-2-7b-16k`本身就是已经合并过的模型，不需要再合并了。

chinese-llama-2-7b-16k 不是一个基座模型吗， 我要指令微调的不是要合 alpaca lora 模型吗？

**Comment by iMountTai** [comment]
参考[完整模型下载](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#完整模型下载)

**Comment by tanghui315** [comment]
> 参考[完整模型下载](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#%E5%AE%8C%E6%95%B4%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD)

问下，Chinese-LLaMA-2-LoRA 和 Chinese-Alpaca-2-LoRA 有什么区别？

**Comment by tanghui315** [comment]
> > 参考[完整模型下载](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#%E5%AE%8C%E6%95%B4%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD)
> 
> 问下，Chinese-LLaMA-2-LoRA 和 Chinese-Alpaca-2-LoRA 有什么区别？

我明白你的意思了， 等于 Chinese-LLaMA-Alpaca-2 和第一版有所不同， 不能通过基座模型 合并指令lora 得到指令模型。

**Comment by tanghui315** [comment]
> > > 参考[完整模型下载](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2#%E5%AE%8C%E6%95%B4%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD)
> > 
> > 
> > 问下，Chinese-LLaMA-2-LoRA 和 Chinese-Alpaca-2-LoRA 有什么区别？
> 
> 我明白你的意思了， 等于 Chinese-LLaMA-Alpaca-2 和第一版有所不同， 不能通过基座模型 合并指令lora 得到指令模型。

我这样理解对吗？

**Comment by iMountTai** [comment]
不全对，可参考 [常见问题](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/faq_zh)。因为第二版可商用，所以我们既提供了合并LoRA后的完整模型，也提供了可与基底模型合并的LoRA权重，具体信息查看readme及相关wiki吧。
