### ISSUE TITLE
请教一下Chinese-Alpaca-2继续训练lora的问题

### ISSUE THREAD

**Issue by Agreewithu** [ymcui/Chinese-LLaMA-Alpaca-2#356]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

作者您好，在Chinese-Llama-Alpaca的一期项目中，Chinese-Alpaca-Plus的模型是基于Chinese-Llama-Plus经过SFT得到的，继续训练Chinese-Alpaca-Plus的lora权重预训练模型需要使用Chinese-Llama-Plus。在二期项目中，我看到项目主页的README中写，Chinese-Alpaca-2是基于Chinese-Llama-2经过SFT得到的，那么为什么继续训练Chinese-Alpaca-2的lora权重预训练模型是Llama2呢？（Wiki中是这么写的，如图所示）希望得到您的解答。
![1697769269908](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/86297268/5d69754f-8d17-4d8d-9d09-130f80d6460e)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by airaria** [comment]
一期项目中alpaca是在合并后的chinese-llama的基础上训新的lora，
二期项目中alpaca是接着chinese-llama的lora继续训练

**Comment by Agreewithu** [comment]
> 一期项目中alpaca是在合并后的chinese-llama的基础上训新的lora， 二期项目中alpaca是接着chinese-llama的lora继续训练

感谢解答
