### ISSUE TITLE
词表扩充后的模型合并

### ISSUE THREAD

**Issue by lyq080700** [ymcui/Chinese-LLaMA-Alpaca-2#360]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

您好，我自己基于chinese_llama2进行了词表扩充，然后进行了预训练，预训练出来后对话能力不强的，所以需要指令微调，但我想合并现有的chinese_alpaca_lora_7B这个权重再去指令微调，再合并自己微调后的权重，这样可以吗，但我试过之后因为词表扩充的步骤，词表大小不一致所以合并不成功，到SFT的话就会报这个错误：
**RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
size mismatch for base_model.model.model.embed_tokens.weight: copying a param with shape torch.Size([49954, 4096]) from checkpoint, the shape in current model is torch.Size([58353, 4096]).**
请问一下这个问题要怎么解决呢，感谢回答！！！

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```
谢谢

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
谢谢

**Comment by clclclaiggg** [comment]
我也出现这个问题，好像需要resize-embedding-size步骤，但是不知道具体怎么解决

**Comment by ymcui** [comment]
```
我想合并现有的chinese_alpaca_lora_7B这个权重再去指令微调，再合并自己微调后的权重，这样可以吗，
```
不可以。lora和对应的基模型是有绑定关系的。
不能理解为像积木一样把这个lora加到你的模型就能得到对话能力了。

**Comment by lyq080700** [comment]
> ```
> 我想合并现有的chinese_alpaca_lora_7B这个权重再去指令微调，再合并自己微调后的权重，这样可以吗，
> ```
> 
> 不可以。lora和对应的基模型是有绑定关系的。 不能理解为像积木一样把这个lora加到你的模型就能得到对话能力了。

好的，非常感谢，那如果要训练自己领域的指令微调模型，就得重新找新的指令数据，再基于自己预训练过的模型重新训练一个全新的模型是吗
