### ISSUE TITLE
llama-7b模型参数有问题，下载时报错，微调时不拟合

### ISSUE THREAD

**Issue by Fuyubai** [ymcui/Chinese-LLaMA-Alpaca-2#361]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

下载时
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/49471258/fea6d9c3-87c0-4532-8d9f-8388782a19a4)

微调时
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/49471258/655090b6-1e91-400a-b450-7c9465863106)

貌似是因为hg上的模型文件太大了导致的bug

**Comment by ymcui** [comment]
第一个图并不是报错。另外如果你从HF下载模型，可以在对应页面找到文件的SHA256，看看是否下载完整。
