### ISSUE TITLE
多次進行微調

### ISSUE THREAD

**Issue by Naozumi520** [ymcui/Chinese-LLaMA-Alpaca-2#364]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

不知道能多次進行微調嗎？我在這樣操作後出現了對話能力差的問題

例如第一次微調增加了廣東話能力，之後再微調增加角色資訊，這樣操作下來對話能力變得極差。但是第一次只微調其廣東話能力時候其對話能力是非常正常的。

**Comment by iMountTai** [comment]
多次微调不排除会出现灾难性遗忘的问题，可能需要调整lr、total_bachsize等超参
