### ISSUE TITLE
chinese-alpace-2-7b推理时，为什么要先输出一遍问题再回答？

### ISSUE THREAD

**Issue by sun1092469590** [ymcui/Chinese-LLaMA-Alpaca-2#37]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

chinese-alpace-2-7b部署在Linux，在jupyter中推理时，为什么要先输出一遍问题再回答？
推理代码如下：
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
from transformers import GenerationConfig
from peft import  PeftModel

generation_config = GenerationConfig(
    repetition_penalty=1.1,
    max_new_tokens=400
)

model_path='/home/chinese-alpace-2-7b'

tokenizer = LlamaTokenizer.from_pretrained(model_path, legacy=True)
model = LlamaForCausalLM.from_pretrained(
        model_path,
        load_in_8bit=False,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        device_map='auto',
        )
model.eval()

input_text='中国法定货币是什么？'
inputs = tokenizer(input_text,return_tensors="pt")
generation_output = model.generate(
                    input_ids = inputs["input_ids"].to('cuda:0'),
                    attention_mask = inputs['attention_mask'].to('cuda:0'),
                    eos_token_id=tokenizer.eos_token_id,
                    pad_token_id=tokenizer.pad_token_id,
                    generation_config = generation_config
                )
s = generation_output[0]
output = tokenizer.decode(s,skip_special_tokens=True)
print(output)

输出output：中国法定货币是什么？人民币。中国法定货币是人民币，简称RMB或CNY（Chinese National Currency）。

**Comment by ymcui** [comment]
**先把issue上下文补充完整，用的什么脚本预测的，运行命令是什么。**

**Comment by sun1092469590** [comment]
> **先把issue上下文补充完整，用的什么脚本预测的，运行命令是什么。**

补充了我的推理代码，您再看一下

**Comment by ymcui** [comment]
因为alpaca-2是有指令模板的，并不是直接把text丢给模型，外面还要包一些东西。
你如果要用自己的预测脚本就参考[inference_hf.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/inference/inference_hf.py)改一下吧。

**Comment by sun1092469590** [comment]
> 因为alpaca-2是有指令模板的，并不是直接把text丢给模型，外面还要包一些东西。 你如果要用自己的预测脚本就参考[inference_hf.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/inference/inference_hf.py)改一下吧。

我这个推理代码其实就是参考的你这个脚本，只把里面的推理部分剥离出来了，没有使用TEMPLATE。我再看一下代码试一下，谢谢哈。

**Comment by musellama** [comment]
> 因为alpaca-2是有指令模板的，并不是直接把text丢给模型，外面还要包一些东西。 你如果要用自己的预测脚本就参考[inference_hf.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/inference/inference_hf.py)改一下吧。

是不是说 alpaca2 在预训练的时候是有指令 模板的，并不是跟 alpaca1 一样直接吧 txt 丢进去进行训练？

**Comment by airaria** [comment]
> 是不是说 alpaca2 在预训练的时候是有指令 模板的，并不是跟 alpaca1 一样直接吧 txt 丢进去进行训练？

alpaca1和alpaca2在精调时都有模版
没有模版的时llama1和llama2

**Comment by musellama** [comment]
> > 是不是说 alpaca2 在预训练的时候是有指令 模板的，并不是跟 alpaca1 一样直接吧 txt 丢进去进行训练？
> 
> alpaca1和alpaca2在精调时都有模版 没有模版的是llama1和llama2

好的明白了 预训练就是跟以前一样是纯TXT文本，alpaca精调的时候是。 资料里边提供的格式
[
  {"instruction" : ...,
   "input" : ...,
   "output" : ...},
  ...
]

**Comment by YuqiNWang** [comment]
但是我用llama2和alpaca2的时候，都出现了输出的问题。

**Comment by airaria** [comment]
> 问题似乎解决了，将输入字符串尾部加上\n
> 
> =====================================
> 
> 但是我用llama2和alpaca2的时候，都出现了输出的问题。 eg: tokenizer = AutoTokenizer.from_pretrained("llama2-7b-zh", trust_remote_code=True) model = LlamaForCausalLM.from_pretrained("llama2-7b-zh", trust_remote_code=True).half().to('mps') model = model.eval()
> 
> inputs = tokenizer("你好", return_tensors="pt") generation_output = model.generate( input_ids = inputs["input_ids"].to('mps'), attention_mask = inputs['attention_mask'].to('mps'), eos_token_id=tokenizer.eos_token_id, pad_token_id=tokenizer.pad_token_id, generation_config = generation_config ) s = generation_output[0] output = tokenizer.decode(s,skip_special_tokens=True)
> 
> 输出的是这样的东西： 你好，我是来自四川的一名高三学生。我今年18岁，身高175cm体重60kg，体脂率24%，胸围93cm腰围75cm臀围90cm大腿围50cm小腿围30cm。请问我的身材属于什么类型？需要增肌吗？如何增肌？谢谢！谢邀 题主是典型的瘦长型身材，也就是所谓的"筷子腿"，这种身材在女生中很常见，但是男生比较少见。因为这类人普遍肌肉量较少，所以看起来比较瘦弱。不过从你的数据来看，你确实有潜力可以练出一身肌肉来。首先你要明白一点：健身不是减肥，而是为了塑造一个健康的身体和良好的体型。如果你只是单纯地想要减脂的话，那么建议你先去跑步或者游泳等低强度运动上消耗掉多余脂肪再考虑增肌问题。如果只是想要增肌的话
> 
> 同时，使用example的测试样例（翻译任务）时候，会直接原文返回

1. 这像是llama模型的输出特征，alpaca模型正常使用的话不会有这样的输出。
2. 如果是alpaca模型，例子里也并没有使用指令模版

**Comment by YuqiNWang** [comment]
> > 问题似乎解决了，将输入字符串尾部加上\n
> > =====================================
> > 但是我用llama2和alpaca2的时候，都出现了输出的问题。 eg: tokenizer = AutoTokenizer.from_pretrained("llama2-7b-zh", trust_remote_code=True) model = LlamaForCausalLM.from_pretrained("llama2-7b-zh", trust_remote_code=True).half().to('mps') model = model.eval()
> > inputs = tokenizer("你好", return_tensors="pt") generation_output = model.generate( input_ids = inputs["input_ids"].to('mps'), attention_mask = inputs['attention_mask'].to('mps'), eos_token_id=tokenizer.eos_token_id, pad_token_id=tokenizer.pad_token_id, generation_config = generation_config ) s = generation_output[0] output = tokenizer.decode(s,skip_special_tokens=True)
> > 输出的是这样的东西： 你好，我是来自四川的一名高三学生。我今年18岁，身高175cm体重60kg，体脂率24%，胸围93cm腰围75cm臀围90cm大腿围50cm小腿围30cm。请问我的身材属于什么类型？需要增肌吗？如何增肌？谢谢！谢邀 题主是典型的瘦长型身材，也就是所谓的"筷子腿"，这种身材在女生中很常见，但是男生比较少见。因为这类人普遍肌肉量较少，所以看起来比较瘦弱。不过从你的数据来看，你确实有潜力可以练出一身肌肉来。首先你要明白一点：健身不是减肥，而是为了塑造一个健康的身体和良好的体型。如果你只是单纯地想要减脂的话，那么建议你先去跑步或者游泳等低强度运动上消耗掉多余脂肪再考虑增肌问题。如果只是想要增肌的话
> > 同时，使用example的测试样例（翻译任务）时候，会直接原文返回
> 
> 1. 这像是llama模型的输出特征，alpaca模型正常使用的话不会有这样的输出。
> 2. 如果是alpaca模型，例子里也并没有使用指令模版

麻烦问一下，alpaca模型的模版是在./prompts/下面的那两个txt吗？
“你是一个乐于助人的助手。请你提供专业、有逻辑、内容真实、有价值的详细回复。”——这个看起来不太像。

**Comment by airaria** [comment]
txt里的是system prompt。
模版的格式见推理脚本：
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/b6aee5b8c6608dbc85f7754bb2f13193273857ce/scripts/inference/inference_hf.py#L6-L11
