### ISSUE TITLE
部署chinese-alpaca-2-7b-hf提示“ If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True”

### ISSUE THREAD

**Issue by minmie** [ymcui/Chinese-LLaMA-Alpaca-2#374]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
按照 这个链接进行部署：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/inference_with_transformers_zh

执行这个命令后报错
python scripts/inference/gradio_demo.py --base_model /home/chenjq/model/chinese-alpaca-2-7b-hf

```
使用的模型：
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/44903ad5-70e4-41e7-af5b-2887bf2bdcf1)

### 依赖情况（代码类问题务必提供）

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/61223687-dd80-4d32-a454-bd2587921722)

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/7f27e38c-70c0-4067-bf81-35d9c3352f94)

**Comment by ymcui** [comment]
图片不要放在代码块里，显示不出来，你重新编辑一下吧。

**Comment by ymcui** [comment]
`/home/chenjq/model/chinese-alpaca-2-7b-hf`目录下是什么文件？`ls`一下？

**Comment by minmie** [comment]
> 图片不要放在代码块里，显示不出来，你重新编辑一下吧。
@ymcui  重新修改了

**Comment by minmie** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/e4f5d0f9-5b9e-4712-898a-3be2ebe492f0)
@ymcui

**Comment by ymcui** [comment]
是从哪里下载的？你看看bin文件的SHA256是否和`SHA256.md`里的一致？

**Comment by minmie** [comment]
从这里下载的
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/cbb149d7-8fde-4c1f-9fe2-ef04b9d71f1e)

sha256不一样
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/40080081/2e26c59a-08b7-4965-bd78-59a3efd5aa10)


@ymcui

**Comment by ymcui** [comment]
有可能你下载的不完整，你可以重新下载试试或者从其他链接下载。

**Comment by minmie** [comment]
确实是模型问题，重新下载已解决
