### ISSUE TITLE
chinese-alpaca-2-13b-16k 长文本训练过程咨询

### ISSUE THREAD

**Issue by zx4321** [ymcui/Chinese-LLaMA-Alpaca-2#375]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
在Code Llama中，通过设置rope_theta来让长文本的效果更好，请问当前chinese-alpaca-2-13b-16k训练过程中修改了这个参数吗？
"rope_theta": 1000000（https://huggingface.co/codellama/CodeLlama-7b-hf/blob/main/config.json）
```
https://scontent-hkt1-2.xx.fbcdn.net/v/t39.2365-6/369856151_1754812304950972_1159666448927483931_n.pdf?_nc_cat=107&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=yHzAghoBhMQAX8GuEYS&_nc_ht=scontent-hkt1-2.xx&oh=00_AfDTA9ubVw-yP_LkldI2QdMuCfhaKtoiO7VLDl_-W3EQfg&oe=6543B50F

### 依赖情况（代码类问题务必提供）

```
无
```

### 运行日志或截图

```
无
```

**Comment by iMountTai** [comment]
参考 (release 3.0](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/releases/tag/v3.0)
