### ISSUE TITLE
alpaca2-7b模型推理阶段报错：OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by promisecc** [ymcui/Chinese-LLaMA-Alpaca-2#378]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
alpaca2-7b模型推理阶段报错：OSError: [Errno 9] Bad file descriptor
已通过merge_llama2_with_chinese_lora_low_mem.py脚本合并模型，运行环境为Linux服务器上
```

### 依赖情况（代码类问题务必提供）

```

```

### 运行日志或截图

<img width="1370" alt="截屏2023-10-31 17 12 56" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/48479576/d909c098-e585-417f-bb7b-a9bd855eb7eb">

**Comment by ymcui** [comment]
自己在搜索引擎里搜一下错误信息吧。
你这也没个运行命令，不清楚你跑的是什么模型。
看你的描述像是自己训了一个模型，用我们的代码去做inference。这种情况你要先排查用我们原版的模型做inference会不会出现这个问题，然后再看是不是因为你tune的有问题。
