### ISSUE TITLE
建议增加扩充词表的数量

### ISSUE THREAD

**Issue by twang2218** [ymcui/Chinese-LLaMA-Alpaca-2#4]
在之前的 Chinese-LLaMA-Alpaca 的工作中，词表的数量增加了1万多，其中有相当比例是多字词，总词量达到了 49954。其中汉字主要覆盖了最基本的繁简常用字，

| ![](https://github.com/twang2218/vocab-coverage/blob/main/images/empty.png?raw=true)汉字覆盖率 |![](https://github.com/twang2218/vocab-coverage/blob/main/images/empty.png?raw=true) 输入端词向量分布图 |
|-------|--------|
|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/shibing624_chinese-alpaca-plus-7b-hf.coverage.png?raw=true)|![](https://github.com/twang2218/vocab-coverage/blob/main/images/embeddings/shibing624_chinese-alpaca-plus-7b-hf.embeddings.input.jpg?raw=true)|

但是，这2万词表扩充或许过于保守了。

我观察其他多语言模型，在词表的扩充上都要更大一个量级，如

### BERT 类模型

- `bert-base-multilingual-cased`: **12万**
- `xlm-roberta-base`：**25万**。

|          |          |
|------|------|
|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/bert-base-multilingual-cased.coverage.png?raw=true)|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/xlm-roberta-base.coverage.png?raw=true)|

### 中文大语言模型

- THUDM/chatglm-6b: **13万**
- THUDM/chatglm2-6b: **6万**
- BAAI/aquila-7b: **10万**
- fnlp/moss-moon-003-sft: **10.6万**
- baichuan-int/baichuan-7b: **6万**

|          |          |
|------|------|
|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/THUDM_chatglm-6b.coverage.png?raw=true)|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/THUDM_chatglm2-6b.coverage.png?raw=true)|
|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/fnlp_moss-moon-003-sft.coverage.png?raw=true)|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/baichuan-inc_baichuan-7B.coverage.png?raw=true)|
|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/BAAI_aquila-7b.png?raw=true)||

### 国外大语言模型

- bigscience/bloom-7b1: **25万**
- mosaicml/mpt-7b-instruct: **5万**
- tiiuae/falcon-7b-instruct: **6.5万**

|          |          |          |
|------|------|------|
|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/bigscience_bloom-7b1.coverage.png?raw=true)|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/mosaicml_mpt-7b-instruct.coverage.png?raw=true)|![](https://github.com/twang2218/vocab-coverage/blob/main/images/coverage/tiiuae_falcon-7b-instruct.coverage.png?raw=true)|

因此希望模型在为中文扩表的时候，能够更多一些，比如将词表扩充到10万～20万的级别。

**Comment by ymcui** [comment]
你的这个repo我之前看过了，会考虑，谢谢。
