### ISSUE TITLE
resize_token_embeddings 相关的疑惑

### ISSUE THREAD

**Issue by AriKing11** [ymcui/Chinese-LLaMA-Alpaca-2#400]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
    if model_vocab_size != len(tokenizer):
        logger.info(f"Resize model vocab size to {len(tokenizer)}")
        model.resize_token_embeddings(len(tokenizer))
```
我有一点小困惑, 就是如果使用了resize_token_embeddings 在model中的embedding层多加了一行向量, 但是这个向量并没有经过训练, 那么如何确保模型不会受这个添加词表影响 使得整体效果变差.

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
是你自己要在词表里多加一个token吗？这么做的目的是什么？
加了token就肯定是要做进一步训练的，原因你自己也讲了（新加的token对应的词向量是随机初始化的）。

非必要不加新token
