### ISSUE TITLE
hf推理

### ISSUE THREAD

**Issue by tkone2018** [ymcui/Chinese-LLaMA-Alpaca-2#410]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
我是用inference_hf.py推理的时候，回答问题的时候回家input的问题列出来
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/41476675/6dd3ac7a-6a94-44d8-8f7b-7f6ce3974803)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/41476675/0b438a3e-73c5-464e-9ebc-909e17fe934e)

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/41476675/9a4f4fce-afb3-4b29-9a2d-30f4ffb58b4a)

**Comment by iMountTai** [comment]
没有复现你的问题
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/35353688/908030c5-581c-4bb8-a105-753d237d6061)

**Comment by tkone2018** [comment]
好吧，我也不知道哪里有啥问题

**Comment by tkone2018** [comment]
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/41476675/1ab4e796-b0f3-466d-8a6f-c19bb7f23795)
我用的这个模型，应该没问题吧

**Comment by tkone2018** [comment]
我用的
Chinese-Alpaca-2-13B这个模型推理没问题吧



<br class="Apple-interchange-newline">
</body>
</html>

**Comment by tkone2018** [comment]
@iMountTai 解决了，是需要将with_prompt参数设置为True,我建议如果是alpaca,改为默认为True
