### ISSUE TITLE
max_seq_length

### ISSUE THREAD

**Issue by Go4miii** [ymcui/Chinese-LLaMA-Alpaca-2#427]
请问max_seq_length是输入长度还是输出长度？

**Comment by ymcui** [comment]
你问的是什么脚本或者代码？没上下文怎么回答。

**Comment by Go4miii** [comment]
> 你问的是什么脚本或者代码？没下文怎么回答。

https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh，这个网站里的训练脚本

**Comment by ymcui** [comment]
训练数据输入长度。具体自行查看相关代码定义：
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/0189e8be7706d2aceb90d238149d5fda6b6aea8d/scripts/training/build_dataset.py#L23
