### ISSUE TITLE
多机多卡微调

### ISSUE THREAD

**Issue by qdchenxiaoyan** [ymcui/Chinese-LLaMA-Alpaca-2#429]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

作者能否完善下多机多卡微调的说明，谢谢~

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by qdchenxiaoyan** [comment]
> [指令微调脚本wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/sft_scripts_zh#%E4%BD%BF%E7%94%A8%E5%A4%9A%E6%9C%BA%E5%A4%9A%E5%8D%A1)中有说明

<img width="401" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/29563875/813942de-efdf-49f6-bb07-82e5cd960126">我是按照这个配置的，如下图：
<img width="289" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/29563875/ada40a15-86e5-43eb-ae1b-7668a8828f7e">
<img width="308" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/29563875/ef945a75-ca51-4c5d-83fb-c8197edfb28d">
我是两台机器，是两台机器分别启动训练么，配置的区别就是node_rank，其他都一样？那启动顺序有没有什么要求呢

**Comment by iMountTai** [comment]
`master_addr`需要指定rank0所在机器的IP，启动顺序不清楚有没有区别，具体可以看一下torchrun的官方文档。

**Comment by qdchenxiaoyan** [comment]
> `master_addr`需要指定rank0所在机器的IP，启动顺序不清楚有没有区别，具体可以看一下torchrun的官方文档。

试了，在设定的通信时间内，启动顺序没要求
