### ISSUE TITLE
对Alpaca2预训练后，回复内容很短

### ISSUE THREAD

**Issue by lry0223** [ymcui/Chinese-LLaMA-Alpaca-2#449]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

在对Alpaca-2模型进行pt预训练并合并原模型后吗，生成的回复非常短，如图。设置max_token或者在prompt中告诉模型尽可能详细回答都没有生效，请问应该如何解决
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/87320095/86ba056f-dd05-45e6-91c9-0ffe0b303fbb)

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
`对Alpaca-2模型进行pt预训练并合并原模型后`得到的应该是一个基底模型，非对话模型，能和你对话说明还具备之前的部分对话能力，但是因为你的训练已经更改了模型的权重，模型的回复会受到什么影响也不好说。可以试试选取回复长度比较长的SFT数据进一步对得到的模型做SFT，观察回复长度。

**Comment by lry0223** [comment]
好的，感谢回答
