### ISSUE TITLE
扩充词汇表是怎样操作的？

### ISSUE THREAD

**Issue by jyC23333** [ymcui/Chinese-LLaMA-Alpaca-2#45]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型转换和合并

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

想问下哪里能获得扩充词汇表相关的内容与代码。

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
可以参考一期项目中的代码[merge_tokenizers.py(https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_tokenizer/merge_tokenizers.py)

**Comment by musellama** [comment]
> 流程和一期一样，可以参考一期项目中的代码[merge_tokenizers.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_tokenizer/merge_tokenizers.py)

词表扩充后训练是不是会影响 最后合并的时候呢？ 比如 原版llmaa 50000左右  扩充完毕 200000左右。合并会报错吧

**Comment by airaria** [comment]
> > 流程和一期一样，可以参考一期项目中的代码[merge_tokenizers.py](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_tokenizer/merge_tokenizers.py)
> 
> 词表扩充后训练是不是会影响 最后合并的时候呢？ 比如 原版llmaa 50000左右 扩充完毕 200000左右。合并会报错吧

合并时会用新词表（55296）替换旧词表（32000）
