### ISSUE TITLE
怎么启动chinese llama

### ISSUE THREAD

**Issue by dongziyu1016** [ymcui/Chinese-LLaMA-Alpaca-2#451]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
 ./main -m zh-models/7B/ggml-model-q4_0.gguf --color -ins -c 2048 --temp 0.2 -n 256 --repeat_penalty 1.3
```
您好，我用这个命令启动llama2-7B模型。但是模型没有生成任何内容
<img width="440" alt="微信图片_20231208150707" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/136042459/4110f838-a3c8-461c-8ad3-2be55ce32c61">

请问是不是我的启动方式不对，我应该怎么办？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
命令没有什么大问题。不排除是你的terminal的问题。另外llama不是用来对话的。

**Comment by dongziyu1016** [comment]
好的，非常感谢
