### ISSUE TITLE
1.3B 模型没有包含 pytorch_model.bin.index.json ，如何在调优后进行合并？

### ISSUE THREAD

**Issue by reterVision** [ymcui/Chinese-LLaMA-Alpaca-2#454]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
  File "/mnt/ai/Chinese-LLaMA-Alpaca-2/scripts/merge_llama2_with_chinese_lora_low_mem.py", line 326, in <module>
    with open(os.path.join(base_model_path, config),'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../chinese-alpaca-2-1.3b/pytorch_model.bin.index.json'
```

**Comment by iMountTai** [comment]
可以直接注释掉[第330-331行](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/0189e8be7706d2aceb90d238149d5fda6b6aea8d/scripts/merge_llama2_with_chinese_lora_low_mem.py#L330)
