### ISSUE TITLE
Model 在 RAG推理中不断重覆生成相同的tokens

### ISSUE THREAD

**Issue by williamyu20** [ymcui/Chinese-LLaMA-Alpaca-2#476]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-Alpaca-2-16K (7B/13B)

### 操作系统

Linux

### 详细描述问题

用Langchain 搭建了一个RAG，并且给model一些從Chatgpt 3.5 生成假的银行开帐户的资料，用llama.cpp作推理。看了Langchain retrieval的output 是没有任何问题的，能output相对应的资料，但model的回应却一直出现重复回覆相同tokens的情况，即使调节了repetition_penalty也没用。这是这个model原本的缺陷吗？ model用的是ggml-model-q8_0.gguf，以下是retrieval 得到的output和model的回应。

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/72000926/1bdc482c-9618-4382-a3ca-89b628646d5b)

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/72000926/3ee0167e-e065-46c6-88f1-8eaf74422e0b)

**Comment by ymcui** [comment]
直接用llama.cpp做推理是否有这个问题？以此来判断是哪个环节出了问题。
