### ISSUE TITLE
DeepSpeed提示Loss scale already at minimum，然后就自动退出。

### ISSUE THREAD

**Issue by leonunix** [ymcui/Chinese-LLaMA-Alpaca-2#486]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Others

### 操作系统

Linux

### 详细描述问题

我在使用数据做训练的时候DeepSpeed提示Loss scale already at minimum然后就自己中断训练了
然后我在下面地址找到一样的问题。最后通过把fp16切换成bf16解决了这个问题。我想问一下。为什么你们训练模型的时候没问题呢？LLama2本身是使用bf16训练的。理论继续训练也应该用bf16才对啊？

https://github.com/microsoft/DeepSpeed/issues/4017

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
我们也是采用的bf16训练，但是因为较多人手里的显卡不支持bf16，所以脚本中都是以fp16显示的。基于我们的模型做少量数据精调一般不会出现`Loss scale `问题，从头预训练出现该问题的可能性比较大。
