### ISSUE TITLE
raylet内存警告，Object creation will fail if spilling is required.请问如何移除警告信息

### ISSUE THREAD

**Issue by ByteCaprice** [ymcui/Chinese-LLaMA-Alpaca-2#491]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

效果问题

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
一运行就报内存警告
(raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-01-04_09-39-43_289383_3199100 is over 95% full, available space: 0; capacity: 1081985105920. Object creation will fail if spilling is required.
很影响体验，请问如何消除
```

### 依赖情况（代码类问题务必提供）

```
vllm版本0.2.1
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
前因后果讲清楚，没明白你这个是运行什么导致的。

**Comment by ByteCaprice** [comment]
> 前因后果讲清楚，没明白你这个是运行什么导致的。
用vllm下的inference_hf.py文件进行推理时产生的，显存快满的时候会不停的警告
