### ISSUE TITLE
ntk上下文扩展

### ISSUE THREAD

**Issue by tkone2018** [ymcui/Chinese-LLaMA-Alpaca-2#494]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

generation_config = GenerationConfig(
        temperature=0.2,
        top_k=40,
        top_p=0.9,
        do_sample=True,
        num_beams=1,
        repetition_penalty=1.1,
        max_new_tokens=30000
    )
推理文件是inference_hf.py，采用ntk扩展，想问下是不是输入还是限制在4096了，请问下ntk是可以扩展输入的上下文吗，还是说我使用ntk后，还需要修改哪些部分才能扩展输入的上下文token数，谢谢
<img width="685" alt="50f65d48fb70cf10b07d418af23e836" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/41476675/9bed2de4-17ee-47b0-a992-5401e39c151c">

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by tkone2018** [comment]
还有就是请教下vllm推理是不是不支持ntk上下文扩展技术

**Comment by iMountTai** [comment]
你`max_new_token`设置的太大，参数不对。而且NTK不是无限扩展，比如原来支持4k长度，NTK可扩展到8-12k。

**Comment by tkone2018** [comment]
@iMountTai 好的，谢谢
