### ISSUE TITLE
仓库里面包含中文词表扩充相关的代码吗

### ISSUE THREAD

**Issue by weiiWill** [ymcui/Chinese-LLaMA-Alpaca-2#497]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

好像没有看到词表扩充相关代码，望指导

**Comment by ymcui** [comment]
一代有合并脚本。词表需要自己用sentencepiece训，教程自己去sentencepiece那边看吧。
合并：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节#准备工作词表扩充

**Comment by weiiWill** [comment]
多谢
