### ISSUE TITLE
Chinese-Alpaca-2的7B指令精调，用作分类，微调的结果accuracy为什么16bit比8bit只高0.001，另外13B模型不升反降？

### ISSUE THREAD

**Issue by feifei05** [ymcui/Chinese-LLaMA-Alpaca-2#498]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# Chinese-Alpaca-2的7B指令精调，用作分类，输出答案在10个中文字以内，微调100epochs的结果accuracy为什么16bit比8bit只高0.001，另外13B模型不升反降，这问题主要从哪些角度考虑？
```

### 依赖情况（代码类问题务必提供）

```
# transformers=4.34.0
# sentencepiece= 0.1.99
```

### 运行日志或截图

```
# 7B的8bit微调100epochs分类任务，测试集结果Class,precision,recall,f1-score,support
weighted avg,0.6490202416435714,0.6545275590551181,0.6430212355260709,2032.0

7B的16bit微调100epochs分类任务，测试集结果Class,precision,recall,f1-score,support
weighted avg,0.6485059628314677,0.655511811023622,0.6441143713844812,2032.0
```

**Comment by ymcui** [comment]
特定任务问题还请自行debug
