### ISSUE TITLE
预训练完美运行，但是保存lora模型为1k

### ISSUE THREAD

**Issue by msn199959** [ymcui/Chinese-LLaMA-Alpaca-2#50]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

drwxr-xr-x 2 root root   4096 Aug  2 15:21 ./
drwxr-xr-x 4 root root   4096 Aug  2 15:21 ../
-rw-r--r-- 1 root root    111 Aug  2 15:21 README.md
-rw-r--r-- 1 root root    592 Aug  2 15:21 adapter_config.json
-rw-r--r-- 1 root root    443 Aug  2 15:21 adapter_model.bin
-rw-r--r-- 1 root root    411 Aug  2 15:21 special_tokens_map.json
-rw-r--r-- 1 root root 844403 Aug  2 15:21 tokenizer.model
-rw-r--r-- 1 root root    747 Aug  2 15:21 tokenizer_config.json

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by iMountTai** [comment]
贴出运行脚本？就一句话不好debug呀
