### ISSUE TITLE
使用flash attention会报错

### ISSUE THREAD

**Issue by Go4miii** [ymcui/Chinese-LLaMA-Alpaca-2#502]
在运行run_sft.sh时使用--flash_attn 会报错：ValueError: Some specified arguments are not used by the HfArgumentParser: ['--flash_attn']    。
请问是什么情况？

**Comment by iMountTai** [comment]
修改为`--use_flash_attention_2 `

**Comment by Go4miii** [comment]
> 修改为`--use_flash_attention_2 `

好的我试试，谢谢！！
