### ISSUE TITLE
关于强化学习

### ISSUE THREAD

**Issue by wuhuanon** [ymcui/Chinese-LLaMA-Alpaca-2#506]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Others

### 操作系统

Linux

### 详细描述问题

warmup_rate 参数是干嘛用的，可不可以不用这个参数训练

**Comment by GeekDream-x** [comment]
这是设置学习率预热的训练步数占比。使用DeepSpeed-Chat训练代码的话可以参考[run_llama2_7b.sh](https://github.com/microsoft/DeepSpeedExamples/blob/master/applications/DeepSpeed-Chat/training/step3_rlhf_finetuning/training_scripts/llama2/run_llama2_7b.sh)使用参数`num_warmup_steps`直接指定预热的步数
