### ISSUE TITLE
load_in_8bit 推理耗时比fp16长

### ISSUE THREAD

**Issue by haoxurt** [ymcui/Chinese-LLaMA-Alpaca-2#516]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

在V100上fp16推理13b模型，显存占用大概30G,耗时3s以内，同样的prompt, 使用int8推理，虽然显存占用明显减少至15G左右，但耗时增加到5s以上

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
bnb的8bit量化只是减少了权重大小，推理速度并不会提升。这种问题可以关注一下transformers或者bitsandbytes原repo下有没有优化方案。
