### ISSUE TITLE
感觉中文答非所问，你们的会有这个问题吗？

### ISSUE THREAD

**Issue by tmpuserx** [ymcui/Chinese-LLaMA-Alpaca-2#52]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

其他问题

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

我从huggingface下载的ziqingyang/chinese-alpaca-2-7b 和ziqingyang/chinese-alpaca-2-lora-7b，通过script目录下面的gradio_demo.py 加载上面下载的模块，由于显卡内存不大，使用了--load_in_8bit选项，在窗口中简单提了几个问题，但是感觉答非所问，是我设置的问题吗？

```
# 请在此处粘贴运行代码（如没有可删除该代码块）

python gradio_demo.py --base_model C:\Users\aa\Downloads\ziqingyang-chinese-alpaca-2-7b --lora_model C:\Users\aa\Downloads\ziqingyang-chinese-alpaca-2-lora-7b --tokenizer_path C:\Users\aa\Downloads\ziqingyang-chinese-alpaca-2-lora-7b --load_in_8bit

```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/39644828/00133c67-ea76-480b-97d8-c6ce01b4c06e)

**Comment by ymcui** [comment]
所以你为啥要加载lora呢……？ base_model已经是完整版模型了

**Comment by tmpuserx** [comment]
诶，我以为两个是要一起用的。。。只用base_model果然就正常多了。谢谢！

**Comment by qianxifu** [comment]
请问使用gradio_demo.py部署的怎么使用http api访问呢？可以多用户同时访问吗|？
