### ISSUE TITLE
“基座模型”和“指令模型”该怎么使用？

### ISSUE THREAD

**Issue by kgdxpr** [ymcui/Chinese-LLaMA-Alpaca-2#522]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

刚接触大模型有个问题帮忙解答一下，在完整模型的列表中分了两个类型“基座模型”和“指令模型”，这两个有什么区别，在使用的时候是选择其中一个用还是两个都要用，在什么场景该用什么类型？谢谢。

**Comment by ymcui** [comment]
请勿重复发帖。
