### ISSUE TITLE
请问本仓库能否基于YaRN进行sft？

### ISSUE THREAD

**Issue by Zheng-Jay** [ymcui/Chinese-LLaMA-Alpaca-2#524]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

感谢贵团队的开源贡献！
YaRN仓库开源了训练代码，但只支持预训练，我想进行sft阶段的外推训练，将instruct版本从4k外推到16k，看到alpaca2仓库日志里写道支持YaRN模型，翻遍了wiki和issue都没找到YaRN训练相关的，是只支持推理而已吗？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
目前仓库内训练代码确实没有适配YaRN训练，可以自行修改代码，而且预训练和SFT阶段只是数据不同，本质上都是CausalLM任务。

**Comment by Zheng-Jay** [comment]
> 目前仓库内训练代码确实没有适配YaRN训练，可以自行修改代码以支持，将[sft-405](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/f1680bf75e54f1b497eb7f2df8bd39fa89426089/scripts/training/run_clm_sft_with_peft.py#L405)的`LlamaForCausalLM`改成从自定义模型文件import再调试试试，或者添加`trust_remote_code=True`参数。

好的，我看YaRN有自定义的Llama模型类，除了把替换进去，还有其他需要修改的吗？
另外`trust_remote_code=True`不是在从hf上下载模型时才用到么，在这里需要用到吗？

**Comment by iMountTai** [comment]
`trust_remote_code`参数就是用来使用自定义模型类的，直接使用第一种方案吧(替换模型类)
