### ISSUE TITLE
Knowledge updation

### ISSUE THREAD

**Issue by ForestR** [ymcui/Chinese-LLaMA-Alpaca-2#527]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] I have read the [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki) and [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [LangChain](https://github.com/hwchase17/langchain), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), we recommend checking the corresponding project for solutions

### Type of Issue

Model inference

### Base Model

Chinese-Alpaca-2 (7B/13B)

### Operating System

Linux

### Describe your issue in detail

```
I want to know how could i upload files in gradio interface to update the knowledge of the base model?

Maybe i need to run the base model in privateGPT/localGPT?
```

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

```
# Please copy-and-paste your logs here.
```

**Comment by ymcui** [comment]
Using privateGPT or similar is a straightforward way, as our Gradio demo does not have an interface to upload user files.
