### ISSUE TITLE
1.3B模型是如何训练的？

### ISSUE THREAD

**Issue by makotov** [ymcui/Chinese-LLaMA-Alpaca-2#529]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Others

### 操作系统

None

**Comment by zxzjt** [comment]
1.3B如何全参微调，有知道的吗

**Comment by GoGoJoestar** [comment]
Chinese-LLaMA-2-1.3B是在Chinese-LLaMA-2-7B上取前四层，进行了增量预训练；Chinese-Alpaca-2-1.3B则是在Chinese-LLaMA-2-1.3B上进行了sft训练。
1.3B模型预训练和sft的训练数据与7/13B模型使用的数据相同。1.3B模型在训练时均采用全量参数训练的方式。

**Comment by GoGoJoestar** [comment]
> 1.3B如何全量sft指令微调，有大佬知道嘛

1.3B模型在结构上和7B相同，除了层数不一样。1.3B可直接使用原本的[精调脚本](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/ae46bcdd5dcff90efaf214e6f6da1344d08ec347/scripts/training/run_clm_sft_with_peft.py#L247)进行sft，如需全量参数精调，可以在训练脚本中传入参数 “--full_finetuning True”

**Comment by Rick-24** [comment]
您好，您的来信我已收到，我会尽快处理。      祝好！
