### ISSUE TITLE
运行模型时output norm.weight' notfound如何解决

### ISSUE THREAD

**Issue by dyqc** [ymcui/Chinese-LLaMA-Alpaca-2#534]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型量化和部署

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
请问在运行模型的时候output norm.weight not found 改如何解决 是下载的bin用convert转化成gguf格式

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
<img width="721" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/104749026/6e286993-4ec6-4eaf-8fc5-c9cf9f9a1083">

**Comment by ymcui** [comment]
这点信息很难给你看问题。
1）模型从哪儿下的？是否比对过SHA256（如果从HF下载）？
2）转换脚本换成convert.py是否有同样问题？
3）嫌麻烦就直接下载我们转换好的GGUF
