### ISSUE TITLE
微调验证损失趋势

### ISSUE THREAD

**Issue by Daniel-1997** [ymcui/Chinese-LLaMA-Alpaca-2#54]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

代码是周二上午拉取的，基座模型是Chinese Alpaca2， 进行lora指令精调的时候，在验证集上的损失都呈现这样的趋势：

1. 一开始可能有小幅度降低（可能没有）
2. 先上升后下降（幅度都不会很大）
3. 大幅度上升

微调两个不同的任务，验证损失都呈现这样的趋势，很好奇这样是否正常？因为关系到微调轮数设置，是否不再降低的时候就可以早停了？

下图中两个任务微调的batchsize分别是：60和120

### 依赖情况（代码类问题务必提供）

peft                     0.3.0.dev0
torch                    2.0.0
torchvision              0.15.1
transformers             4.31.0

### 运行日志或截图

![W B Chart 2023_8_3 08_22_19](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/59271872/23028953-590f-43f6-a70b-e07b375a26e1)

![W B Chart 2023_8_3 08_23_37](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/59271872/ae18f918-477f-446f-aded-6d1775f0828f)

**Comment by airaria** [comment]
和具体的训练/验证集大小、分布以及学习率、训练量等超参有关，不好一概而论。
