### ISSUE TITLE
词汇表扩充并且增量训练的具体流程和修改哪些部分？

### ISSUE THREAD

**Issue by Shajiu** [ymcui/Chinese-LLaMA-Alpaca-2#543]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Others

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
我想在LLama2上通过扩充满文词汇表来做增量训练，我怎么处理呢？
当前，我先用sp训练满文分词器，随后加载此模型并且跟llama词汇表合并，然后用此结果替换llama中的词汇表。随后做增量训练时出现错误？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
不是替换，是合并词表。建议你阅读我们的论文。
一代项目里也有相关细节：https://github.com/ymcui/Chinese-LLaMA-Alpaca/wiki/训练细节

**Comment by Shajiu** [comment]
催老师，我是这么做的
首先，拿了一批中文数据集用sentencepiece训练得到一个gogpt.model和gogpt.vocab；
然后，用sentencepiece分别加载llama2的的词汇和gogpt.mode，并且把gogpt.mode不在llama2词汇表中的加在llama2的后面，合并。生成special_tokens_map.json  tokenizer_config.json  tokenizer.model
最后，用这个合并的3个替换原先llama2下的对应三个文件。加载进行训练的。此时的词汇表大小为：90894，我在llama2下修改了config.json中的vocab_size:32000 改为vocab_size:90894训练时出现如下错误：
ValueError: Trying to set a tensor of shape torch.Size([32000, 4096]) in "weight" (which has shape torch.Size([90894, 4096])), this look incorrect.

另外我确实读了您的作品文章，但还是这块没弄明白。具体怎么合并以及继续增量训练。

**Comment by ymcui** [comment]
在我们的脚本上，基于原版llama-2 + 扩展词表不需要修改config.json的`vocab_size`。
这里有resize操作：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/main/scripts/training/run_clm_pt_with_peft.py#L625

**Comment by ymcui** [comment]
不是替换tokenizer，我们的脚本里有专门制定中文tokenizer的参数项，你按照教程设置就行了。
表格里面写的很清楚了：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/pt_scripts_zh#支持的训练模式
