### ISSUE TITLE
在精调的时候，如何让模型在指定的GPU上运行，而不是只在cuda:0上

### ISSUE THREAD

**Issue by ZhenHengDong** [ymcui/Chinese-LLaMA-Alpaca-2#544]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
根据指令精调模型进行微调时，发现只能在cuda:0上运行，我想指定device = torch.device("cuda:3" if torch.cuda.is_available() else "cpu")，但是又不生效，请问如何指定模型运行的GPU呢？
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
在运行脚本的最开始添加`CUDA_VISIBLE_DEVICES=3 torchrun ……`

**Comment by ZhenHengDong** [comment]
> 在运行脚本的最开始添加`CUDA_VISIBLE_DEVICES=3 torchrun ……`

非常感谢🙏
