### ISSUE TITLE
'padding_value' (position 3) must be float, not NoneType

### ISSUE THREAD

**Issue by liqinga** [ymcui/Chinese-LLaMA-Alpaca-2#545]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
tokenizer的设置不应该是一下内容么
chinese_tokenizer_path=/root/autodl-tmp/Chinese-LLaMA-Alpaca-2/scripts/tokenizer/tokenizer.model

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```
<img width="806" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/68682858/70ff2c92-f0fa-4429-a35b-2c9c4db3be92">

**Comment by iMountTai** [comment]
`chinese_tokenizer_path`是`tokenizer.model`所在的路径，还包含tokenizer的一些config文件。
