### ISSUE TITLE
finetune之后的模型使用

### ISSUE THREAD

**Issue by xiaoToby** [ymcui/Chinese-LLaMA-Alpaca-2#546]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```
使用finetune之后的模型(output/checkpoint-400),把finetune前的原始模型删掉后，运行失败。因为在adapter_config.json文件中有base_model_name_or_path，运行finetune之后的模型还是会读取这个路径，报OSError: Can't load the configuration of ‘xxx’错误。
我的问题是，因为想在容器环境内运行，不想让容器太辎重了，所以删掉了原始模型，我想问为什么还是会要读取原始模型？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by iMountTai** [comment]
finetune之后的模型(output/checkpoint-400)生成的是lora，需要和原始模型合并使用，你把原模型删了，肯定出错啊。
