### ISSUE TITLE
指令精调

### ISSUE THREAD

**Issue by dongziyu1016** [ymcui/Chinese-LLaMA-Alpaca-2#550]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型转换和合并

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
对chinese-alpaca-2 7B 进行指令精调训练全新的lora权重 ，之后，将llama2-7B 和 chinese-alpaca-2的lora和训练得到的lora合并。
在合并模型时报错：不能识别第二个lora参数


python scripts/merge_llama2_with_chinese_lora_low_mem.py --base_model llama2 --lora_model (lora, scripts/training/output_dir/sft_lora_model) --output_type huggingface --output_dir new_model
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
<img width="707" alt="Snipaste_2024-03-25_20-21-01" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/136042459/df4dc245-3b29-46d8-9642-a39fcba8303e">

```

**Comment by iMountTai** [comment]
应该是chinese-alpaca-2和训练得到的lora合并

**Comment by dongziyu1016** [comment]
好的，非常感谢！
