### ISSUE TITLE
多卡训练卡在加载模型

### ISSUE THREAD

**Issue by ymourenya** [ymcui/Chinese-LLaMA-Alpaca-2#552]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

其他问题

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

torchrun --nnodes 1 --nproc_per_node 4 run_clm_pt_with_peft.py 
你好，我把gpu的数量设置为4，采用单机多卡进行训练，为什么会卡在加载模型，我单卡进行训练没有这个问题
![图片](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/126037097/3363c48f-9541-4cdb-9a38-d6d6c54dcad1)

**Comment by iMountTai** [comment]
注释掉[L549](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/105f42ccc3570ee74530d7b4ee01d152a825d258/scripts/training/run_clm_pt_with_peft.py#L549)试试

**Comment by ymourenya** [comment]
你好，还是不行

**Comment by ymourenya** [comment]
> 注释掉[L549](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/105f42ccc3570ee74530d7b4ee01d152a825d258/scripts/training/run_clm_pt_with_peft.py#L549)试试

你好，我两张gpu也能训练，但是再往上就不行了，我用的A40

**Comment by ymourenya** [comment]
> 注释掉[L549](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/105f42ccc3570ee74530d7b4ee01d152a825d258/scripts/training/run_clm_pt_with_peft.py#L549)试试

还有就是能问一下你们是用的什么GPU进行预训练的吗

**Comment by iMountTai** [comment]
我们也是A40。[L244](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/105f42ccc3570ee74530d7b4ee01d152a825d258/scripts/training/run_clm_pt_with_peft.py#L244)改为False呢？双卡既然能跑，分布式代码应该是没有问题的。
