### ISSUE TITLE
训练垂直领域大模型应该基于哪个版本？

### ISSUE THREAD

**Issue by Zheng-Jay** [ymcui/Chinese-LLaMA-Alpaca-2#555]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

我们收集了垂直领域的预训练数据和指令数据（混合了通用数据），应该在Chinese-Llama-2还是Chinese-Alpaca2上二次开发呢？我看好像大家都是基于base做二次pt和sft，但是我不想浪费掉instruct版本的指令，基于哪个版本训效果更优呢？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by yourcaptain** [comment]
我也有相同的疑惑，盼答复。

**Comment by yourcaptain** [comment]
我也有相同的疑惑，盼答复。
