### ISSUE TITLE
HELP!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by xiaoToby** [ymcui/Chinese-LLaMA-Alpaca-2#562]
### Check before submitting issues

- [X] Make sure to pull the latest code, as some issues and bugs have been fixed.
- [X] I have read the [Wiki](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki) and [FAQ section](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/FAQ) AND searched for similar issues and did not find a similar problem or solution
- [X] Third-party plugin issues - e.g., [llama.cpp](https://github.com/ggerganov/llama.cpp), [LangChain](https://github.com/hwchase17/langchain), [text-generation-webui](https://github.com/oobabooga/text-generation-webui), we recommend checking the corresponding project for solutions

### Type of Issue

None

### Base Model

None

### Operating System

None

### Describe your issue in detail

```
# Please copy-and-paste your command here.
```
LLama3开源了，期待你们的Chinese-LLaMA-Alpaca-3！！！！！！！

### Dependencies (must be provided for code-related issues)

```
# Please copy-and-paste your dependencies here.
```

### Execution logs or screenshots

```
# Please copy-and-paste your logs here.
```

**Comment by ymcui** [comment]
可以关注后续：https://github.com/ymcui/Chinese-LLaMA-Alpaca-3
