### ISSUE TITLE
训练数据和测试数据开源了么?

### ISSUE THREAD

**Issue by chg0901** [ymcui/Chinese-LLaMA-Alpaca-2#566]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-Alpaca-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

```
### 人类偏好对齐（RLHF）版本评测

## 对齐水平

为评估中文模型与人类价值偏好对齐程度，我们自行构建了评测数据集，覆盖了道德、色情、毒品、暴力等人类价值偏好重点关注的多个方面。实验结果以价值体现正确率进行呈现（体现正确价值观题目数 / 总题数）
```

想问一下, 这个训练数据和测试数据开源了么, 想试一下自己调一个模型

**Comment by chg0901** [comment]
ddddd

**Comment by chg0901** [comment]
...........

**Comment by lyccyl1** [comment]
感觉没有，只能在他技术报告里，用api的指令微调数据做不到复现，只能做到相同规模的数据
