### ISSUE TITLE
chinese-llama-2-13b-hf可否直接用bf16继续预训练？

### ISSUE THREAD

**Issue by NLP-Learning** [ymcui/Chinese-LLaMA-Alpaca-2#572]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型训练与精调

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

您好，我基于chinese-llama-2-13b-hf作为基座模型，继续扩充了词表，并使用fp16继续预训练，但是一段时间后会遇到loss突刺，loss变得特别大且无法再收敛。我随后换了bf16，目前还在训练中，没有再loss突刺，但我突然想到chinese-llama-2-13b-hf是使用fp16这个精度训练的，我直接使用bf16基于chinese-llama-2-13b-hf继续预训练合理吗，或者能保证训练效果吗？

期待您的回答，感谢！

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
可以用bf16，相对更稳定一些。

**Comment by NLP-Learning** [comment]
> 可以用bf16，相对更稳定一些。

感谢老师回复，我还想再向您请教一个问题，我使用bf16继续预训练后，再使用fp16去sft可以吗？
