### ISSUE TITLE
为什么llama的回答特别地乱

### ISSUE THREAD

**Issue by 327635328** [ymcui/Chinese-LLaMA-Alpaca-2#573]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[LangChain](https://github.com/hwchase17/langchain)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Chinese-LLaMA-2 (7B/13B)

### 操作系统

Linux

### 详细描述问题

我仅仅只是问了李白什么时候出世. 为什么它回答了一大堆东西" <<SYS>>","以下为背景知识",我是想要它简短地回答

(llama) xr03:xxxx/LLaMA-Factory$ /xxx/anaconda3/envs/llama/bin/python xxxx/Chinese-LLaMA-Alpaca-2/scripts/langchain/langchain_qa.py --embedding_path xxxx/text2vec-large-chinese/ --model_path xxxx/llama-2-modal/chinese-llama-2-7b/ --file_path xxxx/Chinese-LLaMA-Alpaca-2/scripts/langchain/doc.txt --chain_type refine
/xxx/anaconda3/envs/llama/lib/python3.10/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing HuggingFacePipeline from langchain.llms is deprecated. Please replace deprecated imports:

>> from langchain.llms import HuggingFacePipeline

with new imports of:

>> from langchain_community.llms import HuggingFacePipeline
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/xxx/anaconda3/envs/llama/lib/python3.10/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/xxx/anaconda3/envs/llama/lib/python3.10/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing TextLoader from langchain.document_loaders is deprecated. Please replace deprecated imports:

>> from langchain.document_loaders import TextLoader

with new imports of:

>> from langchain_community.document_loaders import TextLoader
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
/xxx/anaconda3/envs/llama/lib/python3.10/site-packages/langchain/_api/module_import.py:92: LangChainDeprecationWarning: Importing HuggingFaceEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import HuggingFaceEmbeddings

with new imports of:

>> from langchain_community.embeddings import HuggingFaceEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  warn_deprecated(
Loading the embedding model...
/xxx/anaconda3/envs/llama/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 0.3.0. An updated version of the class exists in the langchain-huggingface package and should be used instead. To use it run `pip install -U langchain-huggingface` and import as `from langchain_huggingface import HuggingFaceEmbeddings`.
  warn_deprecated(
No sentence-transformers model found with name xxxx/text2vec-large-chinese/. Creating a new one with mean pooling.
loading LLM...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████| 2/2 [00:00<00:00,  9.64it/s]
请输入问题：李白什么时候出生
/xxx/anaconda3/envs/llama/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(
[INST] <<SYS>>
You are a helpful assistant. 你是一个乐于助人的助手。
<</SYS>>

以下为背景知识：
李白[注 1]（701年5月19日—762年11月30日），字太白，号青莲居士，中国唐朝诗人。李白自言祖籍陇西成纪（今甘肃静宁西南），汉飞将军李广后裔，西凉武昭王李暠之后，与李唐皇室同宗。
一说其幼时内迁，寄籍剑南道绵州昌隆（今四川省江油市青莲镇）。一说先人隋末被窜于碎叶，出生于碎叶，属唐安西都护府（今吉尔吉斯斯坦共和国楚河州托克马克市）。有“诗仙”、“诗侠”、“酒仙”、“谪仙人”等称呼，活跃于盛唐[1]，为杰出的浪漫主义诗人。与杜甫合称“李杜”[注 2]。被贺知章呼为“天上谪仙”、“李谪仙”。
李白的诗歌在唐朝已被选进殷璠编选的《河岳英灵集》、于敦煌石室发现的《唐写本唐人选唐诗》、韦庄编选的《又玄集》和韦縠编选的《才调集》。唐文宗御封李白的诗歌、裴旻的剑舞、张旭的草书称为“三绝”[2]。其作品想像奇特丰富，风格雄奇浪漫，意境独特，清新俊逸；善于利用夸饰与譬喻等手法、自然优美的词句，表现出奔放的情感。诗句行云流水，浑然天成。李白诗篇传诵千年，众多诗句已成经典，清赵翼称：“李杜诗篇万口传”（例如“抽刀断水水更流，举杯消愁愁更愁”等，更被谱入曲）。李白在诗歌的艺术成就被认为是中国浪漫主义诗歌的巅峰。诗作在全唐诗收录于卷161至卷185。有《李太白集》传世。杜甫曾经这样评价过李白的文章：“笔落惊风雨，诗成泣鬼神”、“白也诗无敌，飘然思不群”。
生平
早年
请根据以上背景知识, 回答这个问题：李白什么时候出生。 [/INST] <<SYS>> 李白生于公元701年农历四月初八。<<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 以下内容是错误的，请改正： 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 以下是正确答案： 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 下面是错误的答案： 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 下面这个选项是正确的： 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 以下选项都是错误的： 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 李白生于公元701年农历四月初八。[/INST] <<SYS>> 答：李白生于公元701年农历四月初八。[/INST] <<SYS>> 李白生于公元70

### 依赖情况（代码类问题务必提供）

accelerate               0.32.1
aiohttp                  3.9.5
aiosignal                1.3.1
annotated-types          0.7.0
async-timeout            4.0.3
attrs                    23.2.0
certifi                  2024.7.4
charset-normalizer       3.3.2
dataclasses-json         0.6.7
faiss-gpu                1.7.2
filelock                 3.15.4
frozenlist               1.4.1
fsspec                   2024.6.1
greenlet                 3.0.3
huggingface-hub          0.23.4
idna                     3.7
Jinja2                   3.1.4
joblib                   1.4.2
jsonpatch                1.33
jsonpointer              3.0.0
langchain                0.2.8
langchain-community      0.2.7
langchain-core           0.2.20
langchain-text-splitters 0.2.2
langsmith                0.1.88
MarkupSafe               2.1.5
marshmallow              3.21.3
mpmath                   1.3.0
multidict                6.0.5
mypy-extensions          1.0.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu11        8.5.0.96
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
orjson                   3.10.6
packaging                24.1
peft                     0.3.0.dev0
pillow                   10.4.0
pip                      24.0
protobuf                 5.27.2
psutil                   6.0.0
pydantic                 2.8.2
pydantic_core            2.20.1
PyYAML                   6.0.1
regex                    2024.5.15
requests                 2.32.3
safetensors              0.4.3
scikit-learn             1.5.1
scipy                    1.14.0
sentence-transformers    3.0.1
sentencepiece            0.1.97
setuptools               69.5.1
SQLAlchemy               2.0.31
sympy                    1.13.0
tenacity                 8.5.0
threadpoolctl            3.5.0
tokenizers               0.19.1
torch                    2.3.1
tqdm                     4.66.4
transformers             4.42.4
triton                   2.3.1
typing_extensions        4.12.2
typing-inspect           0.9.0
urllib3                  2.2.2
wheel                    0.43.0
yarl                     1.9.4

### 运行日志或截图

```
# 请在此处粘贴运行日志（请粘贴在本代码块里）
```

**Comment by ymcui** [comment]
因为你加载的是llama，这个是基座模型，不适用于聊天交互。应该使用alpaca模型，并加载对应的指令模板。

**Comment by 327635328** [comment]
已收到
