### ISSUE TITLE
 模型推理的速度很慢

### ISSUE THREAD

**Issue by amwork2020** [ymcui/Chinese-LLaMA-Alpaca-2#62]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
python inference_hf.py chinese-alpaca-2-7b  --use_vllm 的推理速度可以
但是python gradio_demo.py  --use_vllm  --gpus 0,1 的推理速度很慢为啥？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
无

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
无

**Comment by ymcui** [comment]
建议你先排查是因为gradio_demo慢还是因为你指定了两个gpu所以慢。

**Comment by amwork2020** [comment]
> 建议你先排查是因为gradio_demo慢还是因为你指定了两个gpu所以慢。

因为gradio_demo慢,如何解决？

**Comment by ymcui** [comment]
我们在colab上测试过，使用单个V100+启用vllm速度是比较快的。

**Comment by amwork2020** [comment]
> 我们在colab上测试过，使用单个V100+启用vllm速度是比较快的。

我是4块3090卡 24g，启用vllm 还是很慢不知道为啥，跟gpu卡有关系？
