### ISSUE TITLE
tokenizer是不是没对应好？

### ISSUE THREAD

**Issue by Zombiessss** [ymcui/Chinese-LLaMA-Alpaca-2#63]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
sft的时候load数据进来，发现数据的样本全部被做了错误映射，看看是否会有影响？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
![image](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/25706482/e8ac3f9f-fc65-4db6-b33b-587cad4a7c4e)

**Comment by airaria** [comment]
Tokenizer我们验证过没有问题。是不是加载的是旧cache? cache需要重新生成

**Comment by Zombiessss** [comment]
> Tokenizer我们验证过没有问题。是不是加载的是旧cache? cache需要重新生成

有道理 干 那pretrain就错了，白费两天

**Comment by KelleyYin** [comment]
请问加载作者提供的tokenizer之后，继续训练embedding层是冻结的还是继续会更新的？

**Comment by airaria** [comment]
> 请问加载作者提供的tokenizer之后，继续训练embedding层是冻结的还是继续会更新的？

embedding层训练与否和tokenizer无关，而是由训练脚本中的`modules_to_save`选项控制
