### ISSUE TITLE
chinese-alpaca-2训练数据格式问题

### ISSUE THREAD

**Issue by icoderzqliu** [ymcui/Chinese-LLaMA-Alpaca-2#64]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

请问一下如果要在自己数据上sft Chinese-alpaca-2，数据格式应该怎么准备，目前训练数据的格式都还是之前的{"instruction":"", "input":"", "output":""}，需要套上提到的新的template吗？
```
SYSTEM_PROMPT = """You are a helpful assistant. 你是一个乐于助人的助手。"""

PROMPT_TEMPLATE = (
    "[INST] <<SYS>>\n"
    "{system_prompt}\n"
    "<</SYS>>\n\n"
    "{instruction} [/INST]"
)

full_prompt = PROMPT_TEMPLATE.format_map({"instruction": your_instruction, "system_prompt": SYSTEM_PROMPT})
```
还是直接用instruction+input作为prompt就可以呢？

**Comment by airaria** [comment]
数据格式和之前一样，按`{"instruction":"", "input":"", "output":""}`格式准备就可以了。
SFT脚本里会自动给数据套上template。
