### ISSUE TITLE
预训练chinese-llama-2-7b时出错

### ISSUE THREAD

**Issue by desu9** [ymcui/Chinese-LLaMA-Alpaca-2#67]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

为什么会在loading checkpoint时出错？是因为显存不够吗？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```
pip list | grep -E 'transformers|peft|torch'
peft                     0.3.0.dev0
torch                    2.0.1
transformers             4.31.0

### 运行日志或截图

```
# 请在此处粘贴运行日志
```
[2023-08-03 08:32:36,402] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
2023-08-03 08:32:40.458334: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2023-08-03 08:32:42,753] [WARNING] [comm.py:152:init_deepspeed_backend] NCCL backend in DeepSpeed not yet implemented
[2023-08-03 08:32:42,753] [INFO] [comm.py:616:init_distributed] cdb=None
[2023-08-03 08:32:42,753] [INFO] [comm.py:643:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
08/03/2023 08:32:43 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
[INFO|configuration_utils.py:712] 2023-08-03 08:32:50,607 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--ziqingyang--chinese-llama-2-7b/snapshots/557b5cbd48a4a4eb5a08e975c4b6e11ac1ed4cbc/config.json
[INFO|configuration_utils.py:768] 2023-08-03 08:32:50,607 >> Model config LlamaConfig {
  "_name_or_path": "ziqingyang/chinese-llama-2-7b",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.31.0",
  "use_cache": true,
  "vocab_size": 55296
}

[INFO|tokenization_utils_base.py:1839] 2023-08-03 08:32:50,710 >> loading file tokenizer.model from cache at /root/.cache/huggingface/hub/models--ziqingyang--chinese-llama-2-7b/snapshots/557b5cbd48a4a4eb5a08e975c4b6e11ac1ed4cbc/tokenizer.model
[INFO|tokenization_utils_base.py:1839] 2023-08-03 08:32:50,710 >> loading file added_tokens.json from cache at None
[INFO|tokenization_utils_base.py:1839] 2023-08-03 08:32:50,710 >> loading file special_tokens_map.json from cache at /root/.cache/huggingface/hub/models--ziqingyang--chinese-llama-2-7b/snapshots/557b5cbd48a4a4eb5a08e975c4b6e11ac1ed4cbc/special_tokens_map.json
[INFO|tokenization_utils_base.py:1839] 2023-08-03 08:32:50,710 >> loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--ziqingyang--chinese-llama-2-7b/snapshots/557b5cbd48a4a4eb5a08e975c4b6e11ac1ed4cbc/tokenizer_config.json
[WARNING|logging.py:295] 2023-08-03 08:32:50,711 >> You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
08/03/2023 08:32:50 - INFO - __main__ - training datasets-t has been loaded from disk
Caching indices mapping at /content/Chinese-LLaMA-Alpaca-2/scripts/training/temp_data_cache_dir/t/train/cache-5ce72d5a2218009e.arrow
08/03/2023 08:32:50 - INFO - datasets.arrow_dataset - Caching indices mapping at /content/Chinese-LLaMA-Alpaca-2/scripts/training/temp_data_cache_dir/t/train/cache-5ce72d5a2218009e.arrow
Caching indices mapping at /content/Chinese-LLaMA-Alpaca-2/scripts/training/temp_data_cache_dir/t/train/cache-7bb07f6ff7076c43.arrow
08/03/2023 08:32:50 - INFO - datasets.arrow_dataset - Caching indices mapping at /content/Chinese-LLaMA-Alpaca-2/scripts/training/temp_data_cache_dir/t/train/cache-7bb07f6ff7076c43.arrow
08/03/2023 08:32:50 - INFO - __main__ - Num train_samples  3248
08/03/2023 08:32:50 - INFO - __main__ - Training example:
08/03/2023 08:32:50 - INFO - __main__ -  应该流畅而准确。<s> Text: ""I have a dream that one day this nation will rise up and live out the true meaning of its creed: 'We hold these truths to be self-evident, that all men are created equal.'""<s></s><s> Assistant: 我有一个梦想，希望有一天这个国家会振作起来，实现其信条的真正含义：“我们认为这些真理都是不言而喻的，即所有人生而平等。”<s></s> "<s> "<s> Human: 请你回答以下问题：2019年全球最受欢迎的旅游城市是哪个？<s></s><s> Assistant: 据《环球旅行》杂志发布的2019年全球最佳旅游城市排名，第一名是日本京都。京都以其古老的神社、庙宇和花园等著名景点吸引着大量游客前来。此外，其他入选前十名的城市还包括巴黎、罗马、布达佩斯、普拉古、华沙、纽约、马拉喀什、巴塞罗那和香港等。<s></s> "<s> "<s> Human: 列举三个方法来减轻焦虑和压力<s></s><s> Assistant: 1. 呼吸练习：深呼吸、放松呼吸等简单的呼吸练习可以让身体得到放松，减轻焦虑和压力。一般而言，只需花费几分钟就可以达到效果。<s><s> 2. 运动：运动是一种非常有效的减轻焦虑和压力的方法。进行一些简单的运动，例如散步、慢跑、瑜伽等，可以帮助身体释放紧张和充满焦虑的能量，同时还能提高身体的免疫力。<s><s> 3. 放松技巧：放松技巧是减轻焦虑和压力的另一种有效方法。例如，渐进性肌肉松弛法、冥想、温泉浴、按摩等，都可以帮助身体达到放松和舒适的状态，从而减轻焦虑和压力。<s></s> "<s> "<s> Human: 小明：李老板，你好，我是你打电话来的那个律师，我来为你解决那个让你困扰的案件。<s> 李老板：谢谢你来帮我，小明律师。我听说你是个非常有能力的年轻律师，我相信你能帮我赢得这个案子。<s> 小明：嗯，这案子确实不简单，但是没问题。我已经仔细研究了你提供的材料，对于你的情况，我有一些个人的看法。不知道你是否同意先听一听我的观点。<s> 李老板：当然，我非常愿意听听你的想法。请告诉我，小明律师。请总结以上对话的主要内容。<s></s><s>Ass
[INFO|modeling_utils.py:2603] 2023-08-03 08:32:50,837 >> loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--ziqingyang--chinese-llama-2-7b/snapshots/557b5cbd48a4a4eb5a08e975c4b6e11ac1ed4cbc/pytorch_model.bin.index.json
[INFO|modeling_utils.py:1172] 2023-08-03 08:32:50,838 >> Instantiating LlamaForCausalLM model under default dtype torch.float16.
[INFO|configuration_utils.py:599] 2023-08-03 08:32:50,839 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 0,
  "transformers_version": "4.31.0"
}

Loading checkpoint shards:   0% 0/2 [00:00<?, ?it/s]ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 3336) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
run_clm_pt_with_peft.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-03_08:33:39
  host      : 802dbb16712c
  rank      : 0 (local_rank: 0)
  exitcode  : -9 (pid: 3336)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 3336
=====================================================

**Comment by iMountTai** [comment]
显存是多少？也有可能是内存不足

**Comment by desu9** [comment]
> 显存是多少？也有可能是内存不足

显存16G是不是有点少，我已经把Bach_size减少到128了

**Comment by llmrainer** [comment]
大佬，想问下预训练的数据是什么格式的啊，可以给点case吗

**Comment by liyu19980601** [comment]
大佬，想问下预训练的数据是什么格式的啊，可以给点case吗
