### ISSUE TITLE
请问是否考虑训练一个 extended context 版本的模型？

### ISSUE THREAD

**Issue by jamesljl** [ymcui/Chinese-LLaMA-Alpaca-2#71]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

7月28日， together.ai 使用 FlashAttention2 训练了一个 extended context 版本的 LLaMA-2 ， context 长度达 32k。他们发表了以下博客说明: https://together.ai/blog/llama-2-7b-32k
llama 2 基准模型的最大context 为 4k tokens，感觉在商业应用上是否会有些限制？训练一个 extended context 版本的 LLaMA-2 是否会有帮助呢？

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by jamesljl** [comment]
另外，原来的 llama 模型 context 限制是 2k tokens ， 通过 SuperHot 可以扩展到 8k。前两天在 reddit 上看到有人说 SuperHot 也能把 llama 的 context 扩展。具体过程不详。

**Comment by ymcui** [comment]
不排除未来会推出，一期项目的时候我们就思考过，但当前这个feature并不是我们最关注的方面。
我们已经实现了基于NTK的上下文延长方法（无需二次训练），12K长度以内，PPL没有显著变化，可能对于大多数人也够用了。
