### ISSUE TITLE
無法利用LangChain.CTransformers 載入Chinese-Llama-2-7b ggml 模型

### ISSUE THREAD

**Issue by wennycooper** [ymcui/Chinese-LLaMA-Alpaca-2#81]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型推理

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

您好, 我有成功用llama.cpp 轉換出ggml格式的 llama-2-7b model.
使用./main -m ../llama-2-7b-combined/ggml-model-q6_K.bin  也能夠正常運作

但我用以下 langchain.llms CTransformers 的方法就無法載入模型.

```
def build_llm():
    # Local CTransformers model
    llm = CTransformers(model="../llama-2-7b-combined/ggml-model-q6_K.bin",
                        model_type="llama",
                        config={'max_new_tokens': 4096,
                                'temperature': 0.01}
                        )
```

## 錯誤訊息如下:
error loading model: unrecognized tensor type 14

llama_init_from_file: failed to load model
Traceback (most recent call last):
  File "/workspace/test/Llama-2-Open-Source-LLM-CPU-Inference/kkuei_main.py", line 34, in <module>
    llm = build_llm()
  File "/workspace/test/Llama-2-Open-Source-LLM-CPU-Inference/src/llm.py", line 23, in build_llm
    llm = CTransformers(model=cfg.MODEL_BIN_PATH,
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/ctransformers.py", line 70, in validate_environment
    values["client"] = AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/hub.py", line 157, in from_pretrained
    return LLM(
  File "/usr/local/lib/python3.10/dist-packages/ctransformers/llm.py", line 205, in __init__
    raise RuntimeError(
RuntimeError: Failed to create LLM 'llama' from 'models/ggml-model-q6_K.bin'.

### 依赖情况（代码类问题务必提供）

```
# pip list | grep -E 'transformers|peft|torch'
ctransformers            0.2.5
peft                     0.3.0.dev0
pytorch-quantization     2.1.2
sentence-transformers    2.2.2
torch                    2.0.1
torch-tensorrt           1.5.0.dev0
torchdata                0.7.0a0
torchtext                0.16.0a0
torchvision              0.16.0a0
transformers             4.31.0
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by wennycooper** [comment]
或是可否提供我用langchain 正確的載入模型的方式. 謝謝!

**Comment by ymcui** [comment]
你的代码里：
```
llm = CTransformers(model="../llama-2-7b-combined/ggml-model-q6_K.bin",
```
你的报错信息：
```
RuntimeError: Failed to create LLM 'llama' from 'models/ggml-model-q6_K.bin'.
```
模型的路径似乎不太一样。也可以试一下传入绝对路径而不是相对路径。

另外也可以参考一下我们的wiki：https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/langchain_zh

**Comment by wennycooper** [comment]
我改用 llama-cpp 就可以了

`
from langchain.llms import LlamaCpp
from langchain import PromptTemplate, LLMChain
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

# Callbacks support token-wise streaming
callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
# Verbose is required to pass to the callback manager

n_gpu_layers = 24  # Change this value based on your model and your GPU VRAM pool.
n_batch = 200  # Should be between 1 and n_ctx, consider the amount of VRAM in your GPU.

# Make sure the model path is correct for your system!
llm = LlamaCpp(
    model_path="/workspace/test/mymodel/ggml-model-q6_K.bin",
    n_gpu_layers=n_gpu_layers,
    n_batch=n_batch,
    callback_manager=callback_manager,
    verbose=True,
)

output = llm("Q: 請用Python語言 利用pytorch, 寫一個regression  範例     A: ", max_tokens=4096, stop=["Q:", "\n"], echo=True)
`

**Comment by wennycooper** [comment]
close issue
