### ISSUE TITLE
模型预训练用的llama-alpaca2基座训练的,PT用的txt文本1.5G的文本，只训练lora参数，为何最后得到的 adapter_model.bin 只有1K 为啥。

### ISSUE THREAD

**Issue by musellama** [ymcui/Chinese-LLaMA-Alpaca-2#82]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

Alpaca-2-7B

### 操作系统

Windows

### 详细描述问题

```
模型预训练用的llama-alpaca2基座训练的,PT用的txt文本1.5G的文本，只训练lora参数，为何最后得到的 adapter_model.bin 只有1K 为啥。
```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by musellama** [comment]
可否解决下问题呢

**Comment by ymcui** [comment]
自助参考：https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/711

**Comment by musellama** [comment]
> 自助参考：[ymcui/Chinese-LLaMA-羊驼#711](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/711)

run_clm_pt_with_peft.py 脚本 这段代编 去掉然后就可以了？ 
但是我想知道这段代码有什么影响呢，他的作用是什么。

old_state_dict = model.state_dict

model.state_dict = (
    lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())
).__get__(model, type(model))

**Comment by musellama** [comment]
咋们a

**Comment by Syno8** [comment]
@musellama 你的训练损失是什么样的？训练到最后能到多少？
