### ISSUE TITLE
能否也给一下合并后的sha256 值，我这推理有问题，不知是否是合并的问题

### ISSUE THREAD

**Issue by icowan** [ymcui/Chinese-LLaMA-Alpaca-2#87]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型转换和合并

### 基础模型

Alpaca-2-7B

### 操作系统

Linux

### 详细描述问题

```
$ python3 scripts/merge_llama2_with_chinese_lora_low_mem.py \
--base_model /data/llama/llama2-7b-hf/ \
--lora_model /data/chinese-alpaca-2-lora-7b/ \
--output_type huggingface \
--output_dir /data/output/merged-chinese-alpaca-2-7b-lora-hf/ \
--verbose
```

<img width="1188" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/6229526/8b12276c-8cc9-43e8-84b3-88ca04841d1f">

**Comment by airaria** [comment]
我们提供了[合并好的Chinese-Alapca-2-7B模型](https://huggingface.co/ziqingyang/chinese-alpaca-2-7b)
pytorch_model-00001-of-00002.bin: 182d552f893db16f7196afdf6ec13f05b43650985c9ce71f41f6d576e978c53f
pytorch_model-00002-of-00002.bin: 1f22e3d669ea912c4b0428fb4095f2068eb6192c89406ddd441de87ccec0c1b5

**Comment by ymcui** [comment]
不排除你用的推理方式存在问题的可能性。你用的时候套用Alpaca-2的模板了吗？

**Comment by icowan** [comment]
> 不排除你用的推理方式存在问题的可能性。你用的时候套用Alpaca-2的模板了吗？

用的是fastchat 做的推理

**Comment by ymcui** [comment]
建议你参考我们的推理代码（scripts/inference），不用指定模板效果无法保证。
