### ISSUE TITLE
支援繁體中文嗎?

### ISSUE THREAD

**Issue by compustar** [ymcui/Chinese-LLaMA-Alpaca-2#9]

**Comment by ymcui** [comment]
模型出来了之后你可以试试。

**Comment by ymcui** [comment]
现在我可以回答你了。以下是Alpaca-2-7B的输出示例。不过我更推荐你自己去体验一下。
<img width="1066" alt="image" src="https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/assets/16095339/74bccd81-9c39-465d-8ab1-49b43f0b6b63">
