### ISSUE TITLE
langchain_qa.py啥也不返回

### ISSUE THREAD

**Issue by xxm1668** [ymcui/Chinese-LLaMA-Alpaca-2#90]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

None

### 基础模型

None

### 操作系统

None

### 详细描述问题

```
# 请在此处粘贴运行代码（如没有可删除该代码块）
```
CUDA_VISIBLE_DEVICES=7 python3 src/langchain_qa.py \
    --file_path /home/house365ai/xxm/LLaMA-Efficient-Tuning/doc/1.txt \
    --embedding_path /home/house365ai/xxm/LLaMA-Efficient-Tuning/model/finetuned-model/model \
    --model_path /home/house365ai/xxm/firefly-llama2-13b-merge \
    --gpu_id 7

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```请输入问题：你是？
/home/house365ai/.conda/envs/xxm_new/lib/python3.10/site-packages/transformers/generation/utils.py:1255: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/house365ai/.conda/envs/xxm_new/lib/python3.10/site-packages/transformers/generation/utils.py:1346: UserWarning: Using `max_length`'s default (5120) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
langchain： 
请输入问题：1=1？
langchain： 
请输入问题：怎么了？
langchain： 
请输入问题：盘龙山庄的容积率多少？
langchain： 
请输入问题：

**Comment by iMountTai** [comment]
去掉`CUDA_VISIBLE_DEVICES=7`或者删掉`--gpu_id`

**Comment by xxm1668** [comment]
(xxm_new) house365ai@llm-a100:~/xxm/LLaMA-Efficient-Tuning$ CUDA_VISIBLE_DEVICES=7 python3 src/langchain_qa.py \
> --file_path /home/house365ai/xxm/LLaMA-Efficient-Tuning/doc/1.txt \
> --embedding_path /home/house365ai/xxm/LLaMA-Efficient-Tuning/model/finetuned-model/model \
> --model_path /home/house365ai/xxm/firefly-llama2-13b-merge
Loading the embedding model...
No sentence-transformers model found with name /home/house365ai/xxm/LLaMA-Efficient-Tuning/model/finetuned-model/model. Creating a new one with MEAN pooling.
[2023-08-08 00:51:56,606] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
loading LLM...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.64s/it]
请输入问题：你好
/home/house365ai/.conda/envs/xxm_new/lib/python3.10/site-packages/transformers/generation/utils.py:1255: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/house365ai/.conda/envs/xxm_new/lib/python3.10/site-packages/transformers/generation/utils.py:1346: UserWarning: Using `max_length`'s default (5120) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
langchain： 
请输入问题：你是？
langchain： 
请输入问题：

**Comment by xxm1668** [comment]
@iMountTai 还是无任何输出。。。

**Comment by iMountTai** [comment]
你用我们的chinese-alpaca-2-7b试试，这不是我们发布的模型，可能与内置的prompt有关

**Comment by xxm1668** [comment]
哦哦，如果把prompt更改之后，是否可以生效

**Comment by iMountTai** [comment]
不能保证，毕竟这是适配了我们模型的，`可能与内置的prompt有关`也只是一种可能性。

**Comment by xxm1668** [comment]
OK，多谢

**Comment by airaria** [comment]
可能是因为文档太长了，
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/blob/ffaff14aedabeaec61321ad081bdb2ff954b8f85/scripts/langchain/langchain_qa.py#L80
这里改成 
```
"max_new_tokens": 1024,
```
试试
