### ISSUE TITLE
llama.app项目中调用模型转换失败

### ISSUE THREAD

**Issue by SolarTorch** [ymcui/Chinese-LLaMA-Alpaca-2#94]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型转换和合并

### 基础模型

LLaMA-2-7B

### 操作系统

macOS

### 详细描述问题

```
python3 convert.py models/7B/
```

### 依赖情况（代码类问题务必提供）

```
sentence-transformers     2.2.2
torch                     2.0.1
torchaudio                0.12.1
torchvision               0.15.2
transformers              4.29.1
```

### 运行日志或截图

```
Traceback (most recent call last):
  File "/Users/myname/Documents/llama.cpp/convert.py", line 1326, in <module>
    main()
  File "/Users/myname/Documents/llama.cpp/convert.py", line 1318, in main
    output_type = pick_output_type(model, args.outtype)
  File "/Users/myname/Documents/llama.cpp/convert.py", line 1125, in pick_output_type
    wq_type = model["layers.0.attention.wq.weight"].data_type
KeyError: 'layers.0.attention.wq.weight'
```

**Comment by ymcui** [comment]
`models/7B`的目录文件结构？来源？

**Comment by ymcui** [comment]
> > `models/7B`的目录文件结构？来源？
> 
> 下载自Google Drive
> 
> `/Users/solartorch/Documents/llama.cpp/models/7B`

😅 目录结构是说让你ls一下看看目录下有什么文件。另外，建议你对比一下你下载的文件和我们huggingface上文件的SHA256是否一致。我尝试使用最新版llama.cpp，并没有出现你说的情况。

**Comment by SolarTorch** [comment]
> > > `models/7B`的目录文件结构？来源？
> > 
> > 
> > 下载自Google Drive
> > `/Users/solartorch/Documents/llama.cpp/models/7B`
> 
> 😅 目录结构是说让你ls一下看看目录下有什么文件。另外，建议你对比一下你下载的文件和我们huggingface上文件的SHA256是否一致。我尝试使用最新版llama.cpp，并没有出现你说的情况。

不好意思之前没理解。
```
SHA256.md				pytorch_model.bin.index.json
config.json				special_tokens_map.json
generation_config.json			tokenizer.model
pytorch_model-00001-of-00002-001.bin	tokenizer_config.json
pytorch_model-00002-of-00002-002.bin
```

我在hugging face上没有看到SHA256文件

**Comment by ymcui** [comment]
你列举的文件夹下也有SHA256.md。手动校验一下`pytorch_model*`文件的SHA256能否对的上？

**Comment by SolarTorch** [comment]
> 你列举的文件夹下也有SHA256.md。手动校验一下`pytorch_model*`文件的SHA256能否对的上？

好的我试一下

**Comment by SolarTorch** [comment]
> 你列举的文件夹下也有SHA256.md。手动校验一下`pytorch_model*`文件的SHA256能否对的上？

检查完毕只有`config.json`和`generation_config.json`没有通过

**Comment by ymcui** [comment]
文件名的问题你检查了吗？我看了一下google drive上的模型名并不是你列举的形式。你按我上面说的命名方式修改一下？

**Comment by ymcui** [comment]
另外，
1. 你用的是最新版的llama.cpp吗？如果不是的话建议拉取最新代码，清理之后重新编译`make clean && make`
2. 贴一下完整的运行记录。`python convert.py models/7B/`运行之后的内容。

**Comment by SolarTorch** [comment]
> 文件名的问题你检查了吗？我看了一下google drive上的模型名并不是你列举的形式。你按我上面说的命名方式修改一下？

果然是因为文件名的问题，可能跟Google drive对大文件的压缩解压重新命名有关
