### ISSUE TITLE
在chinese-llama-2-7b上lora sft时，用LlamaTokenizer会出现eval loss nan

### ISSUE THREAD

**Issue by yanghh2000** [ymcui/Chinese-LLaMA-Alpaca-2#95]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull），一些问题已被解决和修复。
- [X] 我已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案
- [x] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，同时建议到对应的项目中查找解决方案

### 问题类型

模型训练与精调

### 基础模型

LLaMA-2-7B

### 操作系统

Linux

### 详细描述问题

在chinese-llama-2-7b上lora sft时，用LlamaTokenizer会出现eval loss nan，但换成AutoTokenizer（fastTokenizer）之后不会nan，似乎与fastTokenizer中\</s\>的编码有关，请问预训练是用的是fastTokenizer吗？

### 依赖情况（代码类问题务必提供）

```
peft                      0.4.0
torch                     1.13.1
torchaudio                0.13.1
torchvision               0.14.1
transformers              4.31.0
```

### 运行日志或截图

```
# 请在此处粘贴运行日志
```

**Comment by airaria** [comment]
我们在预训练和精调使用的是LlamaTokenizer（非fast版本），没有出现过eval loss nan的情况。
你有没有在一段测试文本上比对过AutoTokenizer和LlamaTokenizer的分词结果差异？

**Comment by yanghh2000** [comment]
> 我们在预训练和精调使用的是LlamaTokenizer（非fast版本），没有出现过eval loss nan的情况。 你有没有在一段测试文本上比对过AutoTokenizer和LlamaTokenizer的分词结果差异？

我在debug时发现，用slowTokenizer训练时，</s>（id为2）之后的几个pad token（id 32000）对应的hidden states为nan，但是用fastTokenizer训练，</s>编码为[829, 29879, 29958]，之后的pad token对应hidden states不会出现nan。

我的微调模板是 <s> + "{instruction} \nInput:{input}\nOutput:" + target + </s>

**Comment by airaria** [comment]
</s>的id为2是正常的；
</s>的id为[829, 29879, 29958]的原因可是tokenizer没有把</s>当作special token，而当成正常字符串分词了。
我用AutoTokenizer没有出现这样的情况，建议检查下tokenizer的配置文件有没有问题，以及更新transformers版本

**Comment by yanghh2000** [comment]
问题似乎是由模型量化引起的，qlora时使用fp16会有上述问题，换成普通lora或者bf16就不会出现loss nan了。
